# This file automatically generated by skymarshal
# DO NOT MODIFY BY HAND
# fmt: off
# isort: off

from __future__ import annotations

import copy
import typing as T

from io import BytesIO
import struct

class algebraics_t(object):
    __slots__: T.List[str] = ["R11", "R12", "R13", "R21", "R22", "R23", "R31", "R32", "R33"]

    def __init__(
        self,
        R11: float=0.0,
        R12: float=0.0,
        R13: float=0.0,
        R21: float=0.0,
        R22: float=0.0,
        R23: float=0.0,
        R31: float=0.0,
        R32: float=0.0,
        R33: float=0.0,
        _skip_initialize: bool=False,
    ) -> None:
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize:
            return
        self.R11: float = R11
        self.R12: float = R12
        self.R13: float = R13
        self.R21: float = R21
        self.R22: float = R22
        self.R23: float = R23
        self.R31: float = R31
        self.R32: float = R32
        self.R33: float = R33

    @staticmethod
    def from_all_fields(
        R11: float,
        R12: float,
        R13: float,
        R21: float,
        R22: float,
        R23: float,
        R31: float,
        R32: float,
        R33: float,
    ) -> algebraics_t:
        return algebraics_t(
            R11=R11,
            R12=R12,
            R13=R13,
            R21=R21,
            R22=R22,
            R23=R23,
            R31=R31,
            R32=R32,
            R33=R33,
        )

    @staticmethod
    def _skytype_meta() -> T.Dict[str, str]:
        return dict(
            type="struct",
            package="sym",
            name="algebraics_t",
        )

    @classmethod
    def _default(cls) -> algebraics_t:
        return cls()

    def __repr__(self) -> str:
        return "algebraics_t({})".format(
            ", ".join("{}={}".format(name, repr(getattr(self, name))) for name in self.__slots__))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, algebraics_t):
            return NotImplemented
        return (
            (self.R11==other.R11) and
            (self.R12==other.R12) and
            (self.R13==other.R13) and
            (self.R21==other.R21) and
            (self.R22==other.R22) and
            (self.R23==other.R23) and
            (self.R31==other.R31) and
            (self.R32==other.R32) and
            (self.R33==other.R33)
        )
    # Disallow hashing for python struct lcmtypes.
    __hash__ = None  # type: ignore[assignment]

    def encode(self) -> bytes:
        buf = BytesIO()
        buf.write(algebraics_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf: T.BinaryIO) -> None:
        buf.write(algebraics_t._CACHED_STRUCT_0.pack(self.R11, self.R12, self.R13, self.R21, self.R22, self.R23, self.R31, self.R32, self.R33))

    @staticmethod
    def decode(data: T.Union[bytes, T.BinaryIO]) -> algebraics_t:
        # NOTE(eric): This function can technically accept either a BinaryIO or
        # anything that supports the C++ Buffer Protocol,
        # which is unspecifiable in type hints.

        if hasattr(data, "read"):
            # NOTE(eric): mypy isn't able to figure out the hasattr check
            buf = T.cast(T.BinaryIO, data)
        else:
            buf = BytesIO(T.cast(bytes, data))

        if buf.read(8) != algebraics_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return algebraics_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf: T.BinaryIO) -> algebraics_t:
        self = algebraics_t(_skip_initialize=True)
        self.R11, self.R12, self.R13, self.R21, self.R22, self.R23, self.R31, self.R32, self.R33 = algebraics_t._CACHED_STRUCT_0.unpack(buf.read(72))
        return self

    @staticmethod
    def _get_hash_recursive(parents: T.List[T.Type]) -> int:
        if algebraics_t in parents: return 0
        tmphash = (0x1555f7bf5a8c563) & 0xffffffffffffffff
        tmphash = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash

    _packed_fingerprint: T.Optional[bytes] = None

    @staticmethod
    def _get_packed_fingerprint() -> bytes:
        if algebraics_t._packed_fingerprint is None:
            algebraics_t._packed_fingerprint = struct.pack(">Q", algebraics_t._get_hash_recursive([]))
        return algebraics_t._packed_fingerprint

    def deepcopy(self, **kwargs: T.Any) -> algebraics_t:
        """
        Deep copy of this LCM type

        Returns a copy w/ members specified by kwargs replaced with new values specified by kwargs.
        """
        result = copy.deepcopy(self)
        for key in kwargs:
            if not hasattr(result, key):
                raise KeyError("Type algebraics_t does not have attribute: " + str(key))
            setattr(result, key, kwargs[key])
        return result

    _CACHED_STRUCT_0 = struct.Struct(">ddddddddd")
