# This file automatically generated by skymarshal
# DO NOT MODIFY BY HAND
# fmt: off
# isort: off

from __future__ import annotations

import copy
import typing as T

from io import BytesIO
import struct

class derivatives_t(object):
    __slots__: T.List[str] = ["px", "py", "pz", "vx", "vy", "vz", "qw", "qx", "qy", "qz"]

    def __init__(
        self,
        px: float=0.0,
        py: float=0.0,
        pz: float=0.0,
        vx: float=0.0,
        vy: float=0.0,
        vz: float=0.0,
        qw: float=0.0,
        qx: float=0.0,
        qy: float=0.0,
        qz: float=0.0,
        _skip_initialize: bool=False,
    ) -> None:
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize:
            return
        self.px: float = px
        self.py: float = py
        self.pz: float = pz
        self.vx: float = vx
        self.vy: float = vy
        self.vz: float = vz
        self.qw: float = qw
        self.qx: float = qx
        self.qy: float = qy
        self.qz: float = qz

    @staticmethod
    def from_all_fields(
        px: float,
        py: float,
        pz: float,
        vx: float,
        vy: float,
        vz: float,
        qw: float,
        qx: float,
        qy: float,
        qz: float,
    ) -> derivatives_t:
        return derivatives_t(
            px=px,
            py=py,
            pz=pz,
            vx=vx,
            vy=vy,
            vz=vz,
            qw=qw,
            qx=qx,
            qy=qy,
            qz=qz,
        )

    @staticmethod
    def _skytype_meta() -> T.Dict[str, str]:
        return dict(
            type="struct",
            package="sym",
            name="derivatives_t",
        )

    @classmethod
    def _default(cls) -> derivatives_t:
        return cls()

    def __repr__(self) -> str:
        return "derivatives_t({})".format(
            ", ".join("{}={}".format(name, repr(getattr(self, name))) for name in self.__slots__))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, derivatives_t):
            return NotImplemented
        return (
            (self.px==other.px) and
            (self.py==other.py) and
            (self.pz==other.pz) and
            (self.vx==other.vx) and
            (self.vy==other.vy) and
            (self.vz==other.vz) and
            (self.qw==other.qw) and
            (self.qx==other.qx) and
            (self.qy==other.qy) and
            (self.qz==other.qz)
        )
    # Disallow hashing for python struct lcmtypes.
    __hash__ = None  # type: ignore[assignment]

    def encode(self) -> bytes:
        buf = BytesIO()
        buf.write(derivatives_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf: T.BinaryIO) -> None:
        buf.write(derivatives_t._CACHED_STRUCT_0.pack(self.px, self.py, self.pz, self.vx, self.vy, self.vz, self.qw, self.qx, self.qy, self.qz))

    @staticmethod
    def decode(data: T.Union[bytes, T.BinaryIO]) -> derivatives_t:
        # NOTE(eric): This function can technically accept either a BinaryIO or
        # anything that supports the C++ Buffer Protocol,
        # which is unspecifiable in type hints.

        if hasattr(data, "read"):
            # NOTE(eric): mypy isn't able to figure out the hasattr check
            buf = T.cast(T.BinaryIO, data)
        else:
            buf = BytesIO(T.cast(bytes, data))

        if buf.read(8) != derivatives_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return derivatives_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf: T.BinaryIO) -> derivatives_t:
        self = derivatives_t(_skip_initialize=True)
        self.px, self.py, self.pz, self.vx, self.vy, self.vz, self.qw, self.qx, self.qy, self.qz = derivatives_t._CACHED_STRUCT_0.unpack(buf.read(80))
        return self

    @staticmethod
    def _get_hash_recursive(parents: T.List[T.Type]) -> int:
        if derivatives_t in parents: return 0
        tmphash = (0x407c71b88e190fa3) & 0xffffffffffffffff
        tmphash = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash

    _packed_fingerprint: T.Optional[bytes] = None

    @staticmethod
    def _get_packed_fingerprint() -> bytes:
        if derivatives_t._packed_fingerprint is None:
            derivatives_t._packed_fingerprint = struct.pack(">Q", derivatives_t._get_hash_recursive([]))
        return derivatives_t._packed_fingerprint

    def deepcopy(self, **kwargs: T.Any) -> derivatives_t:
        """
        Deep copy of this LCM type

        Returns a copy w/ members specified by kwargs replaced with new values specified by kwargs.
        """
        result = copy.deepcopy(self)
        for key in kwargs:
            if not hasattr(result, key):
                raise KeyError("Type derivatives_t does not have attribute: " + str(key))
            setattr(result, key, kwargs[key])
        return result

    _CACHED_STRUCT_0 = struct.Struct(">dddddddddd")
