# This file automatically generated by skymarshal
# DO NOT MODIFY BY HAND
# fmt: off
# isort: off

from __future__ import annotations

import copy
import typing as T

from io import BytesIO
import struct

class external_inputs_t(object):
    __slots__: T.List[str] = ["wx", "wy", "wz", "fx", "fy", "fz"]

    def __init__(
        self,
        wx: float=0.0,
        wy: float=0.0,
        wz: float=0.0,
        fx: float=0.0,
        fy: float=0.0,
        fz: float=0.0,
        _skip_initialize: bool=False,
    ) -> None:
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize:
            return
        self.wx: float = wx
        self.wy: float = wy
        self.wz: float = wz
        self.fx: float = fx
        self.fy: float = fy
        self.fz: float = fz

    @staticmethod
    def from_all_fields(
        wx: float,
        wy: float,
        wz: float,
        fx: float,
        fy: float,
        fz: float,
    ) -> external_inputs_t:
        return external_inputs_t(
            wx=wx,
            wy=wy,
            wz=wz,
            fx=fx,
            fy=fy,
            fz=fz,
        )

    @staticmethod
    def _skytype_meta() -> T.Dict[str, str]:
        return dict(
            type="struct",
            package="sym",
            name="external_inputs_t",
        )

    @classmethod
    def _default(cls) -> external_inputs_t:
        return cls()

    def __repr__(self) -> str:
        return "external_inputs_t({})".format(
            ", ".join("{}={}".format(name, repr(getattr(self, name))) for name in self.__slots__))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, external_inputs_t):
            return NotImplemented
        return (
            (self.wx==other.wx) and
            (self.wy==other.wy) and
            (self.wz==other.wz) and
            (self.fx==other.fx) and
            (self.fy==other.fy) and
            (self.fz==other.fz)
        )
    # Disallow hashing for python struct lcmtypes.
    __hash__ = None  # type: ignore[assignment]

    def encode(self) -> bytes:
        buf = BytesIO()
        buf.write(external_inputs_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf: T.BinaryIO) -> None:
        buf.write(external_inputs_t._CACHED_STRUCT_0.pack(self.wx, self.wy, self.wz, self.fx, self.fy, self.fz))

    @staticmethod
    def decode(data: T.Union[bytes, T.BinaryIO]) -> external_inputs_t:
        # NOTE(eric): This function can technically accept either a BinaryIO or
        # anything that supports the C++ Buffer Protocol,
        # which is unspecifiable in type hints.

        if hasattr(data, "read"):
            # NOTE(eric): mypy isn't able to figure out the hasattr check
            buf = T.cast(T.BinaryIO, data)
        else:
            buf = BytesIO(T.cast(bytes, data))

        if buf.read(8) != external_inputs_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return external_inputs_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf: T.BinaryIO) -> external_inputs_t:
        self = external_inputs_t(_skip_initialize=True)
        self.wx, self.wy, self.wz, self.fx, self.fy, self.fz = external_inputs_t._CACHED_STRUCT_0.unpack(buf.read(48))
        return self

    @staticmethod
    def _get_hash_recursive(parents: T.List[T.Type]) -> int:
        if external_inputs_t in parents: return 0
        tmphash = (0xd58f02b00c464e77) & 0xffffffffffffffff
        tmphash = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash

    _packed_fingerprint: T.Optional[bytes] = None

    @staticmethod
    def _get_packed_fingerprint() -> bytes:
        if external_inputs_t._packed_fingerprint is None:
            external_inputs_t._packed_fingerprint = struct.pack(">Q", external_inputs_t._get_hash_recursive([]))
        return external_inputs_t._packed_fingerprint

    def deepcopy(self, **kwargs: T.Any) -> external_inputs_t:
        """
        Deep copy of this LCM type

        Returns a copy w/ members specified by kwargs replaced with new values specified by kwargs.
        """
        result = copy.deepcopy(self)
        for key in kwargs:
            if not hasattr(result, key):
                raise KeyError("Type external_inputs_t does not have attribute: " + str(key))
            setattr(result, key, kwargs[key])
        return result

    _CACHED_STRUCT_0 = struct.Struct(">dddddd")
