# This file automatically generated by skymarshal
# DO NOT MODIFY BY HAND
# fmt: off
# isort: off

from __future__ import annotations

import copy
import typing as T

from io import BytesIO
import struct

class model_outputs_t(object):
    __slots__: T.List[str] = ["ax", "ay", "az"]

    def __init__(
        self,
        ax: float=0.0,
        ay: float=0.0,
        az: float=0.0,
        _skip_initialize: bool=False,
    ) -> None:
        """ If _skip_initialize is True, all other constructor arguments are ignored """
        if _skip_initialize:
            return
        self.ax: float = ax
        self.ay: float = ay
        self.az: float = az

    @staticmethod
    def from_all_fields(
        ax: float,
        ay: float,
        az: float,
    ) -> model_outputs_t:
        return model_outputs_t(
            ax=ax,
            ay=ay,
            az=az,
        )

    @staticmethod
    def _skytype_meta() -> T.Dict[str, str]:
        return dict(
            type="struct",
            package="sym",
            name="model_outputs_t",
        )

    @classmethod
    def _default(cls) -> model_outputs_t:
        return cls()

    def __repr__(self) -> str:
        return "model_outputs_t({})".format(
            ", ".join("{}={}".format(name, repr(getattr(self, name))) for name in self.__slots__))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, model_outputs_t):
            return NotImplemented
        return (
            (self.ax==other.ax) and
            (self.ay==other.ay) and
            (self.az==other.az)
        )
    # Disallow hashing for python struct lcmtypes.
    __hash__ = None  # type: ignore[assignment]

    def encode(self) -> bytes:
        buf = BytesIO()
        buf.write(model_outputs_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf: T.BinaryIO) -> None:
        buf.write(model_outputs_t._CACHED_STRUCT_0.pack(self.ax, self.ay, self.az))

    @staticmethod
    def decode(data: T.Union[bytes, T.BinaryIO]) -> model_outputs_t:
        # NOTE(eric): This function can technically accept either a BinaryIO or
        # anything that supports the C++ Buffer Protocol,
        # which is unspecifiable in type hints.

        if hasattr(data, "read"):
            # NOTE(eric): mypy isn't able to figure out the hasattr check
            buf = T.cast(T.BinaryIO, data)
        else:
            buf = BytesIO(T.cast(bytes, data))

        if buf.read(8) != model_outputs_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return model_outputs_t._decode_one(buf)

    @staticmethod
    def _decode_one(buf: T.BinaryIO) -> model_outputs_t:
        self = model_outputs_t(_skip_initialize=True)
        self.ax, self.ay, self.az = model_outputs_t._CACHED_STRUCT_0.unpack(buf.read(24))
        return self

    @staticmethod
    def _get_hash_recursive(parents: T.List[T.Type]) -> int:
        if model_outputs_t in parents: return 0
        tmphash = (0x7218d588be78033a) & 0xffffffffffffffff
        tmphash = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash

    _packed_fingerprint: T.Optional[bytes] = None

    @staticmethod
    def _get_packed_fingerprint() -> bytes:
        if model_outputs_t._packed_fingerprint is None:
            model_outputs_t._packed_fingerprint = struct.pack(">Q", model_outputs_t._get_hash_recursive([]))
        return model_outputs_t._packed_fingerprint

    def deepcopy(self, **kwargs: T.Any) -> model_outputs_t:
        """
        Deep copy of this LCM type

        Returns a copy w/ members specified by kwargs replaced with new values specified by kwargs.
        """
        result = copy.deepcopy(self)
        for key in kwargs:
            if not hasattr(result, key):
                raise KeyError("Type model_outputs_t does not have attribute: " + str(key))
            setattr(result, key, kwargs[key])
        return result

    _CACHED_STRUCT_0 = struct.Struct(">ddd")
