
/**
 * AttitudeControl.c — Generated by Rumoca
 */
#include "AttitudeControl.h"

static void AttitudeControl_algebraics(AttitudeControl_t *m, real_t t) {

    const real_t e_int_1 = m->e_int_1; (void)e_int_1;
    const real_t e_int_2 = m->e_int_2; (void)e_int_2;
    const real_t e_int_3 = m->e_int_3; (void)e_int_3;

    const real_t q_1 = m->q_1; (void)q_1;
    const real_t q_2 = m->q_2; (void)q_2;
    const real_t q_3 = m->q_3; (void)q_3;
    const real_t q_4 = m->q_4; (void)q_4;
    const real_t q_r_1 = m->q_r_1; (void)q_r_1;
    const real_t q_r_2 = m->q_r_2; (void)q_r_2;
    const real_t q_r_3 = m->q_r_3; (void)q_r_3;
    const real_t q_r_4 = m->q_r_4; (void)q_r_4;

    const real_t Kp_1 = m->Kp_1; (void)Kp_1;
    const real_t Kp_2 = m->Kp_2; (void)Kp_2;
    const real_t Kp_3 = m->Kp_3; (void)Kp_3;
    const real_t Ki_1 = m->Ki_1; (void)Ki_1;
    const real_t Ki_2 = m->Ki_2; (void)Ki_2;
    const real_t Ki_3 = m->Ki_3; (void)Ki_3;
    real_t q_err_w = m->q_err_w;
    real_t e_1 = m->e_1;
    real_t e_2 = m->e_2;
    real_t e_3 = m->e_3;
    real_t omega_1 = m->omega_1;
    real_t omega_2 = m->omega_2;
    real_t omega_3 = m->omega_3;
    (void)t;
    q_err_w = ((((q_1 * q_r_1) + (q_2 * q_r_2)) + (q_3 * q_r_3)) + (q_4 * q_r_4));
    m->q_err_w = q_err_w;
    e_1 = ((2 * ((q_err_w >= 0) ? 1 : (-1))) * ((1 == 1) ? ((((-(q_2 * q_r_1)) + (q_1 * q_r_2)) + (q_4 * q_r_3)) - (q_3 * q_r_4)) : ((1 == 2) ? ((((-(q_3 * q_r_1)) - (q_4 * q_r_2)) + (q_1 * q_r_3)) + (q_2 * q_r_4)) : ((((-(q_4 * q_r_1)) + (q_3 * q_r_2)) - (q_2 * q_r_3)) + (q_1 * q_r_4)))));
    m->e_1 = e_1;
    e_2 = ((2 * ((q_err_w >= 0) ? 1 : (-1))) * ((2 == 1) ? ((((-(q_2 * q_r_1)) + (q_1 * q_r_2)) + (q_4 * q_r_3)) - (q_3 * q_r_4)) : ((2 == 2) ? ((((-(q_3 * q_r_1)) - (q_4 * q_r_2)) + (q_1 * q_r_3)) + (q_2 * q_r_4)) : ((((-(q_4 * q_r_1)) + (q_3 * q_r_2)) - (q_2 * q_r_3)) + (q_1 * q_r_4)))));
    m->e_2 = e_2;
    e_3 = ((2 * ((q_err_w >= 0) ? 1 : (-1))) * ((3 == 1) ? ((((-(q_2 * q_r_1)) + (q_1 * q_r_2)) + (q_4 * q_r_3)) - (q_3 * q_r_4)) : ((3 == 2) ? ((((-(q_3 * q_r_1)) - (q_4 * q_r_2)) + (q_1 * q_r_3)) + (q_2 * q_r_4)) : ((((-(q_4 * q_r_1)) + (q_3 * q_r_2)) - (q_2 * q_r_3)) + (q_1 * q_r_4)))));
    m->e_3 = e_3;
    omega_1 = ((Kp_1 * e_1) + (Ki_1 * e_int_1));
    m->omega_1 = omega_1;
    omega_2 = ((Kp_2 * e_2) + (Ki_2 * e_int_2));
    m->omega_2 = omega_2;
    omega_3 = ((Kp_3 * e_3) + (Ki_3 * e_int_3));
    m->omega_3 = omega_3;
}

void AttitudeControl_derivatives(const AttitudeControl_t *m, real_t t, real_t xdot[ATTITUDECONTROL_N_X]) {

    const real_t e_int_1 = m->e_int_1; (void)e_int_1;
    const real_t e_int_2 = m->e_int_2; (void)e_int_2;
    const real_t e_int_3 = m->e_int_3; (void)e_int_3;

    const real_t q_err_w = m->q_err_w; (void)q_err_w;
    const real_t e_1 = m->e_1; (void)e_1;
    const real_t e_2 = m->e_2; (void)e_2;
    const real_t e_3 = m->e_3; (void)e_3;

    const real_t q_1 = m->q_1; (void)q_1;
    const real_t q_2 = m->q_2; (void)q_2;
    const real_t q_3 = m->q_3; (void)q_3;
    const real_t q_4 = m->q_4; (void)q_4;
    const real_t q_r_1 = m->q_r_1; (void)q_r_1;
    const real_t q_r_2 = m->q_r_2; (void)q_r_2;
    const real_t q_r_3 = m->q_r_3; (void)q_r_3;
    const real_t q_r_4 = m->q_r_4; (void)q_r_4;

    const real_t Kp_1 = m->Kp_1; (void)Kp_1;
    const real_t Kp_2 = m->Kp_2; (void)Kp_2;
    const real_t Kp_3 = m->Kp_3; (void)Kp_3;
    const real_t Ki_1 = m->Ki_1; (void)Ki_1;
    const real_t Ki_2 = m->Ki_2; (void)Ki_2;
    const real_t Ki_3 = m->Ki_3; (void)Ki_3;

    const real_t omega_1 = m->omega_1; (void)omega_1;
    const real_t omega_2 = m->omega_2; (void)omega_2;
    const real_t omega_3 = m->omega_3; (void)omega_3;
    (void)t;
    xdot[0] = e_1;
    xdot[1] = e_2;
    xdot[2] = e_3;
}

void AttitudeControl_init(AttitudeControl_t *m) {
    real_t Kp_1 = REAL_C(0.0);
    real_t Kp_2 = REAL_C(0.0);
    real_t Kp_3 = REAL_C(0.0);
    real_t Ki_1 = REAL_C(0.0);
    real_t Ki_2 = REAL_C(0.0);
    real_t Ki_3 = REAL_C(0.0);
    Kp_1 = 2;
    m->Kp_1 = Kp_1;
    Kp_2 = 2;
    m->Kp_2 = Kp_2;
    Kp_3 = 1;
    m->Kp_3 = Kp_3;
    Ki_1 = 0;
    m->Ki_1 = Ki_1;
    Ki_2 = 0;
    m->Ki_2 = Ki_2;
    Ki_3 = 0;
    m->Ki_3 = Ki_3;
    m->e_int_1 = 0;
    m->e_int_2 = 0;
    m->e_int_3 = 0;
    m->q_1 = 0.0;
    m->q_2 = 0.0;
    m->q_3 = 0.0;
    m->q_4 = 0.0;
    m->q_r_1 = 0.0;
    m->q_r_2 = 0.0;
    m->q_r_3 = 0.0;
    m->q_r_4 = 0.0;
    AttitudeControl_algebraics(m, REAL_C(0.0));
}

void AttitudeControl_step(AttitudeControl_t *m, real_t t, real_t dt) {
    real_t k1[ATTITUDECONTROL_N_X], k2[ATTITUDECONTROL_N_X];
    real_t k3[ATTITUDECONTROL_N_X], k4[ATTITUDECONTROL_N_X];
    real_t x_save[ATTITUDECONTROL_N_X];
    x_save[0] = m->e_int_1;
    x_save[1] = m->e_int_2;
    x_save[2] = m->e_int_3;

    AttitudeControl_algebraics(m, t);
    AttitudeControl_derivatives(m, t, k1);

    m->e_int_1 = x_save[0] + REAL_C(0.5) * dt * k1[0];
    m->e_int_2 = x_save[1] + REAL_C(0.5) * dt * k1[1];
    m->e_int_3 = x_save[2] + REAL_C(0.5) * dt * k1[2];
    AttitudeControl_algebraics(m, t + REAL_C(0.5) * dt);
    AttitudeControl_derivatives(m, t + REAL_C(0.5) * dt, k2);

    m->e_int_1 = x_save[0] + REAL_C(0.5) * dt * k2[0];
    m->e_int_2 = x_save[1] + REAL_C(0.5) * dt * k2[1];
    m->e_int_3 = x_save[2] + REAL_C(0.5) * dt * k2[2];
    AttitudeControl_algebraics(m, t + REAL_C(0.5) * dt);
    AttitudeControl_derivatives(m, t + REAL_C(0.5) * dt, k3);

    m->e_int_1 = x_save[0] + REAL_C(1.0) * dt * k3[0];
    m->e_int_2 = x_save[1] + REAL_C(1.0) * dt * k3[1];
    m->e_int_3 = x_save[2] + REAL_C(1.0) * dt * k3[2];
    AttitudeControl_algebraics(m, t + dt);
    AttitudeControl_derivatives(m, t + dt, k4);
    m->e_int_1 = x_save[0] + (dt / REAL_C(6.0)) * (k1[0] + REAL_C(2.0) * k2[0] + REAL_C(2.0) * k3[0] + k4[0]);
    m->e_int_2 = x_save[1] + (dt / REAL_C(6.0)) * (k1[1] + REAL_C(2.0) * k2[1] + REAL_C(2.0) * k3[1] + k4[1]);
    m->e_int_3 = x_save[2] + (dt / REAL_C(6.0)) * (k1[2] + REAL_C(2.0) * k2[2] + REAL_C(2.0) * k3[2] + k4[2]);
    AttitudeControl_algebraics(m, t + dt);
}