
/**
 * AttitudeControl.h — Generated by Rumoca
 */
#pragma once

#include <math.h>

typedef float real_t;
#define REAL_C(x) x##f
#define SIN(x) sinf(x)
#define COS(x) cosf(x)
#define TAN(x) tanf(x)
#define ASIN(x) asinf(x)
#define ACOS(x) acosf(x)
#define ATAN2(x,y) atan2f(x,y)
#define SQRT(x) sqrtf(x)
#define FABS(x) fabsf(x)
#define POW(x,y) powf(x,y)
#define EXP(x) expf(x)
#define LOG(x) logf(x)
#define FMOD(x,y) fmodf(x,y)
#define FLOOR(x) floorf(x)
#define CEIL(x) ceilf(x)

#define ATTITUDECONTROL_N_X 3

typedef struct {
    /* States */

    real_t e_int_1;
    real_t e_int_2;
    real_t e_int_3;
    /* Algebraic */

    real_t q_err_w;
    real_t e_1;
    real_t e_2;
    real_t e_3;
    /* Inputs */

    real_t q_1;
    real_t q_2;
    real_t q_3;
    real_t q_4;
    real_t q_r_1;
    real_t q_r_2;
    real_t q_r_3;
    real_t q_r_4;
    /* Outputs */

    real_t omega_1;
    real_t omega_2;
    real_t omega_3;
    /* Parameters */

    real_t Kp_1;
    real_t Kp_2;
    real_t Kp_3;
    real_t Ki_1;
    real_t Ki_2;
    real_t Ki_3;
} AttitudeControl_t;

void AttitudeControl_init(AttitudeControl_t *m);
void AttitudeControl_step(AttitudeControl_t *m, real_t t, real_t dt);
void AttitudeControl_derivatives(const AttitudeControl_t *m, real_t t, real_t xdot[ATTITUDECONTROL_N_X]);