
/**
 * AttitudePIDQuaternion.h — Generated by Rumoca
 */
#pragma once

#include <math.h>

typedef float real_t;
#define REAL_C(x) x##f
#define SIN(x) sinf(x)
#define COS(x) cosf(x)
#define TAN(x) tanf(x)
#define ASIN(x) asinf(x)
#define ACOS(x) acosf(x)
#define ATAN2(x,y) atan2f(x,y)
#define SQRT(x) sqrtf(x)
#define FABS(x) fabsf(x)
#define POW(x,y) powf(x,y)
#define EXP(x) expf(x)
#define LOG(x) logf(x)
#define FMOD(x,y) fmodf(x,y)
#define FLOOR(x) floorf(x)
#define CEIL(x) ceilf(x)

#define ATTITUDEPIDQUATERNION_N_X 4

typedef struct {
    /* States */

    real_t integral_1;
    real_t integral_2;
    real_t integral_3;
    real_t integral_4;
    /* Algebraic */

    real_t error_dot_1;
    real_t error_dot_2;
    real_t error_dot_3;
    real_t error_dot_4;
    real_t error_1;
    real_t error_2;
    real_t error_3;
    real_t error_4;
    /* Inputs */

    real_t q_1;
    real_t q_2;
    real_t q_3;
    real_t q_4;
    real_t q_r_1;
    real_t q_r_2;
    real_t q_r_3;
    real_t q_r_4;
    /* Outputs */

    real_t u_1;
    real_t u_2;
    real_t u_3;
    real_t u_4;
    /* Parameters */

    real_t Kp_1;
    real_t Kp_2;
    real_t Kp_3;
    real_t Kp_4;
    real_t Ki_1;
    real_t Ki_2;
    real_t Ki_3;
    real_t Ki_4;
    real_t Kd_1;
    real_t Kd_2;
    real_t Kd_3;
    real_t Kd_4;
    real_t dt;
} AttitudePIDQuaternion_t;

void AttitudePIDQuaternion_init(AttitudePIDQuaternion_t *m);
void AttitudePIDQuaternion_step(AttitudePIDQuaternion_t *m, real_t t, real_t dt);
void AttitudePIDQuaternion_derivatives(const AttitudePIDQuaternion_t *m, real_t t, real_t xdot[ATTITUDEPIDQUATERNION_N_X]);