
/**
 * AttitudePIDQuaternion.c — Generated by Rumoca
 */
#include "AttitudePIDQuaternion.h"

static void AttitudePIDQuaternion_algebraics(AttitudePIDQuaternion_t *m, real_t t) {

    const real_t integral_1 = m->integral_1; (void)integral_1;
    const real_t integral_2 = m->integral_2; (void)integral_2;
    const real_t integral_3 = m->integral_3; (void)integral_3;
    const real_t integral_4 = m->integral_4; (void)integral_4;

    const real_t q_1 = m->q_1; (void)q_1;
    const real_t q_2 = m->q_2; (void)q_2;
    const real_t q_3 = m->q_3; (void)q_3;
    const real_t q_4 = m->q_4; (void)q_4;
    const real_t q_r_1 = m->q_r_1; (void)q_r_1;
    const real_t q_r_2 = m->q_r_2; (void)q_r_2;
    const real_t q_r_3 = m->q_r_3; (void)q_r_3;
    const real_t q_r_4 = m->q_r_4; (void)q_r_4;

    const real_t Kp_1 = m->Kp_1; (void)Kp_1;
    const real_t Kp_2 = m->Kp_2; (void)Kp_2;
    const real_t Kp_3 = m->Kp_3; (void)Kp_3;
    const real_t Kp_4 = m->Kp_4; (void)Kp_4;
    const real_t Ki_1 = m->Ki_1; (void)Ki_1;
    const real_t Ki_2 = m->Ki_2; (void)Ki_2;
    const real_t Ki_3 = m->Ki_3; (void)Ki_3;
    const real_t Ki_4 = m->Ki_4; (void)Ki_4;
    const real_t Kd_1 = m->Kd_1; (void)Kd_1;
    const real_t Kd_2 = m->Kd_2; (void)Kd_2;
    const real_t Kd_3 = m->Kd_3; (void)Kd_3;
    const real_t Kd_4 = m->Kd_4; (void)Kd_4;
    const real_t dt = m->dt; (void)dt;
    real_t error_dot_1 = m->error_dot_1;
    real_t error_dot_2 = m->error_dot_2;
    real_t error_dot_3 = m->error_dot_3;
    real_t error_dot_4 = m->error_dot_4;
    real_t error_1 = m->error_1;
    real_t error_2 = m->error_2;
    real_t error_3 = m->error_3;
    real_t error_4 = m->error_4;
    real_t u_1 = m->u_1;
    real_t u_2 = m->u_2;
    real_t u_3 = m->u_3;
    real_t u_4 = m->u_4;
    (void)t;
    error_dot_1 = 0.0f;
    m->error_dot_1 = error_dot_1;
    error_dot_2 = 0.0 /* WARNING: no equation found for error_dot[2] */;
    m->error_dot_2 = error_dot_2;
    error_dot_3 = 0.0 /* WARNING: no equation found for error_dot[3] */;
    m->error_dot_3 = error_dot_3;
    error_dot_4 = 0.0 /* WARNING: no equation found for error_dot[4] */;
    m->error_dot_4 = error_dot_4;
    error_1 = (q_r_1 - q_1);
    m->error_1 = error_1;
    error_2 = (q_r_2 - q_2);
    m->error_2 = error_2;
    error_3 = (q_r_3 - q_3);
    m->error_3 = error_3;
    error_4 = (q_r_4 - q_4);
    m->error_4 = error_4;
    u_1 = (((Kp_1 * error_1) + (Ki_1 * integral_1)) + (Kd_1 * error_dot_1));
    m->u_1 = u_1;
    u_2 = (((Kp_2 * error_2) + (Ki_2 * integral_2)) + (Kd_2 * error_dot_2));
    m->u_2 = u_2;
    u_3 = (((Kp_3 * error_3) + (Ki_3 * integral_3)) + (Kd_3 * error_dot_3));
    m->u_3 = u_3;
    u_4 = (((Kp_4 * error_4) + (Ki_4 * integral_4)) + (Kd_4 * error_dot_4));
    m->u_4 = u_4;
}

void AttitudePIDQuaternion_derivatives(const AttitudePIDQuaternion_t *m, real_t t, real_t xdot[ATTITUDEPIDQUATERNION_N_X]) {

    const real_t integral_1 = m->integral_1; (void)integral_1;
    const real_t integral_2 = m->integral_2; (void)integral_2;
    const real_t integral_3 = m->integral_3; (void)integral_3;
    const real_t integral_4 = m->integral_4; (void)integral_4;

    const real_t error_dot_1 = m->error_dot_1; (void)error_dot_1;
    const real_t error_dot_2 = m->error_dot_2; (void)error_dot_2;
    const real_t error_dot_3 = m->error_dot_3; (void)error_dot_3;
    const real_t error_dot_4 = m->error_dot_4; (void)error_dot_4;
    const real_t error_1 = m->error_1; (void)error_1;
    const real_t error_2 = m->error_2; (void)error_2;
    const real_t error_3 = m->error_3; (void)error_3;
    const real_t error_4 = m->error_4; (void)error_4;

    const real_t q_1 = m->q_1; (void)q_1;
    const real_t q_2 = m->q_2; (void)q_2;
    const real_t q_3 = m->q_3; (void)q_3;
    const real_t q_4 = m->q_4; (void)q_4;
    const real_t q_r_1 = m->q_r_1; (void)q_r_1;
    const real_t q_r_2 = m->q_r_2; (void)q_r_2;
    const real_t q_r_3 = m->q_r_3; (void)q_r_3;
    const real_t q_r_4 = m->q_r_4; (void)q_r_4;

    const real_t Kp_1 = m->Kp_1; (void)Kp_1;
    const real_t Kp_2 = m->Kp_2; (void)Kp_2;
    const real_t Kp_3 = m->Kp_3; (void)Kp_3;
    const real_t Kp_4 = m->Kp_4; (void)Kp_4;
    const real_t Ki_1 = m->Ki_1; (void)Ki_1;
    const real_t Ki_2 = m->Ki_2; (void)Ki_2;
    const real_t Ki_3 = m->Ki_3; (void)Ki_3;
    const real_t Ki_4 = m->Ki_4; (void)Ki_4;
    const real_t Kd_1 = m->Kd_1; (void)Kd_1;
    const real_t Kd_2 = m->Kd_2; (void)Kd_2;
    const real_t Kd_3 = m->Kd_3; (void)Kd_3;
    const real_t Kd_4 = m->Kd_4; (void)Kd_4;
    const real_t dt = m->dt; (void)dt;

    const real_t u_1 = m->u_1; (void)u_1;
    const real_t u_2 = m->u_2; (void)u_2;
    const real_t u_3 = m->u_3; (void)u_3;
    const real_t u_4 = m->u_4; (void)u_4;
    (void)t;
    xdot[0] = error_1;
    xdot[1] = error_2;
    xdot[2] = error_3;
    xdot[3] = error_4;
}

void AttitudePIDQuaternion_init(AttitudePIDQuaternion_t *m) {
    real_t Kp_1 = REAL_C(0.0);
    real_t Kp_2 = REAL_C(0.0);
    real_t Kp_3 = REAL_C(0.0);
    real_t Kp_4 = REAL_C(0.0);
    real_t Ki_1 = REAL_C(0.0);
    real_t Ki_2 = REAL_C(0.0);
    real_t Ki_3 = REAL_C(0.0);
    real_t Ki_4 = REAL_C(0.0);
    real_t Kd_1 = REAL_C(0.0);
    real_t Kd_2 = REAL_C(0.0);
    real_t Kd_3 = REAL_C(0.0);
    real_t Kd_4 = REAL_C(0.0);
    real_t dt = REAL_C(0.0);
    Kp_1 = 1.0f;
    m->Kp_1 = Kp_1;
    Kp_2 = 1.0f;
    m->Kp_2 = Kp_2;
    Kp_3 = 1.0f;
    m->Kp_3 = Kp_3;
    Kp_4 = 1.0f;
    m->Kp_4 = Kp_4;
    Ki_1 = 0.0f;
    m->Ki_1 = Ki_1;
    Ki_2 = 0.0f;
    m->Ki_2 = Ki_2;
    Ki_3 = 0.0f;
    m->Ki_3 = Ki_3;
    Ki_4 = 0.0f;
    m->Ki_4 = Ki_4;
    Kd_1 = 0.0f;
    m->Kd_1 = Kd_1;
    Kd_2 = 0.0f;
    m->Kd_2 = Kd_2;
    Kd_3 = 0.0f;
    m->Kd_3 = Kd_3;
    Kd_4 = 0.0f;
    m->Kd_4 = Kd_4;
    dt = 0.01f;
    m->dt = dt;
    m->integral_1 = 0.0f;
    m->integral_2 = 0.0f;
    m->integral_3 = 0.0f;
    m->integral_4 = 0.0f;
    m->q_1 = 0.0f;
    m->q_2 = 0.0f;
    m->q_3 = 0.0f;
    m->q_4 = 0.0f;
    m->q_r_1 = 0.0f;
    m->q_r_2 = 0.0f;
    m->q_r_3 = 0.0f;
    m->q_r_4 = 0.0f;
    AttitudePIDQuaternion_algebraics(m, REAL_C(0.0));
}

void AttitudePIDQuaternion_step(AttitudePIDQuaternion_t *m, real_t t, real_t dt) {
    real_t k1[ATTITUDEPIDQUATERNION_N_X], k2[ATTITUDEPIDQUATERNION_N_X];
    real_t k3[ATTITUDEPIDQUATERNION_N_X], k4[ATTITUDEPIDQUATERNION_N_X];
    real_t x_save[ATTITUDEPIDQUATERNION_N_X];
    x_save[0] = m->integral_1;
    x_save[1] = m->integral_2;
    x_save[2] = m->integral_3;
    x_save[3] = m->integral_4;

    AttitudePIDQuaternion_algebraics(m, t);
    AttitudePIDQuaternion_derivatives(m, t, k1);

    m->integral_1 = x_save[0] + REAL_C(0.5) * dt * k1[0];
    m->integral_2 = x_save[1] + REAL_C(0.5) * dt * k1[1];
    m->integral_3 = x_save[2] + REAL_C(0.5) * dt * k1[2];
    m->integral_4 = x_save[3] + REAL_C(0.5) * dt * k1[3];
    AttitudePIDQuaternion_algebraics(m, t + REAL_C(0.5) * dt);
    AttitudePIDQuaternion_derivatives(m, t + REAL_C(0.5) * dt, k2);

    m->integral_1 = x_save[0] + REAL_C(0.5) * dt * k2[0];
    m->integral_2 = x_save[1] + REAL_C(0.5) * dt * k2[1];
    m->integral_3 = x_save[2] + REAL_C(0.5) * dt * k2[2];
    m->integral_4 = x_save[3] + REAL_C(0.5) * dt * k2[3];
    AttitudePIDQuaternion_algebraics(m, t + REAL_C(0.5) * dt);
    AttitudePIDQuaternion_derivatives(m, t + REAL_C(0.5) * dt, k3);

    m->integral_1 = x_save[0] + REAL_C(1.0) * dt * k3[0];
    m->integral_2 = x_save[1] + REAL_C(1.0) * dt * k3[1];
    m->integral_3 = x_save[2] + REAL_C(1.0) * dt * k3[2];
    m->integral_4 = x_save[3] + REAL_C(1.0) * dt * k3[3];
    AttitudePIDQuaternion_algebraics(m, t + dt);
    AttitudePIDQuaternion_derivatives(m, t + dt, k4);
    m->integral_1 = x_save[0] + (dt / REAL_C(6.0)) * (k1[0] + REAL_C(2.0) * k2[0] + REAL_C(2.0) * k3[0] + k4[0]);
    m->integral_2 = x_save[1] + (dt / REAL_C(6.0)) * (k1[1] + REAL_C(2.0) * k2[1] + REAL_C(2.0) * k3[1] + k4[1]);
    m->integral_3 = x_save[2] + (dt / REAL_C(6.0)) * (k1[2] + REAL_C(2.0) * k2[2] + REAL_C(2.0) * k3[2] + k4[2]);
    m->integral_4 = x_save[3] + (dt / REAL_C(6.0)) * (k1[3] + REAL_C(2.0) * k2[3] + REAL_C(2.0) * k3[3] + k4[3]);
    AttitudePIDQuaternion_algebraics(m, t + dt);
}