[package]
name = "rumoca-phase-dae"
description = "ToDae phase for the Rumoca Modelica compiler"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[features]
default = []

[dependencies]
rumoca-core = { workspace = true }
rumoca-eval-flat = { workspace = true }
rumoca-ir-flat = { workspace = true }
rumoca-ir-dae = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
miette = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

[lints]
workspace = true
