[package]
name = "rumoca"
authors = ["James Goppert"]
description = "A Modelica compiler with focus on Casadi, Sympy, JAX, and Collimator generation"
version = "0.1.0"
edition = "2021"

[build-dependencies]
lalrpop = "0.22.0"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
lalrpop-util = "0.22.0"
logos = "0.14.2"
serde = { version = "1.0.214", features = ["derive", "serde_derive"] }
serde_json = "1.0.132"
tera = "1.20.0"
