[package]
name = "rumoca"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
env_logger = "0.11"
indexmap = "2.7.1"
parol = "2.2.0"
parol_runtime = { version = "1.0.1", features = ["auto_generation"] }
thiserror = "1.0"

[build-dependencies]
parol = "1.0.3"
parol_runtime = { version = "1.0.1", features = ["auto_generation"] }

# For faster builds.
[profile.dev.build-override]
opt-level = 3
[profile.release.build-override]
opt-level = 3
