-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [try_branch]: function definitions
import Aeneas
import Ti4.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace try_branch

/-- [try_branch::parse]:
    Source: 'try_branch.rs', lines 1:0-1:82
    Visibility: public -/
def parse (x : Std.U32) : Result (core.result.Result Std.U32 Std.U8) := do
  if x > 9#u32
  then _root_.Aeneas.Std.Result.ok (core.result.Result.Err 1#u8)
  else
    let i ← x + 1#u32
    _root_.Aeneas.Std.Result.ok (core.result.Result.Ok i)

/-- [try_branch::twice]:
    Source: 'try_branch.rs', lines 2:0-2:87
    Visibility: public -/
def twice (x : Std.U32) : Result (core.result.Result Std.U32 Std.U8) := do
  let r ← parse x
  let cf ← core.result.Result.Insts.CoreOpsTry.branch r
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let r1 ← parse val
    let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
    match cf1 with
    | core.ops.control_flow.ControlFlow.Continue val1 =>
      _root_.Aeneas.Std.Result.ok (core.result.Result.Ok val1)
    | core.ops.control_flow.ControlFlow.Break residual =>
      core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
        Std.U32 (core.convert.FromSame Std.U8) residual
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.result.Result.Insts.CoreOpsTryTraitFromResidualResultInfallible.from_residual
      Std.U32 (core.convert.FromSame Std.U8) residual

end try_branch
