//! `cargo xtask coverage run`: the instrumented workspace test run and its
//! summary report, written beside a runbook of the exact commands.

use crate::{
    CoverageRunArgs, ensure_cargo_llvm_cov_available, ensure_llvm_tools_preview_available,
    repo_root, run_cargo_with_args, test_cmd,
};
use anyhow::{Context, Result};
use std::fs;

pub(crate) fn run(args: CoverageRunArgs) -> Result<()> {
    let root = repo_root();
    ensure_cargo_llvm_cov_available(&root)?;
    ensure_llvm_tools_preview_available(&root)?;

    let output_dir = root.join("target/llvm-cov");
    fs::create_dir_all(&output_dir)
        .with_context(|| format!("failed to create {}", output_dir.display()))?;

    let mut runbook = String::new();
    runbook.push_str("# rumoca coverage runbook\n");
    runbook.push_str("# generated by cargo xtask coverage run\n\n");
    let package_args = package_args(&args.packages);
    let mut full_args = vec!["llvm-cov".to_string()];
    if args.packages.is_empty() {
        full_args.push("--workspace".to_string());
    }
    full_args.extend([
        "--tests".to_string(),
        "--json".to_string(),
        "--output-path".to_string(),
        "target/llvm-cov/workspace-full.json".to_string(),
    ]);
    full_args.extend(
        test_cmd::COVERAGE_TEST_FEATURES
            .iter()
            .map(ToString::to_string),
    );
    full_args.extend(package_args.clone());
    if args.no_clean {
        full_args.push("--no-clean".to_string());
    }
    let mut summary_args = vec![
        "llvm-cov".to_string(),
        "report".to_string(),
        "--json".to_string(),
        "--summary-only".to_string(),
        "--output-path".to_string(),
        "target/llvm-cov/workspace-summary.json".to_string(),
    ];
    summary_args.extend(package_args);

    println!("coverage: workspace (tests)");
    runbook.push_str("cargo ");
    runbook.push_str(&full_args.join(" "));
    runbook.push('\n');
    run_cargo_with_args(&root, &full_args)?;

    println!("coverage: workspace (summary)");
    runbook.push_str("cargo ");
    runbook.push_str(&summary_args.join(" "));
    runbook.push('\n');
    run_cargo_with_args(&root, &summary_args)?;

    let runbook_path = output_dir.join("coverage-commands.txt");
    fs::write(&runbook_path, runbook)
        .with_context(|| format!("failed to write {}", runbook_path.display()))?;

    println!("Coverage artifacts generated in {}", output_dir.display());
    println!("Runbook: {}", runbook_path.display());
    Ok(())
}

/// `--package` arguments for the selected workspace packages.
fn package_args(packages: &[String]) -> Vec<String> {
    packages
        .iter()
        .flat_map(|package| ["--package".to_string(), package.clone()])
        .collect()
}
