-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [f64_binding]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace f64_binding

/-- [f64_binding::Literal]
    Source: '/home/jgoppert/git/rumoca/infra/verification/aeneas/candidates/f64-type-binding/f64-binding.rs', lines 9:0-12:1
    Visibility: public -/
@[discriminant isize]
inductive Literal where
| Real : F64 → Literal
| Integer : Std.I64 → Literal

/-- [f64_binding::Entry]
    Source: '/home/jgoppert/git/rumoca/infra/verification/aeneas/candidates/f64-type-binding/f64-binding.rs', lines 14:0-17:1
    Visibility: public -/
structure Entry where
  expression : Std.U32
  value : F64

/-- [f64_binding::real]:
    Source: '/home/jgoppert/git/rumoca/infra/verification/aeneas/candidates/f64-type-binding/f64-binding.rs', lines 19:0-21:1
    Visibility: public -/
def real (value : F64) : Result Literal := do
  _root_.Aeneas.Std.Result.ok (Literal.Real value)

/-- [f64_binding::entry_value]:
    Source: '/home/jgoppert/git/rumoca/infra/verification/aeneas/candidates/f64-type-binding/f64-binding.rs', lines 23:0-25:1
    Visibility: public -/
def entry_value (entry : Entry) : Result F64 := do
  _root_.Aeneas.Std.Result.ok entry.value

end f64_binding
