
"""
Generated by Rumoca.

This template renders the current DAE context into a SymPy-friendly symbolic
model. It keeps Rumoca's continuous equations in residual form and can solve
for explicit state derivatives and algebraics when possible.
"""

import sympy as sp


def der(symbol):
    if isinstance(symbol, sp.Indexed):
        return sp.IndexedBase(f"{symbol.base}_dot")[symbol.indices]
    if isinstance(symbol, sp.IndexedBase):
        return sp.IndexedBase(f"{symbol}_dot")
    return sp.Symbol(f"{symbol}_dot")


def pre(symbol):
    if isinstance(symbol, sp.Indexed):
        return sp.IndexedBase(f"pre_{symbol.base}")[symbol.indices]
    if isinstance(symbol, sp.IndexedBase):
        return sp.IndexedBase(f"pre_{symbol}")
    return sp.Symbol(f"pre_{symbol}")


def if_else(condition, then_expr, else_expr):
    return sp.Piecewise((then_expr, condition), (else_expr, True))


def _vector(entries):
    return (
        sp.Matrix([symbol for _, symbol, _ in entries]),
        {name: start for name, _, start in entries},
        {name: index for index, (name, _, _) in enumerate(entries)},
    )


def _column(entries):
    return sp.Matrix(entries) if entries else sp.Matrix([])


def zeros(*dims):
    if len(dims) == 1:
        return sp.Matrix.zeros(int(dims[0]), 1)
    return sp.Matrix.zeros(*(int(dim) for dim in dims))


def ones(*dims):
    if len(dims) == 1:
        return sp.Matrix.ones(int(dims[0]), 1)
    return sp.Matrix.ones(*(int(dim) for dim in dims))


def sum(values):
    if isinstance(values, sp.MatrixBase):
        return sp.Add(*list(values))
    if isinstance(values, (list, tuple)):
        return sp.Add(*values)
    return values


abs = sp.Abs
min = sp.Min
max = sp.Max
sign = sp.sign
sqrt = sp.sqrt
sin = sp.sin
cos = sp.cos
tan = sp.tan
asin = sp.asin
acos = sp.acos
atan = sp.atan
atan2 = sp.atan2
sinh = sp.sinh
cosh = sp.cosh
tanh = sp.tanh
exp = sp.exp
log = sp.log
log10 = lambda value: sp.log(value, 10)
floor = sp.floor
ceil = sp.ceiling
transpose = lambda value: sp.Matrix(value).T
identity = sp.eye
cross = lambda lhs, rhs: sp.Matrix(lhs).cross(sp.Matrix(rhs))
div = lambda lhs, rhs: sp.floor(lhs / rhs)
mod = sp.Mod
rem = sp.Mod


class Model:
    """Flattened symbolic DAE model."""

    def __init__(self):
        self.time = sp.Symbol("time")
        time = self.time

        # States, algebraics, inputs, outputs, parameters, constants, discretes.


        x = sp.Symbol("x")


        z = sp.Symbol("z")


        theta = sp.Symbol("theta")


        x_dot = sp.Symbol("x_dot")


        z_dot = sp.Symbol("z_dot")


        theta_dot = sp.Symbol("theta_dot")


        self.x, self.x_start, self.x_index = _vector([
            ("x", x, 0.0),
            ("z", z, 0.0),
            ("theta", theta, 0.0),
            ("x_dot", x_dot, 0.0),
            ("z_dot", z_dot, 0.0),
            ("theta_dot", theta_dot, 0.0)
        ])


        self.y, self.y_start, self.y_index = _vector([])



        T = sp.Symbol("T")


        M = sp.Symbol("M")


        self.u, self.u_start, self.u_index = _vector([
            ("T", T, 0.0),
            ("M", M, 0.0)
        ])


        self.w, self.w_start, self.w_index = _vector([])



        m = sp.Symbol("m")


        J = sp.Symbol("J")


        g = sp.Symbol("g")


        self.p, self.p_start, self.p_index = _vector([
            ("m", m, 2.496),
            ("J", J, 0.0344),
            ("g", g, 9.80665)
        ])


        self.constants, self.constants_start, self.constants_index = _vector([])


        self.z, self.z_start, self.z_index = _vector([])


        self.m, self.m_start, self.m_index = _vector([])

        self.f_x = _column([
            (der(x) - x_dot),
            (der(z) - z_dot),
            (der(theta) - theta_dot),
            ((m * der(x_dot)) - (-(T * sin(theta)))),
            ((m * der(z_dot)) - ((T * cos(theta)) - (m * g))),
            ((J * der(theta_dot)) - M)
        ])

        self.initial_residuals = _column([])

        self.relations = _column([])

        self.explicit_targets = [

            der(x),


            der(z),


            der(theta),


            (m * der(x_dot)),


            (m * der(z_dot)),


            (J * der(theta_dot)),

        ]
        self.explicit_solution = None
        self.explicit_rhs = sp.Matrix([])

    def solve_explicit(self):
        """Best-effort symbolic solve for explicit derivatives and algebraics."""
        if len(self.f_x) == 0 or len(self.explicit_targets) == 0:
            self.explicit_solution = {}
            self.explicit_rhs = sp.Matrix([])
            return self.explicit_solution

        solutions = sp.solve(
            list(self.f_x),
            self.explicit_targets,
            dict=True,
            simplify=False,
        )
        self.explicit_solution = solutions[0] if solutions else {}
        self.explicit_rhs = sp.Matrix(
            [
                self.explicit_solution.get(symbol, symbol)
                for symbol in self.explicit_targets
            ]
        )
        return self.explicit_solution

    def summary(self):
        return {
            "states": [str(symbol) for symbol in self.x],
            "algebraics": [str(symbol) for symbol in self.y],
            "inputs": [str(symbol) for symbol in self.u],
            "parameters": [str(symbol) for symbol in self.p],
            "continuous_residual_count": len(self.f_x),
            "initial_residual_count": len(self.initial_residuals),
            "explicit_target_count": len(self.explicit_targets),
        }


if __name__ == "__main__":
    model = Model()
    print(model.summary())
    if len(model.f_x) > 0 and len(model.explicit_targets) > 0:
        print(model.solve_explicit())