
/**
 * RateControlDiscrete.h — Generated by Rumoca
 */
#pragma once

#include <math.h>

typedef float real_t;
#define REAL_C(x) x##f
#define SIN(x) sinf(x)
#define COS(x) cosf(x)
#define TAN(x) tanf(x)
#define ASIN(x) asinf(x)
#define ACOS(x) acosf(x)
#define ATAN2(x,y) atan2f(x,y)
#define SQRT(x) sqrtf(x)
#define FABS(x) fabsf(x)
#define POW(x,y) powf(x,y)
#define EXP(x) expf(x)
#define LOG(x) logf(x)
#define FMOD(x,y) fmodf(x,y)
#define FLOOR(x) floorf(x)
#define CEIL(x) ceilf(x)

#define RATECONTROLDISCRETE_N_X 1

typedef struct {
    /* States */

    real_t _rumoca_dummy_state;

    real_t pre__rumoca_dummy_state;

    /* Algebraic */

    real_t pid_r_setpoint;
    real_t pid_r_measurement;
    real_t pid_p_setpoint;
    real_t pid_p_measurement;
    real_t pid_y_setpoint;
    real_t pid_y_measurement;

    /* Inputs */

    real_t gyro[3];
    real_t rate_sp[3];

    /* Parameters */

    real_t A_d_rp[4];
    real_t B_d_rp[2];
    real_t C_d_rp[2];
    real_t D_d_rp;
    real_t A_d_y[1];
    real_t B_d_y[1];
    real_t C_d_y[1];
    real_t D_d_y;
    real_t pid_r_Ts;
    real_t pid_r_nx;
    real_t pid_p_Ts;
    real_t pid_p_nx;
    real_t pid_y_Ts;
    real_t pid_y_nx;
    real_t pid_r_D_d;
    real_t pid_p_D_d;
    real_t pid_y_A_d[1];
    real_t pid_y_B_d[1];
    real_t pid_y_C_d[1];
    real_t pid_y_D_d;
    real_t pid_p_A_d[4];
    real_t pid_r_A_d[4];
    real_t pid_r_B_d[2];
    real_t pid_p_B_d[2];
    real_t pid_r_C_d[2];
    real_t pid_p_C_d[2];

    /* Discrete */

    real_t pid_r_x[2];
    real_t pid_r_e;
    real_t pid_r_u_k;
    real_t pid_p_x[2];
    real_t pid_p_e;
    real_t pid_p_u_k;
    real_t pid_y_x[1];
    real_t pid_y_e;
    real_t pid_y_u_k;

    real_t pre_pid_r_x[2];
    real_t pre_pid_r_e;
    real_t pre_pid_r_u_k;
    real_t pre_pid_p_x[2];
    real_t pre_pid_p_e;
    real_t pre_pid_p_u_k;
    real_t pre_pid_y_x[1];
    real_t pre_pid_y_e;
    real_t pre_pid_y_u_k;
} RateControlDiscrete_t;

void RateControlDiscrete_init(RateControlDiscrete_t *m);
void RateControlDiscrete_step(RateControlDiscrete_t *m, real_t t, real_t dt);