-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [f32_width]: external types.
-- This is a template file: rename it to "TypesExternal.lean" and fill the holes.
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/-- [f32]: floating-point storage primitive referenced by this crate.
    The translator names it and does not define it; the model file must supply
    `Aeneas.Std.F32`. -/
axiom Aeneas.Std.F32 : Type

