//! Coverage artifact generation, analysis, and regression policy.

mod coverage_analysis;
mod coverage_gate;

use anyhow::{Context, Result, bail, ensure};
use clap::{Args, Parser, Subcommand};
use coverage_analysis::{
    CallsiteIndex, build_workspace_callsite_index, count_callsites_same_file,
    is_opaque_symbol_name, owner_decision_for_label, render_coverage_trim_report,
};
use coverage_gate::CoverageGateArgs;
use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Parser)]
#[command(name = "rumoca-coverage", version)]
#[command(about = "Generate and evaluate Rumoca's LLVM coverage evidence")]
struct Cli {
    #[command(subcommand)]
    command: CoverageCommand,
}

#[derive(Debug, Subcommand)]
enum CoverageCommand {
    /// Generate standardized unified workspace coverage artifacts.
    Run(CoverageRunArgs),
    /// Generate per-package inventory and trim candidates.
    Report(CoverageReportArgs),
    /// Enforce coverage regression thresholds against the committed baseline.
    Gate(CoverageGateArgs),
}

#[derive(Debug, Args)]
struct CoverageRunArgs {
    /// Reuse llvm-cov artifacts between runs.
    #[arg(long)]
    no_clean: bool,
    /// Restrict coverage to selected workspace packages.
    #[arg(long = "package", short = 'p')]
    packages: Vec<String>,
}

#[derive(Debug, Args)]
struct CoverageReportArgs {
    /// Workspace packages to report; all packages when omitted.
    #[arg(long = "package", short = 'p')]
    packages: Vec<String>,
    /// Number of lowest-coverage files per package.
    #[arg(long, default_value_t = 10)]
    top_files: usize,
    /// Near-zero callsite threshold for dead-helper detection.
    #[arg(long, default_value_t = 1)]
    near_zero_callsites: usize,
}

fn main() -> Result<()> {
    match Cli::parse().command {
        CoverageCommand::Run(args) => cmd_coverage_run(args),
        CoverageCommand::Report(args) => cmd_coverage_report(args),
        CoverageCommand::Gate(args) => cmd_coverage_gate(args),
    }
}

fn repo_root() -> PathBuf {
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    cwd.ancestors()
        .find(|dir| {
            dir.join("Cargo.toml").is_file()
                && fs::read_to_string(dir.join("Cargo.toml"))
                    .is_ok_and(|text| text.contains("[workspace]"))
        })
        .map(Path::to_path_buf)
        .unwrap_or(cwd)
}

fn exe_name(base: &str) -> String {
    if cfg!(windows) {
        format!("{base}.exe")
    } else {
        base.to_string()
    }
}

fn run_status(mut command: Command) -> Result<()> {
    let rendered = format!("{command:?}");
    let status = command
        .status()
        .with_context(|| format!("failed to run {rendered}"))?;
    ensure!(status.success(), "command failed ({status}): {rendered}");
    Ok(())
}

fn run_capture(mut command: Command) -> Result<String> {
    let rendered = format!("{command:?}");
    let output = command
        .output()
        .with_context(|| format!("failed to run {rendered}"))?;
    ensure!(
        output.status.success(),
        "command failed ({}): {rendered}\n{}",
        output.status,
        String::from_utf8_lossy(&output.stderr)
    );
    Ok(String::from_utf8_lossy(&output.stdout).into_owned())
}

fn cmd_coverage_run(args: CoverageRunArgs) -> Result<()> {
    let root = repo_root();
    ensure_cargo_llvm_cov_available(&root)?;
    ensure_llvm_tools_preview_available(&root)?;

    let output_dir = root.join("target/llvm-cov");
    fs::create_dir_all(&output_dir)
        .with_context(|| format!("failed to create {}", output_dir.display()))?;

    let mut runbook = String::new();
    runbook.push_str("# rumoca coverage runbook\n");
    runbook.push_str("# generated by cargo make coverage-run\n\n");
    let package_args = coverage_package_args(&args.packages);
    let mut full_args = vec!["llvm-cov".to_string()];
    if args.packages.is_empty() {
        full_args.push("--workspace".to_string());
    }
    full_args.extend([
        "--tests".to_string(),
        "--json".to_string(),
        "--output-path".to_string(),
        "target/llvm-cov/workspace-full.json".to_string(),
    ]);
    full_args.extend(package_args.clone());
    if args.no_clean {
        full_args.push("--no-clean".to_string());
    }
    let mut summary_args = vec![
        "llvm-cov".to_string(),
        "report".to_string(),
        "--json".to_string(),
        "--summary-only".to_string(),
        "--output-path".to_string(),
        "target/llvm-cov/workspace-summary.json".to_string(),
    ];
    summary_args.extend(package_args.clone());

    println!("coverage: workspace (tests)");
    runbook.push_str("cargo ");
    runbook.push_str(&full_args.join(" "));
    runbook.push('\n');
    run_cargo_with_args(&root, &full_args)?;

    println!("coverage: workspace (summary)");
    runbook.push_str("cargo ");
    runbook.push_str(&summary_args.join(" "));
    runbook.push('\n');
    run_cargo_with_args(&root, &summary_args)?;

    let runbook_path = output_dir.join("coverage-commands.txt");
    fs::write(&runbook_path, runbook)
        .with_context(|| format!("failed to write {}", runbook_path.display()))?;

    println!("Coverage artifacts generated in {}", output_dir.display());
    println!("Runbook: {}", runbook_path.display());
    Ok(())
}

fn coverage_package_args(packages: &[String]) -> Vec<String> {
    packages
        .iter()
        .flat_map(|package| ["--package".to_string(), package.clone()])
        .collect()
}

fn cmd_coverage_gate(args: CoverageGateArgs) -> Result<()> {
    coverage_gate::run(&repo_root(), &args)
}

#[derive(Debug, Clone)]
struct CoverageFileSummary {
    file: String,
    line_percent: f64,
    line_count: u64,
    line_covered: u64,
}

#[derive(Debug, Clone)]
struct CoverageCandidate {
    package: String,
    file: String,
    line: usize,
    demangled_function: String,
    symbol: Option<String>,
    visibility: String,
    has_cfg_attr: bool,
    callsites_same_file: Option<usize>,
    callsites_workspace: Option<usize>,
    callsites_other_crates: Option<usize>,
    triage_label: String,
    owner_decision: String,
}

#[derive(Debug, Clone)]
struct PackageCoverageInventory {
    package: String,
    lowest_files: Vec<CoverageFileSummary>,
    zero_count_functions_total: usize,
    candidates: Vec<CoverageCandidate>,
    triage_counts: BTreeMap<String, usize>,
}

#[derive(Debug, Clone)]
struct WorkspacePackageInfo {
    name: String,
    root_prefix: String,
}

type ZeroCoverageTotalsByPackage = HashMap<String, usize>;
type CandidateListsByPackage = HashMap<String, Vec<CoverageCandidate>>;

fn cmd_coverage_report(args: CoverageReportArgs) -> Result<()> {
    let root = repo_root();
    let output_dir = root.join("target/llvm-cov");
    ensure!(
        output_dir.is_dir(),
        "coverage output directory not found: {}. Run `cargo make coverage-run` first.",
        output_dir.display()
    );
    let summary_path = output_dir.join("workspace-summary.json");
    let full_path = output_dir.join("workspace-full.json");
    ensure!(
        summary_path.is_file() && full_path.is_file(),
        "missing workspace coverage artifacts (expected {} and {}). Run `cargo make coverage-run` first.",
        summary_path.display(),
        full_path.display()
    );

    let package_infos = workspace_package_infos(&root)?;
    let selected_packages = if args.packages.is_empty() {
        package_infos.clone()
    } else {
        let requested = args.packages.into_iter().collect::<BTreeSet<_>>();
        let package_map = package_infos
            .iter()
            .map(|info| (info.name.clone(), info.clone()))
            .collect::<BTreeMap<_, _>>();
        let mut selected = Vec::new();
        for package in requested {
            let Some(info) = package_map.get(&package) else {
                bail!("unknown workspace package in --package filter: {package}");
            };
            selected.push(info.clone());
        }
        selected
    };
    ensure!(
        !selected_packages.is_empty(),
        "no workspace packages available for coverage report"
    );
    let summary_json = read_json_file(&summary_path)?;
    let full_json = read_json_file(&full_path)?;

    let (inventories, all_candidates) = collect_coverage_inventories(
        &root,
        &selected_packages,
        &summary_json,
        &full_json,
        args.top_files,
        args.near_zero_callsites,
    )?;
    ensure!(
        all_candidates
            .iter()
            .all(|candidate| !candidate.owner_decision.is_empty()),
        "coverage report candidate generation produced empty owner decisions"
    );
    ensure!(
        all_candidates
            .iter()
            .all(|candidate| candidate.owner_decision != "untriaged"),
        "coverage report candidate generation produced untriaged owner decisions"
    );
    let (report_path, candidates_path) =
        write_coverage_report_artifacts(&output_dir, &inventories, &all_candidates)?;

    println!("Coverage inventory report: {}", report_path.display());
    println!("Trim candidates JSON: {}", candidates_path.display());
    Ok(())
}

fn collect_coverage_inventories(
    root: &Path,
    package_infos: &[WorkspacePackageInfo],
    summary_json: &serde_json::Value,
    full_json: &serde_json::Value,
    top_files: usize,
    near_zero_callsites: usize,
) -> Result<(Vec<PackageCoverageInventory>, Vec<CoverageCandidate>)> {
    let mut source_cache = HashMap::new();
    let callsite_index = build_workspace_callsite_index(root, package_infos)?;
    let mut inventories = Vec::new();
    let mut all_candidates = Vec::new();
    let mut files_by_package = summary_file_entries_by_package(root, package_infos, summary_json)?;
    let (zero_totals_by_package, mut candidates_by_package) = zero_count_candidates_by_package(
        root,
        package_infos,
        full_json,
        near_zero_callsites,
        &mut source_cache,
        &callsite_index,
    )?;

    for package in package_infos {
        let mut lowest_files = files_by_package.remove(&package.name).unwrap_or_default();
        lowest_files.sort_by(|a, b| {
            a.line_percent
                .total_cmp(&b.line_percent)
                .then(a.file.cmp(&b.file))
        });
        lowest_files.truncate(top_files);

        let mut candidates = candidates_by_package
            .remove(&package.name)
            .unwrap_or_default();
        candidates.sort_by(|a, b| {
            a.file
                .cmp(&b.file)
                .then(a.line.cmp(&b.line))
                .then(a.demangled_function.cmp(&b.demangled_function))
        });
        candidates.dedup_by(|a, b| {
            a.file == b.file
                && a.line == b.line
                && a.symbol == b.symbol
                && a.triage_label == b.triage_label
        });
        all_candidates.extend(candidates.clone());

        let mut triage_counts = BTreeMap::new();
        for candidate in &candidates {
            *triage_counts
                .entry(candidate.triage_label.clone())
                .or_insert(0) += 1;
        }

        inventories.push(PackageCoverageInventory {
            package: package.name.clone(),
            lowest_files,
            zero_count_functions_total: zero_totals_by_package
                .get(&package.name)
                .copied()
                .unwrap_or(0),
            candidates,
            triage_counts,
        });
    }

    inventories.sort_by(|a, b| a.package.cmp(&b.package));
    all_candidates.sort_by(|a, b| {
        a.package
            .cmp(&b.package)
            .then(a.file.cmp(&b.file))
            .then(a.line.cmp(&b.line))
            .then(a.demangled_function.cmp(&b.demangled_function))
    });
    Ok((inventories, all_candidates))
}

fn write_coverage_report_artifacts(
    output_dir: &Path,
    inventories: &[PackageCoverageInventory],
    all_candidates: &[CoverageCandidate],
) -> Result<(PathBuf, PathBuf)> {
    let report_md = render_coverage_trim_report(inventories);
    let report_path = output_dir.join("coverage-trim-report.md");
    fs::write(&report_path, report_md)
        .with_context(|| format!("failed to write {}", report_path.display()))?;

    let candidates_json = build_trim_candidates_json(inventories, all_candidates);
    let candidates_path = output_dir.join("trim-candidates.json");
    let candidates_serialized =
        serde_json::to_string_pretty(&candidates_json).context("failed to serialize candidates")?;
    fs::write(&candidates_path, candidates_serialized)
        .with_context(|| format!("failed to write {}", candidates_path.display()))?;
    Ok((report_path, candidates_path))
}

fn build_trim_candidates_json(
    inventories: &[PackageCoverageInventory],
    all_candidates: &[CoverageCandidate],
) -> serde_json::Value {
    serde_json::json!({
        "generated_by": "cargo make coverage-report",
        "generated_at_unix_secs": unix_timestamp_seconds(),
        "report_version": 1,
        "packages": inventories.iter().map(|inventory| {
            serde_json::json!({
                "package": inventory.package,
                "zero_count_functions_total": inventory.zero_count_functions_total,
                "lowest_coverage_files": inventory.lowest_files.iter().map(|file| {
                    serde_json::json!({
                        "file": file.file,
                        "line_percent": file.line_percent,
                        "line_count": file.line_count,
                        "line_covered": file.line_covered,
                    })
                }).collect::<Vec<_>>(),
                "triage_counts": inventory.triage_counts,
            })
        }).collect::<Vec<_>>(),
        "candidates": all_candidates.iter().map(|candidate| {
            serde_json::json!({
                "package": candidate.package,
                "file": candidate.file,
                "line": candidate.line,
                "demangled_function": candidate.demangled_function,
                "symbol": candidate.symbol,
                "visibility": candidate.visibility,
                "has_cfg_attr": candidate.has_cfg_attr,
                "callsites_same_file": candidate.callsites_same_file,
                "callsites_workspace": candidate.callsites_workspace,
                "callsites_other_crates": candidate.callsites_other_crates,
                "triage_label": candidate.triage_label,
                "owner_decision": candidate.owner_decision,
            })
        }).collect::<Vec<_>>(),
    })
}

fn read_json_file(path: &Path) -> Result<serde_json::Value> {
    let raw =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;
    serde_json::from_str(&raw).with_context(|| format!("failed to parse JSON {}", path.display()))
}

fn summary_file_entries_by_package(
    root: &Path,
    package_infos: &[WorkspacePackageInfo],
    summary_json: &serde_json::Value,
) -> Result<HashMap<String, Vec<CoverageFileSummary>>> {
    let files = summary_json
        .get("data")
        .and_then(serde_json::Value::as_array)
        .and_then(|data| data.first())
        .and_then(|first| first.get("files"))
        .and_then(serde_json::Value::as_array)
        .context("summary JSON missing data[0].files")?;

    let mut entries_by_package: HashMap<String, Vec<CoverageFileSummary>> = HashMap::new();
    for file in files {
        let filename = match file.get("filename").and_then(serde_json::Value::as_str) {
            Some(value) => value,
            None => continue,
        };
        let Some(package) = package_for_filename(root, package_infos, filename) else {
            continue;
        };

        let line_summary = match file
            .get("summary")
            .and_then(|summary| summary.get("lines"))
            .and_then(serde_json::Value::as_object)
        {
            Some(value) => value,
            None => continue,
        };

        let line_percent = line_summary
            .get("percent")
            .and_then(serde_json::Value::as_f64)
            .unwrap_or(0.0);
        let line_count = line_summary
            .get("count")
            .and_then(serde_json::Value::as_u64)
            .unwrap_or(0);
        let line_covered = line_summary
            .get("covered")
            .and_then(serde_json::Value::as_u64)
            .unwrap_or(0);
        entries_by_package
            .entry(package.name.clone())
            .or_default()
            .push(CoverageFileSummary {
                file: relativize_path(root, filename),
                line_percent,
                line_count,
                line_covered,
            });
    }
    Ok(entries_by_package)
}

fn zero_count_candidates_by_package(
    root: &Path,
    package_infos: &[WorkspacePackageInfo],
    full_json: &serde_json::Value,
    near_zero_callsites: usize,
    source_cache: &mut HashMap<PathBuf, String>,
    callsite_index: &CallsiteIndex,
) -> Result<(ZeroCoverageTotalsByPackage, CandidateListsByPackage)> {
    let functions = full_json
        .get("data")
        .and_then(serde_json::Value::as_array)
        .and_then(|data| data.first())
        .and_then(|first| first.get("functions"))
        .and_then(serde_json::Value::as_array)
        .context("full JSON missing data[0].functions")?;

    let mut zero_totals_by_package: ZeroCoverageTotalsByPackage = HashMap::new();
    let mut candidates_by_package: CandidateListsByPackage = HashMap::new();
    for function in functions {
        if function
            .get("count")
            .and_then(serde_json::Value::as_u64)
            .unwrap_or(0)
            != 0
        {
            continue;
        }
        let Some((package_name, candidate)) = zero_count_candidate_for_function(
            root,
            package_infos,
            function,
            near_zero_callsites,
            source_cache,
            callsite_index,
        ) else {
            continue;
        };
        *zero_totals_by_package
            .entry(package_name.clone())
            .or_insert(0) += 1;
        candidates_by_package
            .entry(package_name)
            .or_default()
            .push(candidate);
    }

    Ok((zero_totals_by_package, candidates_by_package))
}

fn zero_count_candidate_for_function(
    root: &Path,
    package_infos: &[WorkspacePackageInfo],
    function: &serde_json::Value,
    near_zero_callsites: usize,
    source_cache: &mut HashMap<PathBuf, String>,
    callsite_index: &CallsiteIndex,
) -> Option<(String, CoverageCandidate)> {
    let file = function
        .get("filenames")
        .and_then(serde_json::Value::as_array)
        .into_iter()
        .flatten()
        .filter_map(serde_json::Value::as_str)
        .find(|filename| package_for_filename(root, package_infos, filename).is_some())?;
    let package = package_for_filename(root, package_infos, file)?;
    let line = function
        .get("regions")
        .and_then(serde_json::Value::as_array)
        .and_then(|regions| regions.first())
        .and_then(serde_json::Value::as_array)
        .and_then(|region| region.first())
        .and_then(serde_json::Value::as_u64)
        .unwrap_or(0) as usize;
    let raw_function = function
        .get("name")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("<unknown>")
        .to_string();
    let demangled_function = demangle_cov_function_name(&raw_function);
    let symbol = extract_symbol_name(&demangled_function);
    let (declaration_name, has_cfg_attr, visibility, callsites_same_file) =
        candidate_symbol_metadata(root, file, line, symbol, source_cache)?;
    if declaration_name
        .as_deref()
        .is_some_and(is_opaque_symbol_name)
    {
        return None;
    }
    let callsites_workspace = declaration_name
        .as_deref()
        .and_then(|name| callsite_index.workspace_callsites(name));
    let callsites_other_crates = declaration_name
        .as_deref()
        .and_then(|name| callsite_index.other_crate_callsites(&package.name, name));
    let triage_label = classify_candidate(
        visibility.as_str(),
        has_cfg_attr,
        callsites_workspace,
        near_zero_callsites,
    )
    .to_string();
    let owner_decision = owner_decision_for_label(&triage_label).to_string();
    Some((
        package.name.clone(),
        CoverageCandidate {
            package: package.name.clone(),
            file: relativize_path(root, file),
            line,
            demangled_function,
            symbol: declaration_name,
            visibility,
            has_cfg_attr,
            callsites_same_file,
            callsites_workspace,
            callsites_other_crates,
            triage_label,
            owner_decision,
        },
    ))
}

fn package_for_filename<'a>(
    root: &Path,
    package_infos: &'a [WorkspacePackageInfo],
    filename: &str,
) -> Option<&'a WorkspacePackageInfo> {
    let rel = relativize_path(root, filename);
    package_infos
        .iter()
        .find(|package| rel.starts_with(&package.root_prefix))
}

fn candidate_symbol_metadata(
    root: &Path,
    filename: &str,
    line: usize,
    symbol: Option<String>,
    source_cache: &mut HashMap<PathBuf, String>,
) -> Option<(Option<String>, bool, String, Option<usize>)> {
    let source_file = {
        let path = Path::new(filename);
        if path.is_absolute() {
            path.to_path_buf()
        } else {
            root.join(path)
        }
    };
    if !source_cache.contains_key(&source_file) {
        let text = fs::read_to_string(&source_file).ok()?;
        source_cache.insert(source_file.clone(), text);
    }
    let source_text = source_cache.get(&source_file).map(String::as_str)?;
    let declaration = parse_fn_declaration(source_text, line);
    let has_cfg_attr = declaration_has_cfg_attr(source_text, line);
    let declaration_name = declaration
        .as_ref()
        .map(|decl| decl.name.clone())
        .or(symbol);
    let visibility = declaration
        .as_ref()
        .map(|decl| {
            if decl.is_public {
                "public".to_string()
            } else {
                "private".to_string()
            }
        })
        .unwrap_or_else(|| "unknown".to_string());
    let callsites_same_file = declaration_name
        .as_deref()
        .and_then(|name| count_callsites_same_file(source_text, name));
    Some((
        declaration_name,
        has_cfg_attr,
        visibility,
        callsites_same_file,
    ))
}

fn relativize_path(root: &Path, filename: &str) -> String {
    let path = Path::new(filename);
    let rel = path.strip_prefix(root).unwrap_or(path);
    rel.to_string_lossy().replace('\\', "/")
}

#[derive(Debug, Clone)]
struct FnDeclaration {
    name: String,
    is_public: bool,
}

fn parse_fn_declaration(source: &str, line: usize) -> Option<FnDeclaration> {
    if line == 0 {
        return None;
    }
    let line_text = source.lines().nth(line - 1)?;
    let trimmed = line_text.trim_start();
    if trimmed.starts_with("//") {
        return None;
    }
    let fn_index = trimmed.find("fn ")?;
    let prefix = &trimmed[..fn_index];
    let is_public = prefix.contains("pub");
    let after_fn = &trimmed[(fn_index + 3)..];
    let name = after_fn
        .chars()
        .take_while(|ch| ch.is_ascii_alphanumeric() || *ch == '_')
        .collect::<String>();
    if name.is_empty() {
        return None;
    }
    Some(FnDeclaration { name, is_public })
}

fn declaration_has_cfg_attr(source: &str, line: usize) -> bool {
    if line == 0 {
        return false;
    }
    let start = line.saturating_sub(4);
    let end = line.saturating_sub(1);
    for (index, line_text) in source.lines().enumerate() {
        let line_no = index + 1;
        if line_no < start || line_no > end {
            continue;
        }
        if line_text.contains("#[cfg(") || line_text.contains("#[cfg_attr(") {
            return true;
        }
    }
    false
}

fn classify_candidate(
    visibility: &str,
    has_cfg_attr: bool,
    callsites_workspace: Option<usize>,
    near_zero_callsites: usize,
) -> &'static str {
    if visibility == "public" {
        return "public_api_review";
    }
    if has_cfg_attr {
        return "rare_path_keep";
    }
    // Keep explicit single-use private helpers: we intentionally use these to
    // keep complex flows readable and avoid deep nesting.
    if callsites_workspace == Some(2) {
        return "single_use_helper_keep";
    }
    if callsites_workspace.is_some_and(|count| count <= near_zero_callsites) {
        return "dead_likely";
    }
    "needs_targeted_test"
}

fn demangle_cov_function_name(name: &str) -> String {
    if let Some(index) = name.rfind("::h") {
        let suffix = &name[(index + 3)..];
        if suffix.len() >= 8 && suffix.chars().all(|ch| ch.is_ascii_hexdigit()) {
            return name[..index].to_string();
        }
    }
    name.to_string()
}

fn extract_symbol_name(name: &str) -> Option<String> {
    for segment in name.rsplit("::") {
        let trimmed = segment.trim();
        if trimmed.is_empty() || trimmed.contains("{{closure}}") {
            continue;
        }
        let symbol = trimmed
            .chars()
            .take_while(|ch| ch.is_ascii_alphanumeric() || *ch == '_')
            .collect::<String>();
        if !symbol.is_empty() {
            return Some(symbol);
        }
    }
    None
}

fn unix_timestamp_seconds() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|duration| duration.as_secs())
        .unwrap_or(0)
}

fn ensure_cargo_llvm_cov_available(root: &Path) -> Result<()> {
    let mut cmd = Command::new("cargo");
    cmd.arg("llvm-cov").arg("--version").current_dir(root);
    let _ = run_capture(cmd)
        .context("cargo-llvm-cov is required. Install with: cargo install cargo-llvm-cov")?;
    Ok(())
}

fn ensure_llvm_tools_preview_available(root: &Path) -> Result<()> {
    let mut rustc_info = Command::new("rustc");
    rustc_info.arg("-vV").current_dir(root);
    let rustc_info =
        run_capture(rustc_info).context("failed to run `rustc -vV` for coverage preflight")?;
    let host = parse_rustc_host(&rustc_info)
        .context("failed to parse host triple from `rustc -vV` output")?;

    let mut rustc_sysroot = Command::new("rustc");
    rustc_sysroot
        .arg("--print")
        .arg("sysroot")
        .current_dir(root);
    let sysroot = run_capture(rustc_sysroot)
        .context("failed to run `rustc --print sysroot` for coverage preflight")?;
    let rustlib_bin = Path::new(sysroot.trim())
        .join("lib")
        .join("rustlib")
        .join(host)
        .join("bin");
    let llvm_cov = rustlib_bin.join(exe_name("llvm-cov"));
    let llvm_profdata = rustlib_bin.join(exe_name("llvm-profdata"));
    if llvm_cov.is_file() && llvm_profdata.is_file() {
        return Ok(());
    }

    let install_cmd = active_toolchain(root)
        .map(|toolchain| format!("rustup component add llvm-tools-preview --toolchain {toolchain}"))
        .unwrap_or_else(|| "rustup component add llvm-tools-preview".to_string());
    bail!(
        "missing rustup component `llvm-tools-preview` for the active toolchain.\n\
expected tools:\n  {}\n  {}\n\
install with:\n  {}\n\
then re-run:\n  cargo make coverage-run",
        llvm_cov.display(),
        llvm_profdata.display(),
        install_cmd
    );
}

fn parse_rustc_host(rustc_info: &str) -> Option<&str> {
    rustc_info
        .lines()
        .find_map(|line| line.strip_prefix("host: "))
        .map(str::trim)
        .filter(|host| !host.is_empty())
}

fn active_toolchain(root: &Path) -> Option<String> {
    let mut cmd = Command::new("rustup");
    cmd.arg("show").arg("active-toolchain").current_dir(root);
    let output = run_capture(cmd).ok()?;
    output
        .split_whitespace()
        .next()
        .map(str::to_string)
        .filter(|toolchain| !toolchain.is_empty())
}

fn workspace_package_infos(root: &Path) -> Result<Vec<WorkspacePackageInfo>> {
    let mut cmd = Command::new("cargo");
    cmd.arg("metadata")
        .arg("--no-deps")
        .arg("--format-version=1")
        .current_dir(root);
    let metadata_json = run_capture(cmd).context("failed to run cargo metadata")?;
    let metadata: serde_json::Value =
        serde_json::from_str(&metadata_json).context("failed to parse cargo metadata JSON")?;

    let workspace_members = metadata
        .get("workspace_members")
        .and_then(serde_json::Value::as_array)
        .context("cargo metadata missing workspace_members")?
        .iter()
        .filter_map(serde_json::Value::as_str)
        .map(str::to_string)
        .collect::<BTreeSet<_>>();

    let mut package_infos = metadata
        .get("packages")
        .and_then(serde_json::Value::as_array)
        .context("cargo metadata missing packages")?
        .iter()
        .filter_map(|pkg| {
            let id = pkg.get("id").and_then(serde_json::Value::as_str)?;
            if !workspace_members.contains(id) {
                return None;
            }
            let name = pkg.get("name").and_then(serde_json::Value::as_str)?;
            let manifest_path = pkg
                .get("manifest_path")
                .and_then(serde_json::Value::as_str)?;
            let manifest_path = Path::new(manifest_path);
            let package_root = manifest_path.parent()?;
            let root_prefix = package_root
                .strip_prefix(root)
                .unwrap_or(package_root)
                .to_string_lossy()
                .replace('\\', "/");
            Some(WorkspacePackageInfo {
                name: name.to_string(),
                root_prefix: format!("{root_prefix}/"),
            })
        })
        .collect::<Vec<_>>();

    package_infos.sort_by(|a, b| {
        b.root_prefix
            .len()
            .cmp(&a.root_prefix.len())
            .then(a.name.cmp(&b.name))
    });
    package_infos.dedup_by(|a, b| a.name == b.name && a.root_prefix == b.root_prefix);
    Ok(package_infos)
}

fn run_cargo_with_args(root: &Path, args: &[String]) -> Result<()> {
    let mut command = Command::new("cargo");
    for arg in args {
        command.arg(arg);
    }
    command.current_dir(root);
    run_status(command)
}
