//! Lazy GALEC / eFMI codegen addon for the rumoca WASM package.
//!
//! This is a SEPARATE `cdylib` sibling of `rumoca-bind-wasm`: the core
//! rumoca WASM binary (Modelica / template / simulation workflows) must NOT
//! grow the GALEC → eFMI Algorithm Code + embedded-C projection, so this
//! module carries it on its own and is loaded on demand only when a user
//! selects a GALEC codegen target. It mirrors the repo's lazy-diffsol-addon
//! (`rumoca-bind-wasm-diffsol`) and the layered core/rumoca/viz/live
//! packaging direction.
//!
//! It is self-contained: [`render_galec`] compiles Modelica in-memory to the
//! canonical DAE and then projects it to GALEC (`.alg`) and — for the C
//! targets — the GALEC-derived embedded C, in one call.
//!
//! ## The wasm32 identity hazard
//!
//! The `rumoca-compile` container plans (`plan_galec_production_export`) mint
//! a packaging identity — a v4 UUID plus `time::now_utc` — which panics on
//! `wasm32-unknown-unknown` without the `time` wasm feature. This addon never
//! takes that path: it drives the identity-free
//! [`rumoca_galec_codegen::lower_to_algorithm_code`] projection directly and
//! renders the shared embedded-C-layout templates itself, so no UUID or clock
//! is ever touched.

use minijinja::{Environment, UndefinedBehavior, Value as JinjaValue, context};
use rumoca_compile::codegen::targets::{TargetBundle, TargetTemplateSource};
use rumoca_compile::galec::{GalecInput, GalecOptions, build_scalar_type_map};
use rumoca_compile::{Session, SessionConfig};
use rumoca_galec_codegen::{
    c_template_context, lower_to_algorithm_code, render_algorithm_code, xml_escape, xs_double,
};
use serde_json::{Value, json};
use wasm_bindgen::prelude::*;

/// The three GALEC codegen targets this addon serves (all `ir = "dae"`):
///
/// - `galec` — eFMI Algorithm Code eFMU (`.alg` only from this addon's view);
/// - `galec-production` — eFMI Production Code eFMU (adds C99 + manifest); the
///   container packaging lives in the native CLI, but the C files it wraps
///   claim the Production Code representation, so this addon renders them with
///   that conformance header;
/// - `embedded-c-galec` — GALEC-derived embedded C, explicitly NOT an eFMI
///   container, so its C files self-describe as such.
const TARGET_GALEC: &str = "galec";
const TARGET_GALEC_PRODUCTION: &str = "galec-production";
const TARGET_EMBEDDED_C_GALEC: &str = "embedded-c-galec";

/// The builtin target bundle whose `model.h.jinja`/`model.c.jinja` own the C
/// FILE LAYOUT (the galec-production bundle's C templates are passthroughs of
/// pre-rendered text; the real conformance-headed C-layout templates live in
/// the `embedded-c-galec` bundle, shared by both C tracks — mirroring
/// `rumoca-compile`'s `plan_galec_production_export`).
const C_LAYOUT_BUNDLE: &str = "embedded-c-galec";
const HEADER_TEMPLATE: &str = "model.h.jinja";
const SOURCE_TEMPLATE: &str = "model.c.jinja";

/// `galec-production` C-file conformance claim (SPEC_0034 GAL-024 / D10):
/// inside the conformant eFMU these C files ARE the Production Code
/// representation, and the conformance surface is the manifest's LogicalData.
/// Kept verbatim in sync with `rumoca-compile`'s
/// `galec_api::PRODUCTION_CONFORMANCE_LINES`/`_SUMMARY`.
const PRODUCTION_CONFORMANCE_LINES: &[&str] = &[
    "eFMI Production Code representation; the conformance surface is",
    "ProductionCode/manifest.xml (LogicalData), not these C names",
    "(SPEC_0034 GAL-024).",
];
const PRODUCTION_CONFORMANCE_SUMMARY: &str =
    "eFMI Production Code representation (SPEC_0034 GAL-024).";

/// `embedded-c-galec` C-file conformance claim: the non-eFMI track must
/// self-describe as NOT an eFMI Production Code container. Kept verbatim in
/// sync with `rumoca`'s `target_manifest::EMBEDDED_C_GALEC_CONFORMANCE_HEADER`.
const EMBEDDED_C_GALEC_CONFORMANCE_LINES: &[&str] = &[
    "NOT an eFMI Production Code container: no eFMU manifest mapping exists",
    "for this artifact. Generated by rumoca --target embedded-c-galec.",
];
const EMBEDDED_C_GALEC_CONFORMANCE_SUMMARY: &str = "NOT an eFMI Production Code container.";

/// Initialize the panic hook for readable console errors (mirrors the core
/// binding and the diffsol addon).
#[wasm_bindgen(start)]
pub fn init() {
    #[cfg(feature = "console_error_panic_hook")]
    console_error_panic_hook::set_once();
}

/// Compile Modelica `source`, project the model named `model_name` to GALEC,
/// and return the rendered artifacts as a JSON string.
///
/// `target` is one of `galec`, `galec-production`, `embedded-c-galec`.
///
/// Success shape:
/// ```json
/// { "ok": true, "target": "<target>", "alg": "<.alg text>",
///   "c_header": "<.h text or empty>", "c_source": "<.c text or empty>" }
/// ```
/// The `c_header`/`c_source` fields are empty strings for the `galec` target
/// (Algorithm Code only). Failure shape: `{ "ok": false, "error": "<msg>" }`.
#[wasm_bindgen]
pub fn render_galec(source: &str, model_name: &str, target: &str) -> String {
    let value = match render_galec_impl(source, model_name, target) {
        Ok(value) => value,
        Err(error) => json!({ "ok": false, "error": error }),
    };
    // A `serde_json::Value` built from strings always serializes; fall back to
    // a hand-built error string on the impossible failure so the contract
    // (always a JSON string) still holds.
    serde_json::to_string(&value).unwrap_or_else(|error| {
        format!("{{\"ok\":false,\"error\":\"response serialization failed: {error}\"}}")
    })
}

fn render_galec_impl(source: &str, model_name: &str, target: &str) -> Result<Value, String> {
    if !matches!(
        target,
        TARGET_GALEC | TARGET_GALEC_PRODUCTION | TARGET_EMBEDDED_C_GALEC
    ) {
        return Err(format!(
            "unknown GALEC target '{target}' \
             (expected one of {TARGET_GALEC}, {TARGET_GALEC_PRODUCTION}, {TARGET_EMBEDDED_C_GALEC})"
        ));
    }

    // 1. Compile the source in-memory to the canonical DAE + Flat model
    //    (mirror the sibling's in-memory Session path).
    let mut session = Session::new(SessionConfig::default());
    session
        .add_document("input.mo", source)
        .map_err(|error| format!("failed to load source: {error}"))?;
    let requested = qualify_input_model_name(&session, model_name);
    let result = session
        .compile_model(&requested)
        .map_err(|error| format!("compilation error: {error}"))?;

    // 2. Identity-free projection to the validated Algorithm Code package
    //    (never the UUID/clock-minting container plans — the wasm32 hazard).
    let model_id = model_name.replace('.', "_");
    let scalar_types = build_scalar_type_map(&result.flat);
    let input = GalecInput::new(&result.dae, &model_id).with_scalar_types(&scalar_types);
    let package = lower_to_algorithm_code(&input, &GalecOptions::default())
        .map_err(|diagnostics| render_projection_diagnostics(&diagnostics))?;
    let alg = render_algorithm_code(&package).map_err(|error| error.to_string())?;

    // 3. For the C tracks, render the shared embedded-C-layout templates with
    //    the projection's typed C context plus this target's conformance
    //    header (the one key that is target identity, not projection data).
    let (c_header, c_source) =
        if matches!(target, TARGET_GALEC_PRODUCTION | TARGET_EMBEDDED_C_GALEC) {
            let c_context = c_template_context(&package, model_name)
                .map_err(|error| format!("C template context failed: {error}"))?;
            let header = render_c_layout(target, HEADER_TEMPLATE, &c_context)?;
            let source = render_c_layout(target, SOURCE_TEMPLATE, &c_context)?;
            (header, source)
        } else {
            (String::new(), String::new())
        };

    // 4. JSON response.
    Ok(json!({
        "ok": true,
        "target": target,
        "alg": alg,
        "c_header": c_header,
        "c_source": c_source,
    }))
}

/// Render one shared embedded-C-layout template under a strict-undefined,
/// autoescape-off minijinja environment, feeding the serialized typed C
/// context plus this target's conformance header.
fn render_c_layout(target: &str, template: &str, c_context: &Value) -> Result<String, String> {
    let bundle = TargetBundle::builtin(C_LAYOUT_BUNDLE).ok_or_else(|| {
        format!("builtin C-layout bundle '{C_LAYOUT_BUNDLE}' is not embedded in this build")
    })?;
    let template_source = bundle
        .template_source(template)
        .map_err(|error| format!("read template '{template}': {error:#}"))?;

    let (lines, summary) = conformance_header(target);
    let mut env = Environment::new();
    env.set_undefined_behavior(UndefinedBehavior::Strict);
    // The manifest render filters are registered so the C-layout templates —
    // which do not use them today — stay renderable if they ever adopt the
    // shared filter vocabulary, matching every other GALEC render env.
    env.add_filter("xml_escape", |text: String| xml_escape(&text));
    env.add_filter("xs_double", xs_double);
    env.render_str(
        &template_source,
        context! {
            conformance_header => context! { lines => lines, summary => summary },
            ..JinjaValue::from_serialize(c_context)
        },
    )
    .map_err(|error| format!("render '{template}': {error}"))
}

/// The conformance header (`lines` + `summary`) for a C-producing target.
fn conformance_header(target: &str) -> (&'static [&'static str], &'static str) {
    if target == TARGET_GALEC_PRODUCTION {
        (PRODUCTION_CONFORMANCE_LINES, PRODUCTION_CONFORMANCE_SUMMARY)
    } else {
        (
            EMBEDDED_C_GALEC_CONFORMANCE_LINES,
            EMBEDDED_C_GALEC_CONFORMANCE_SUMMARY,
        )
    }
}

/// Render the collected projection diagnostics into a single error message.
fn render_projection_diagnostics(diagnostics: &[rumoca_galec_codegen::GalecTargetError]) -> String {
    let body = diagnostics
        .iter()
        .map(|diagnostic| format!("  - {diagnostic}"))
        .collect::<Vec<_>>()
        .join("\n");
    format!("GALEC projection rejected the model:\n{body}")
}

/// Qualify a bare model name against the in-memory document's `within` prefix
/// (mirrors `rumoca-bind-wasm`'s `qualify_input_model_name`): a dotted name is
/// already qualified, and a bare top-level class in a `within P;` file resolves
/// to `P.<name>`.
fn qualify_input_model_name(session: &Session, model_name: &str) -> String {
    if model_name.contains('.') {
        return model_name.to_string();
    }
    let Some(doc) = session.get_document("input.mo") else {
        return model_name.to_string();
    };
    let Some(parsed) = doc.parsed().or_else(|| doc.recovered()) else {
        return model_name.to_string();
    };
    if !parsed.classes.contains_key(model_name) {
        return model_name.to_string();
    }
    let within = parsed
        .within
        .as_ref()
        .map(ToString::to_string)
        .filter(|prefix| !prefix.is_empty());
    within.map_or_else(
        || model_name.to_string(),
        |prefix| format!("{prefix}.{model_name}"),
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Fixed-sample discrete model admissible for GALEC projection (mirrors
    /// the `rumoca-compile` galec facade fixture).
    const DISCRETE_SOURCE: &str = r#"
model GalecWasmDemo
  constant Real samplePeriod = 0.001;
  parameter Real gain = 2.0;
  discrete Integer count(start = 0);
  discrete output Real y(start = 0.0);
equation
  when sample(0.0, samplePeriod) then
    count = pre(count) + 1;
    y = gain * count;
  end when;
end GalecWasmDemo;
"#;

    fn parse(json: &str) -> Value {
        serde_json::from_str(json).expect("render_galec must return valid JSON")
    }

    #[test]
    fn galec_target_returns_alg_only() {
        let value = parse(&render_galec(
            DISCRETE_SOURCE,
            "GalecWasmDemo",
            TARGET_GALEC,
        ));
        assert_eq!(value["ok"], true, "{value}");
        assert_eq!(value["target"], TARGET_GALEC);
        assert!(
            value["alg"]
                .as_str()
                .is_some_and(|alg| alg.contains("DoStep")),
            "alg should carry the DoStep method: {value}"
        );
        assert_eq!(value["c_header"], "");
        assert_eq!(value["c_source"], "");
    }

    #[test]
    fn embedded_c_target_renders_c_with_not_a_container_header() {
        let value = parse(&render_galec(
            DISCRETE_SOURCE,
            "GalecWasmDemo",
            TARGET_EMBEDDED_C_GALEC,
        ));
        assert_eq!(value["ok"], true, "{value}");
        let header = value["c_header"].as_str().expect("c_header string");
        let source = value["c_source"].as_str().expect("c_source string");
        assert!(header.contains("GalecWasmDemoState"), "{header}");
        assert!(source.contains("_dostep("), "{source}");
        assert!(
            header.contains(EMBEDDED_C_GALEC_CONFORMANCE_LINES[0]),
            "embedded-c header must self-describe as NOT a container: {header}"
        );
    }

    #[test]
    fn production_target_renders_c_with_production_conformance_header() {
        let value = parse(&render_galec(
            DISCRETE_SOURCE,
            "GalecWasmDemo",
            TARGET_GALEC_PRODUCTION,
        ));
        assert_eq!(value["ok"], true, "{value}");
        let header = value["c_header"].as_str().expect("c_header string");
        let source = value["c_source"].as_str().expect("c_source string");
        assert!(
            header.contains(PRODUCTION_CONFORMANCE_LINES[0]),
            "production header must claim the PC representation: {header}"
        );
        assert!(
            source.contains(PRODUCTION_CONFORMANCE_SUMMARY),
            "production source must carry the PC summary: {source}"
        );
        assert!(
            !header.contains("NOT an eFMI Production Code container"),
            "the embedded-c NOT-a-container claim must not leak into production: {header}"
        );
    }

    #[test]
    fn unknown_target_is_a_loud_error() {
        let value = parse(&render_galec(DISCRETE_SOURCE, "GalecWasmDemo", "fmi3"));
        assert_eq!(value["ok"], false);
        assert!(
            value["error"]
                .as_str()
                .is_some_and(|error| error.contains("unknown GALEC target")),
            "{value}"
        );
    }

    #[test]
    fn continuous_model_is_rejected_with_projection_diagnostics() {
        let source = r#"
model ContinuousDemo
  Real x(start = 1.0);
  parameter Real k = 2.0;
equation
  der(x) = -k * x;
end ContinuousDemo;
"#;
        let value = parse(&render_galec(source, "ContinuousDemo", TARGET_GALEC));
        assert_eq!(value["ok"], false);
        assert!(
            value["error"]
                .as_str()
                .is_some_and(|error| error.contains("projection rejected")),
            "{value}"
        );
    }
}
