/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>
#include <lcm/lcm_cpptypes.hpp>

#ifndef __sym_algebraics_t_hpp__
#define __sym_algebraics_t_hpp__

#if defined(SKYMARSHAL_PRINTING_ENABLED)
#include <lcm/lcm_reflection.hpp>
#include <array>
#endif
#include <ostream>


namespace sym
{

class algebraics_t
{
    public:
        double R11;

        double R12;

        double R13;

        double R21;

        double R22;

        double R23;

        double R31;

        double R32;

        double R33;

    public:
        algebraics_t() = default;

        /**
         * Member constructor
         */
        inline algebraics_t(
            const double& R11_arg,
            const double& R12_arg,
            const double& R13_arg,
            const double& R21_arg,
            const double& R22_arg,
            const double& R23_arg,
            const double& R31_arg,
            const double& R32_arg,
            const double& R33_arg
        );

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline __lcm_buffer_size encode(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline __lcm_buffer_size getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline __lcm_buffer_size decode(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        constexpr static uint64_t getHash();

        using type_name_array_t = const char[13];

        inline static constexpr type_name_array_t* getTypeNameArrayPtr();

        /**
         * Returns "algebraics_t"
         */
        inline static constexpr const char* getTypeName();

        using package_name_array_t = const char[4];

        inline static constexpr package_name_array_t* getPackageNameArrayPtr();

        /**
         * Returns "sym"
         */
        inline static constexpr const char * getPackageName();

        // LCM support functions. Users should not call these
        inline __lcm_buffer_size _encodeNoHash(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const;
        inline __lcm_buffer_size _getEncodedSizeNoHash() const;
        inline __lcm_buffer_size _decodeNoHash(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen);
        constexpr static uint64_t _computeHash(const __lcm_hash_ptr *)
        {
            uint64_t hash = 0x01555f7bf5a8c563LL;
            return (hash<<1) + ((hash>>63)&1);
        }

        // Comparison operators.
        inline bool operator==(const algebraics_t& other) const;
        inline bool operator!=(const algebraics_t& other) const;

#if defined(SKYMARSHAL_PRINTING_ENABLED)
        constexpr static std::array<const char*, 9> fields()
        {
            return {{
                "R11",
                "R12",
                "R13",
                "R21",
                "R22",
                "R23",
                "R31",
                "R32",
                "R33",
            }};
        }

        // Get the schema for this type
        static lcm::StructType schema()
        {
            std::vector<lcm::SchemaType> fields;

            fields.push_back(lcm::get_schema<decltype(algebraics_t::R11)>());
            fields.push_back(lcm::get_schema<decltype(algebraics_t::R12)>());
            fields.push_back(lcm::get_schema<decltype(algebraics_t::R13)>());
            fields.push_back(lcm::get_schema<decltype(algebraics_t::R21)>());
            fields.push_back(lcm::get_schema<decltype(algebraics_t::R22)>());
            fields.push_back(lcm::get_schema<decltype(algebraics_t::R23)>());
            fields.push_back(lcm::get_schema<decltype(algebraics_t::R31)>());
            fields.push_back(lcm::get_schema<decltype(algebraics_t::R32)>());
            fields.push_back(lcm::get_schema<decltype(algebraics_t::R33)>());

            return lcm::StructType{
                .fields = std::move(fields),
            };
        }

        // Given a string field path, translate the entire path to field / list indices within this struct.
        // Return value is 0 if the operation succeeded.
        // If the operation failed, return value is equal to 1 + the index of the first invalid field.
        static uint32_t translate_fields(const char* const _fields[], uint32_t _field_indices_out[], uint32_t _num_fields) {
            if (strcmp(_fields[0], fields()[0]) == 0) {
                _field_indices_out[0] = 0;
                uint32_t ret = lcm::translate_fields<decltype(algebraics_t::R11)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[1]) == 0) {
                _field_indices_out[0] = 1;
                uint32_t ret = lcm::translate_fields<decltype(algebraics_t::R12)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[2]) == 0) {
                _field_indices_out[0] = 2;
                uint32_t ret = lcm::translate_fields<decltype(algebraics_t::R13)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[3]) == 0) {
                _field_indices_out[0] = 3;
                uint32_t ret = lcm::translate_fields<decltype(algebraics_t::R21)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[4]) == 0) {
                _field_indices_out[0] = 4;
                uint32_t ret = lcm::translate_fields<decltype(algebraics_t::R22)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[5]) == 0) {
                _field_indices_out[0] = 5;
                uint32_t ret = lcm::translate_fields<decltype(algebraics_t::R23)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[6]) == 0) {
                _field_indices_out[0] = 6;
                uint32_t ret = lcm::translate_fields<decltype(algebraics_t::R31)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[7]) == 0) {
                _field_indices_out[0] = 7;
                uint32_t ret = lcm::translate_fields<decltype(algebraics_t::R32)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[8]) == 0) {
                _field_indices_out[0] = 8;
                uint32_t ret = lcm::translate_fields<decltype(algebraics_t::R33)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            return 1;

        }

        // Return value is 0 if the operation succeeded.
        // If the operation failed, return value is equal to 1 + the index of the first invalid field.
        uint32_t show_field(std::ostream& _stream, const uint32_t _field_indices[], uint32_t _num_fields, const lcm::FormatSettings &_settings) const
        {
            uint32_t ret;
            switch (_field_indices[0]) {
                case 0:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, R11, _settings);
                return ret == 0 ? ret : ret + 1;
                case 1:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, R12, _settings);
                return ret == 0 ? ret : ret + 1;
                case 2:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, R13, _settings);
                return ret == 0 ? ret : ret + 1;
                case 3:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, R21, _settings);
                return ret == 0 ? ret : ret + 1;
                case 4:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, R22, _settings);
                return ret == 0 ? ret : ret + 1;
                case 5:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, R23, _settings);
                return ret == 0 ? ret : ret + 1;
                case 6:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, R31, _settings);
                return ret == 0 ? ret : ret + 1;
                case 7:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, R32, _settings);
                return ret == 0 ? ret : ret + 1;
                case 8:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, R33, _settings);
                return ret == 0 ? ret : ret + 1;
                default:
                return 1;
            }
        }

        // Ability to print to standard streams as well as the fmt library.
        friend std::ostream& operator<<(std::ostream& _stream, const algebraics_t& obj) {
            const lcm::FormatSettings settings = lcm::FormatSettings{
                .indent = 0,
                .eigen_no_nested_arrays = false,
            };
            lcm::show_field(_stream, nullptr, 0, obj, settings);
            return _stream;
        }

#else
        friend std::ostream& operator<<(std::ostream& _stream, const algebraics_t& obj) {
            _stream << "<FORMATTING DISABLED>";
            return _stream;
        }
#endif

#if defined(SKYMARSHAL_STORING_ENABLED)
        // Return value is 0 if the operation succeeded.
        // If the operation failed, return value is equal to 1 + the index of the first invalid field,
        // 1 + field_size if there are not enough fields, or 2 + field_size if the value is invalid.
        __attribute__((nodiscard)) uint32_t store_field(const uint32_t _field_indices[], uint32_t _num_fields, const char* const _value)
        {
            uint32_t ret;
            switch (_field_indices[0]) {
                case 0:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, R11, _value);
                return ret == 0 ? ret : ret + 1;
                case 1:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, R12, _value);
                return ret == 0 ? ret : ret + 1;
                case 2:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, R13, _value);
                return ret == 0 ? ret : ret + 1;
                case 3:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, R21, _value);
                return ret == 0 ? ret : ret + 1;
                case 4:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, R22, _value);
                return ret == 0 ? ret : ret + 1;
                case 5:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, R23, _value);
                return ret == 0 ? ret : ret + 1;
                case 6:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, R31, _value);
                return ret == 0 ? ret : ret + 1;
                case 7:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, R32, _value);
                return ret == 0 ? ret : ret + 1;
                case 8:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, R33, _value);
                return ret == 0 ? ret : ret + 1;
                default:
                return 1;
            }
        }
#endif
};

algebraics_t::algebraics_t(
    const double& R11_arg,
    const double& R12_arg,
    const double& R13_arg,
    const double& R21_arg,
    const double& R22_arg,
    const double& R23_arg,
    const double& R31_arg,
    const double& R32_arg,
    const double& R33_arg
) : R11(R11_arg),
    R12(R12_arg),
    R13(R13_arg),
    R21(R21_arg),
    R22(R22_arg),
    R23(R23_arg),
    R31(R31_arg),
    R32(R32_arg),
    R33(R33_arg) {}

__lcm_buffer_size algebraics_t::encode(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const
{
    __lcm_buffer_size pos = 0, tlen;
    uint64_t hash = getHash();

    tlen = __uint64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

__lcm_buffer_size algebraics_t::decode(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen)
{
    __lcm_buffer_size pos = 0, thislen;

    uint64_t hash;
    thislen = __uint64_t_decode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

__lcm_buffer_size algebraics_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

constexpr uint64_t algebraics_t::getHash()
{
    return _computeHash(NULL);
}

constexpr algebraics_t::type_name_array_t* algebraics_t::getTypeNameArrayPtr() {
    return &"algebraics_t";
}

constexpr const char* algebraics_t::getTypeName()
{
    return *algebraics_t::getTypeNameArrayPtr();
}

constexpr algebraics_t::package_name_array_t* algebraics_t::getPackageNameArrayPtr() {
    return &"sym";
}

constexpr const char * algebraics_t::getPackageName()
{
    return *algebraics_t::getPackageNameArrayPtr();
}

__lcm_buffer_size algebraics_t::_encodeNoHash(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const
{
    __lcm_buffer_size pos = 0, tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R11, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R12, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R13, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R21, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R22, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R23, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R31, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R32, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->R33, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

__lcm_buffer_size algebraics_t::_decodeNoHash(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen)
{
    __lcm_buffer_size pos = 0, tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R11, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R12, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R13, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R21, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R22, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R23, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R31, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R32, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->R33, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

__lcm_buffer_size algebraics_t::_getEncodedSizeNoHash() const
{
    __lcm_buffer_size enc_size = 0;
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    return enc_size;
}

bool algebraics_t::operator==(const algebraics_t& other) const {
  return (
          (R11==other.R11) && 
          (R12==other.R12) && 
          (R13==other.R13) && 
          (R21==other.R21) && 
          (R22==other.R22) && 
          (R23==other.R23) && 
          (R31==other.R31) && 
          (R32==other.R32) && 
          (R33==other.R33));
}

bool algebraics_t::operator!=(const algebraics_t& other) const {
  return !(*this==other);
}

}

#endif