/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <lcm/lcm_coretypes.h>
#include <lcm/lcm_cpptypes.hpp>

#ifndef __sym_derivatives_t_hpp__
#define __sym_derivatives_t_hpp__

#if defined(SKYMARSHAL_PRINTING_ENABLED)
#include <lcm/lcm_reflection.hpp>
#include <array>
#endif
#include <ostream>


namespace sym
{

class derivatives_t
{
    public:
        double px;

        double py;

        double pz;

        double vx;

        double vy;

        double vz;

        double qw;

        double qx;

        double qy;

        double qz;

    public:
        derivatives_t() = default;

        /**
         * Member constructor
         */
        inline derivatives_t(
            const double& px_arg,
            const double& py_arg,
            const double& pz_arg,
            const double& vx_arg,
            const double& vy_arg,
            const double& vz_arg,
            const double& qw_arg,
            const double& qx_arg,
            const double& qy_arg,
            const double& qz_arg
        );

        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline __lcm_buffer_size encode(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline __lcm_buffer_size getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline __lcm_buffer_size decode(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        constexpr static uint64_t getHash();

        using type_name_array_t = const char[14];

        inline static constexpr type_name_array_t* getTypeNameArrayPtr();

        /**
         * Returns "derivatives_t"
         */
        inline static constexpr const char* getTypeName();

        using package_name_array_t = const char[4];

        inline static constexpr package_name_array_t* getPackageNameArrayPtr();

        /**
         * Returns "sym"
         */
        inline static constexpr const char * getPackageName();

        // LCM support functions. Users should not call these
        inline __lcm_buffer_size _encodeNoHash(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const;
        inline __lcm_buffer_size _getEncodedSizeNoHash() const;
        inline __lcm_buffer_size _decodeNoHash(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen);
        constexpr static uint64_t _computeHash(const __lcm_hash_ptr *)
        {
            uint64_t hash = 0x407c71b88e190fa3LL;
            return (hash<<1) + ((hash>>63)&1);
        }

        // Comparison operators.
        inline bool operator==(const derivatives_t& other) const;
        inline bool operator!=(const derivatives_t& other) const;

#if defined(SKYMARSHAL_PRINTING_ENABLED)
        constexpr static std::array<const char*, 10> fields()
        {
            return {{
                "px",
                "py",
                "pz",
                "vx",
                "vy",
                "vz",
                "qw",
                "qx",
                "qy",
                "qz",
            }};
        }

        // Get the schema for this type
        static lcm::StructType schema()
        {
            std::vector<lcm::SchemaType> fields;

            fields.push_back(lcm::get_schema<decltype(derivatives_t::px)>());
            fields.push_back(lcm::get_schema<decltype(derivatives_t::py)>());
            fields.push_back(lcm::get_schema<decltype(derivatives_t::pz)>());
            fields.push_back(lcm::get_schema<decltype(derivatives_t::vx)>());
            fields.push_back(lcm::get_schema<decltype(derivatives_t::vy)>());
            fields.push_back(lcm::get_schema<decltype(derivatives_t::vz)>());
            fields.push_back(lcm::get_schema<decltype(derivatives_t::qw)>());
            fields.push_back(lcm::get_schema<decltype(derivatives_t::qx)>());
            fields.push_back(lcm::get_schema<decltype(derivatives_t::qy)>());
            fields.push_back(lcm::get_schema<decltype(derivatives_t::qz)>());

            return lcm::StructType{
                .fields = std::move(fields),
            };
        }

        // Given a string field path, translate the entire path to field / list indices within this struct.
        // Return value is 0 if the operation succeeded.
        // If the operation failed, return value is equal to 1 + the index of the first invalid field.
        static uint32_t translate_fields(const char* const _fields[], uint32_t _field_indices_out[], uint32_t _num_fields) {
            if (strcmp(_fields[0], fields()[0]) == 0) {
                _field_indices_out[0] = 0;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::px)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[1]) == 0) {
                _field_indices_out[0] = 1;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::py)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[2]) == 0) {
                _field_indices_out[0] = 2;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::pz)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[3]) == 0) {
                _field_indices_out[0] = 3;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::vx)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[4]) == 0) {
                _field_indices_out[0] = 4;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::vy)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[5]) == 0) {
                _field_indices_out[0] = 5;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::vz)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[6]) == 0) {
                _field_indices_out[0] = 6;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::qw)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[7]) == 0) {
                _field_indices_out[0] = 7;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::qx)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[8]) == 0) {
                _field_indices_out[0] = 8;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::qy)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            if (strcmp(_fields[0], fields()[9]) == 0) {
                _field_indices_out[0] = 9;
                uint32_t ret = lcm::translate_fields<decltype(derivatives_t::qz)>(_fields + 1, _field_indices_out + 1, _num_fields - 1);
                return ret == 0 ? ret : ret + 1;
            }
            return 1;

        }

        // Return value is 0 if the operation succeeded.
        // If the operation failed, return value is equal to 1 + the index of the first invalid field.
        uint32_t show_field(std::ostream& _stream, const uint32_t _field_indices[], uint32_t _num_fields, const lcm::FormatSettings &_settings) const
        {
            uint32_t ret;
            switch (_field_indices[0]) {
                case 0:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, px, _settings);
                return ret == 0 ? ret : ret + 1;
                case 1:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, py, _settings);
                return ret == 0 ? ret : ret + 1;
                case 2:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, pz, _settings);
                return ret == 0 ? ret : ret + 1;
                case 3:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, vx, _settings);
                return ret == 0 ? ret : ret + 1;
                case 4:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, vy, _settings);
                return ret == 0 ? ret : ret + 1;
                case 5:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, vz, _settings);
                return ret == 0 ? ret : ret + 1;
                case 6:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, qw, _settings);
                return ret == 0 ? ret : ret + 1;
                case 7:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, qx, _settings);
                return ret == 0 ? ret : ret + 1;
                case 8:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, qy, _settings);
                return ret == 0 ? ret : ret + 1;
                case 9:
                ret = lcm::show_field(_stream, _field_indices + 1, _num_fields - 1, qz, _settings);
                return ret == 0 ? ret : ret + 1;
                default:
                return 1;
            }
        }

        // Ability to print to standard streams as well as the fmt library.
        friend std::ostream& operator<<(std::ostream& _stream, const derivatives_t& obj) {
            const lcm::FormatSettings settings = lcm::FormatSettings{
                .indent = 0,
                .eigen_no_nested_arrays = false,
            };
            lcm::show_field(_stream, nullptr, 0, obj, settings);
            return _stream;
        }

#else
        friend std::ostream& operator<<(std::ostream& _stream, const derivatives_t& obj) {
            _stream << "<FORMATTING DISABLED>";
            return _stream;
        }
#endif

#if defined(SKYMARSHAL_STORING_ENABLED)
        // Return value is 0 if the operation succeeded.
        // If the operation failed, return value is equal to 1 + the index of the first invalid field,
        // 1 + field_size if there are not enough fields, or 2 + field_size if the value is invalid.
        __attribute__((nodiscard)) uint32_t store_field(const uint32_t _field_indices[], uint32_t _num_fields, const char* const _value)
        {
            uint32_t ret;
            switch (_field_indices[0]) {
                case 0:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, px, _value);
                return ret == 0 ? ret : ret + 1;
                case 1:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, py, _value);
                return ret == 0 ? ret : ret + 1;
                case 2:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, pz, _value);
                return ret == 0 ? ret : ret + 1;
                case 3:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, vx, _value);
                return ret == 0 ? ret : ret + 1;
                case 4:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, vy, _value);
                return ret == 0 ? ret : ret + 1;
                case 5:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, vz, _value);
                return ret == 0 ? ret : ret + 1;
                case 6:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, qw, _value);
                return ret == 0 ? ret : ret + 1;
                case 7:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, qx, _value);
                return ret == 0 ? ret : ret + 1;
                case 8:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, qy, _value);
                return ret == 0 ? ret : ret + 1;
                case 9:
                ret = lcm::store_field(_field_indices + 1, _num_fields - 1, qz, _value);
                return ret == 0 ? ret : ret + 1;
                default:
                return 1;
            }
        }
#endif
};

derivatives_t::derivatives_t(
    const double& px_arg,
    const double& py_arg,
    const double& pz_arg,
    const double& vx_arg,
    const double& vy_arg,
    const double& vz_arg,
    const double& qw_arg,
    const double& qx_arg,
    const double& qy_arg,
    const double& qz_arg
) : px(px_arg),
    py(py_arg),
    pz(pz_arg),
    vx(vx_arg),
    vy(vy_arg),
    vz(vz_arg),
    qw(qw_arg),
    qx(qx_arg),
    qy(qy_arg),
    qz(qz_arg) {}

__lcm_buffer_size derivatives_t::encode(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const
{
    __lcm_buffer_size pos = 0, tlen;
    uint64_t hash = getHash();

    tlen = __uint64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

__lcm_buffer_size derivatives_t::decode(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen)
{
    __lcm_buffer_size pos = 0, thislen;

    uint64_t hash;
    thislen = __uint64_t_decode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

__lcm_buffer_size derivatives_t::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

constexpr uint64_t derivatives_t::getHash()
{
    return _computeHash(NULL);
}

constexpr derivatives_t::type_name_array_t* derivatives_t::getTypeNameArrayPtr() {
    return &"derivatives_t";
}

constexpr const char* derivatives_t::getTypeName()
{
    return *derivatives_t::getTypeNameArrayPtr();
}

constexpr derivatives_t::package_name_array_t* derivatives_t::getPackageNameArrayPtr() {
    return &"sym";
}

constexpr const char * derivatives_t::getPackageName()
{
    return *derivatives_t::getPackageNameArrayPtr();
}

__lcm_buffer_size derivatives_t::_encodeNoHash(void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen) const
{
    __lcm_buffer_size pos = 0, tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->px, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->py, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->pz, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->vx, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->vy, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->vz, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->qw, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->qx, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->qy, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_encode_array(buf, offset + pos, maxlen - pos, &this->qz, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

__lcm_buffer_size derivatives_t::_decodeNoHash(const void *buf, __lcm_buffer_size offset, __lcm_buffer_size maxlen)
{
    __lcm_buffer_size pos = 0, tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->px, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->py, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->pz, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->vx, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->vy, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->vz, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->qw, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->qx, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->qy, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __double_decode_array(buf, offset + pos, maxlen - pos, &this->qz, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    return pos;
}

__lcm_buffer_size derivatives_t::_getEncodedSizeNoHash() const
{
    __lcm_buffer_size enc_size = 0;
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    enc_size += __double_encoded_array_size(NULL, 1);
    return enc_size;
}

bool derivatives_t::operator==(const derivatives_t& other) const {
  return (
          (px==other.px) && 
          (py==other.py) && 
          (pz==other.pz) && 
          (vx==other.vx) && 
          (vy==other.vy) && 
          (vz==other.vz) && 
          (qw==other.qw) && 
          (qx==other.qx) && 
          (qy==other.qy) && 
          (qz==other.qz));
}

bool derivatives_t::operator!=(const derivatives_t& other) const {
  return !(*this==other);
}

}

#endif