//! eFMU container layout writer (eFMI ch. 2, GAL-021/023).
//!
//! Produces the two package forms of an eFMU:
//!
//! 1. **Directory form** ([`write_efmu_container`]): an eFMU root holding
//!    exactly `__content.xml`, `schemas/` (populated byte-identically from
//!    the vendored Beta-1 XSDs, BSD-3-Clause `LICENSE` included), and one
//!    tool-named container directory per model representation with its
//!    manifest at the container root.
//! 2. **Zip form** ([`write_efmu_zip`]): the directory form zipped with
//!    `__content.xml` at the zip root (no wrapper directory), extension
//!    `.efmu`.
//!
//! SHA-1 checksums recorded in `__content.xml` are computed at write time
//! from the exact manifest bytes being written — placeholder checksums are
//! unrepresentable — and every `File` entry inside each manifest is
//! cross-checked against the files actually being written: each listed file
//! must exist among them, `File/@checksum` entries must match the bytes, and
//! the registered `manifestRefId` must equal the `id` carried by the manifest
//! bytes themselves (GAL-021: a wrong checksum or dangling reference makes
//! the eFMU invalid). Cross-representation rules (unique
//! names, exactly one Algorithm Code container) are enforced by
//! [`Content::new`], which this module drives; layout-only rules (reserved
//! root names, path-safe components, duplicate files, non-empty output
//! directories) are enforced here. `activeFmu` is never emitted: this writer
//! never unpacks an FMU at the eFMU root, and the attribute must not be set
//! otherwise (eFMI ch. 2.3.6).

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};

use quick_xml::Reader;
use quick_xml::events::{BytesStart, Event};

use crate::checksum::Sha1Hex;
use crate::content::{Content, ContentParts, ModelRepresentation, ModelRepresentationKind};
use crate::diagnostic::EfmiError;
use crate::ids::{FilePath, ManifestId, NameWithoutSlashes, NormalizedText, UtcTimestamp};
use crate::manifest_common::ManifestAttributes;
use crate::xml::content_to_xml;

/// One embedded vendored schema file; `relative_path` is `/`-separated and
/// relative to the emitted `schemas/` directory. The `SCHEMA_ASSETS` static
/// is generated by `build.rs` from `assets/efmi-schemas/`.
struct SchemaAsset {
    relative_path: &'static str,
    bytes: &'static [u8],
}

include!(concat!(env!("OUT_DIR"), "/schema_assets.rs"));

/// Name of the container content description reserved at the eFMU root by
/// the standard (ch. 2): `__content.xml`. Every root entry other than this
/// and [`SCHEMAS_DIR_NAME`] is a tool-named representation container
/// directory. Public so packaging drivers can recognize an existing eFMU
/// root (e.g. to replace their own previous build product before calling
/// [`write_efmu_container`], which itself never overwrites).
pub const CONTENT_XML_NAME: &str = "__content.xml";
/// Reserved root directory holding the eFMI schema copies.
const SCHEMAS_DIR_NAME: &str = "schemas";

/// One non-manifest file of a model representation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RepresentationFile {
    /// Directory part relative to the container root (`./…/`), matching the
    /// manifest's `File/@path` value for this file.
    pub directory: FilePath,
    /// File name including suffix.
    pub name: NameWithoutSlashes,
    /// Exact bytes to write. Manifest `File/@checksum` entries with
    /// `needsChecksum="true"` must have been computed from these same bytes.
    pub bytes: Vec<u8>,
}

/// Everything needed to place one model representation container into an
/// eFMU: registry data for `__content.xml` plus the files to write.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ModelRepresentationFiles {
    /// Container name; doubles as the root directory name of the container.
    pub name: NameWithoutSlashes,
    /// Representation kind; exactly one [`ModelRepresentationKind::AlgorithmCode`]
    /// entry is required per eFMU.
    pub kind: ModelRepresentationKind,
    /// Manifest file name, written at the container's root.
    pub manifest_name: NameWithoutSlashes,
    /// The manifest's own UUID (its `id` attribute), registered as
    /// `manifestRefId` in `__content.xml`.
    pub manifest_ref_id: ManifestId,
    /// Exact serialized manifest bytes (e.g. from
    /// [`crate::xml::algorithm_code_manifest_to_xml`]). The SHA-1 recorded in
    /// `__content.xml` is computed from these bytes at write time; never
    /// re-serialize after checksumming.
    pub manifest_bytes: Vec<u8>,
    /// Further files of the representation (the `.alg` code file, ...).
    pub files: Vec<RepresentationFile>,
}

/// Top-level attributes of the eFMU itself, emitted on the `Content` root
/// element of `__content.xml`.
///
/// There is deliberately no `activeFmu` field: the attribute must not be set
/// unless the named representation's FMU is unpacked at the container root
/// (eFMI ch. 2.3.6), and this writer never unpacks an FMU — so a settable
/// field could only ever produce a standard-violating container. The
/// [`crate::content::ContentParts`] model keeps the attribute for producers
/// that do implement FMU activation.
#[derive(Debug, Clone, PartialEq)]
pub struct EfmuMeta {
    /// Shared manifest attribute group of `__content.xml`.
    pub attributes: ManifestAttributes,
}

impl EfmuMeta {
    /// Metadata for a freshly generated eFMU: a fresh manifest UUID, the
    /// current wall-clock UTC time, and the generating tool's name/version
    /// (e.g. `"rumoca 0.9.9"`). The id and timestamp are minted here — the
    /// documented per-build nondeterminism of a generated container — while
    /// serialization itself stays a pure function of the returned value.
    pub fn generated(name: &str, generation_tool: &str) -> Result<Self, EfmiError> {
        Ok(Self {
            attributes: ManifestAttributes {
                id: ManifestId::generate(),
                name: NormalizedText::new(name)?,
                description: None,
                version: None,
                generation_date_and_time: UtcTimestamp::now_utc(),
                generation_tool: Some(NormalizedText::new(generation_tool)?),
                copyright: None,
                license: None,
            },
        })
    }
}

/// Where one representation landed on disk.
#[derive(Debug, Clone, PartialEq)]
pub struct WrittenRepresentation {
    /// Container name (= directory name under the eFMU root).
    pub name: NameWithoutSlashes,
    /// Absolute path of the container directory.
    pub directory: PathBuf,
    /// Absolute path of the written manifest file.
    pub manifest_path: PathBuf,
    /// SHA-1 of the written manifest bytes, as recorded in `__content.xml`.
    pub manifest_checksum: Sha1Hex,
}

/// The written eFMU directory layout returned by [`write_efmu_container`].
#[derive(Debug, Clone, PartialEq)]
pub struct EfmuLayout {
    /// The eFMU root directory.
    pub root: PathBuf,
    /// Absolute path of `__content.xml`.
    pub content_xml: PathBuf,
    /// Absolute path of the `schemas/` directory.
    pub schemas_dir: PathBuf,
    /// One entry per written model representation, in input order.
    pub representations: Vec<WrittenRepresentation>,
}

/// Write an eFMU in directory form (eFMI ch. 2 package format 1).
///
/// `out_dir` becomes the eFMU root and must not exist yet (or be an empty
/// directory): stale files are never silently mixed into a container. The
/// root receives exactly `__content.xml`, `schemas/`, and one directory per
/// entry of `representations`. All validation — including the
/// exactly-one-Algorithm-Code rule via [`Content::new`] — runs before
/// anything is written.
pub fn write_efmu_container(
    representations: &[ModelRepresentationFiles],
    meta: &EfmuMeta,
    out_dir: &Path,
) -> Result<EfmuLayout, EfmiError> {
    for representation in representations {
        validate_representation_layout(representation)?;
        verify_manifest_consistency(representation)?;
    }
    let checksums: Vec<Sha1Hex> = representations
        .iter()
        .map(|r| Sha1Hex::of_bytes(&r.manifest_bytes))
        .collect();
    let content = build_content(representations, &checksums, meta)?;
    let content_bytes = content_to_xml(&content)?;

    let created_root = prepare_root(out_dir)?;
    write_layout(representations, checksums, &content_bytes, out_dir)
        .inspect_err(|_| cleanup_failed_write(out_dir, created_root))
}

/// Write phase of [`write_efmu_container`]: all validation has passed and the
/// root exists and is empty; place every file.
fn write_layout(
    representations: &[ModelRepresentationFiles],
    checksums: Vec<Sha1Hex>,
    content_bytes: &[u8],
    out_dir: &Path,
) -> Result<EfmuLayout, EfmiError> {
    let schemas_dir = write_schemas(out_dir)?;
    let mut written = Vec::with_capacity(representations.len());
    for (representation, checksum) in representations.iter().zip(checksums) {
        written.push(write_representation(out_dir, representation, checksum)?);
    }
    let content_xml = out_dir.join(CONTENT_XML_NAME);
    write_file(&content_xml, content_bytes)?;
    Ok(EfmuLayout {
        root: out_dir.to_path_buf(),
        content_xml,
        schemas_dir,
        representations: written,
    })
}

/// Best-effort removal of a partially written eFMU root after a mid-write
/// I/O failure, so a retry does not hit [`EfmiError::OutputDirNotEmpty`] over
/// half-written state. Cleanup failures are deliberately ignored: the
/// original write error is the actionable diagnostic.
fn cleanup_failed_write(out_dir: &Path, created_root: bool) {
    if created_root {
        let _ = fs::remove_dir_all(out_dir);
        return;
    }
    // The (empty) root pre-existed and belongs to the caller: remove only
    // the entries this writer created inside it.
    let Ok(entries) = fs::read_dir(out_dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let _ = if path.is_dir() {
            fs::remove_dir_all(&path)
        } else {
            fs::remove_file(&path)
        };
    }
}

/// Zip an eFMU directory (as produced by [`write_efmu_container`]) into a
/// `.efmu` archive (eFMI ch. 2 package format 2): `__content.xml` sits at the
/// zip root, with no wrapper directory. Entries are written in sorted path
/// order with a fixed timestamp, so the archive is a pure function of the
/// directory contents.
pub fn write_efmu_zip(efmu_root: &Path, zip_path: &Path) -> Result<(), EfmiError> {
    if zip_path.extension().and_then(|e| e.to_str()) != Some("efmu") {
        return Err(EfmiError::InvalidContainerLayout {
            item: zip_path.display().to_string(),
            reason: "eFMU zip archives must use the `.efmu` extension".to_owned(),
        });
    }
    if !efmu_root.join(CONTENT_XML_NAME).is_file() {
        return Err(EfmiError::InvalidContainerLayout {
            item: efmu_root.display().to_string(),
            reason: format!("not an eFMU root: `{CONTENT_XML_NAME}` is missing"),
        });
    }
    let mut relative_paths = Vec::new();
    collect_files(efmu_root, efmu_root, &mut relative_paths)?;
    relative_paths.sort();
    write_zip_entries(efmu_root, zip_path, &relative_paths)
}

/// Layout rules for one representation that `Content` validation cannot see:
/// reserved root names and per-representation duplicate target paths.
fn validate_representation_layout(
    representation: &ModelRepresentationFiles,
) -> Result<(), EfmiError> {
    validate_component(representation.name.as_str())?;
    if matches!(
        representation.name.as_str(),
        SCHEMAS_DIR_NAME | CONTENT_XML_NAME
    ) {
        return Err(EfmiError::InvalidContainerLayout {
            item: representation.name.as_str().to_owned(),
            reason: format!(
                "representation names `{SCHEMAS_DIR_NAME}` and `{CONTENT_XML_NAME}` \
                 are reserved at the eFMU root"
            ),
        });
    }
    validate_component(representation.manifest_name.as_str())?;
    let mut paths = BTreeSet::new();
    paths.insert(format!("./{}", representation.manifest_name.as_str()));
    for file in &representation.files {
        validate_component(file.name.as_str())?;
        for segment in file.directory.as_str().split_terminator('/').skip(1) {
            validate_component(segment)?;
        }
        let path = format!("{}{}", file.directory.as_str(), file.name.as_str());
        if !paths.insert(path.clone()) {
            return Err(EfmiError::DuplicateContainerFile {
                representation: representation.name.as_str().to_owned(),
                path,
            });
        }
    }
    Ok(())
}

/// A single path component must stay inside its directory on every platform:
/// no `.`/`..`, no backslashes (Windows separators).
fn validate_component(component: &str) -> Result<(), EfmiError> {
    if component == "." || component == ".." || component.contains('\\') {
        return Err(EfmiError::InvalidContainerLayout {
            item: component.to_owned(),
            reason: "path components must not be `.`/`..` or contain `\\`".to_owned(),
        });
    }
    Ok(())
}

/// One `File` entry parsed back out of serialized manifest bytes (the shared
/// `efmiFiles.xsd` shape used by every manifest kind).
struct ManifestFileEntry {
    /// `path` attribute (`./…/`, container-root relative).
    path: String,
    /// `name` attribute (file name including suffix).
    name: String,
    /// `checksum` attribute; `Some` iff `needsChecksum="true"`.
    checksum: Option<String>,
}

/// GAL-021 write-time gate over the caller-supplied manifest bytes:
///
/// - the manifest's own `id` must equal the registered `manifest_ref_id`
///   (otherwise `__content.xml` would carry a dangling `manifestRefId`);
/// - every `File` entry must name a file this writer is about to place
///   (`needsChecksum="false"` entries included — an unwritten listed file is
///   a dangling reference regardless of checksumming);
/// - every `File/@checksum` must equal the SHA-1 of the bytes being written
///   at that path (eFMI ch. 2.3.5: a wrong checksum makes the eFMU invalid).
fn verify_manifest_consistency(representation: &ModelRepresentationFiles) -> Result<(), EfmiError> {
    let parsed =
        parse_manifest_bytes(&representation.manifest_bytes, representation.name.as_str())?;
    verify_manifest_ref_id(representation, parsed.root_id.as_deref())?;
    verify_manifest_file_entries(representation, parsed.files)
}

/// Extract the manifest's own UUID — the root element's `id` attribute — from
/// serialized manifest bytes.
///
/// This is how a packaging driver obtains the `manifest_ref_id` to register
/// in `__content.xml` for manifest bytes it did not serialize itself (e.g. a
/// manifest rendered earlier in the same build): parsing the id back out of
/// the exact bytes being packaged, instead of re-serializing, keeps the
/// registered `manifestRefId`, the recorded SHA-1, and the written file all
/// derived from one byte sequence (GAL-021). Bytes that are not well-formed
/// XML or whose root element carries no valid brace-wrapped UUID `id` are
/// rejected — such a manifest can never be part of a valid eFMU.
pub fn manifest_root_id(manifest_bytes: &[u8]) -> Result<ManifestId, EfmiError> {
    const ITEM: &str = "manifest bytes";
    let parsed = parse_manifest_bytes(manifest_bytes, ITEM)?;
    let Some(id) = parsed.root_id else {
        return Err(EfmiError::InvalidContainerLayout {
            item: ITEM.to_owned(),
            reason: "manifest root element has no `id` attribute".to_owned(),
        });
    };
    ManifestId::parse(&id)
}

/// The `id` inside the manifest bytes must be the registered
/// `manifest_ref_id`; a manifest without a root `id` can never be
/// schema-valid and is rejected outright.
fn verify_manifest_ref_id(
    representation: &ModelRepresentationFiles,
    root_id: Option<&str>,
) -> Result<(), EfmiError> {
    let Some(found) = root_id else {
        return Err(EfmiError::InvalidContainerLayout {
            item: representation.name.as_str().to_owned(),
            reason: "manifest root element has no `id` attribute".to_owned(),
        });
    };
    let found = ManifestId::parse(found)?;
    if found != representation.manifest_ref_id {
        return Err(EfmiError::ManifestRefIdMismatch {
            representation: representation.name.as_str().to_owned(),
            registered: representation.manifest_ref_id.to_string(),
            found: found.to_string(),
        });
    }
    Ok(())
}

/// Existence + checksum verification of parsed manifest `File` entries
/// against the bytes actually being written.
fn verify_manifest_file_entries(
    representation: &ModelRepresentationFiles,
    entries: Vec<ManifestFileEntry>,
) -> Result<(), EfmiError> {
    let written = written_bytes_by_path(representation);
    for entry in entries {
        let path = format!("{}{}", entry.path, entry.name);
        let Some(bytes) = written.get(&(entry.path, entry.name)) else {
            return Err(EfmiError::ManifestFileMissing {
                representation: representation.name.as_str().to_owned(),
                path,
            });
        };
        let Some(listed) = entry.checksum else {
            continue;
        };
        let computed = Sha1Hex::of_bytes(bytes);
        if computed.as_str() != listed {
            return Err(EfmiError::StaleFileChecksum {
                representation: representation.name.as_str().to_owned(),
                path,
                listed,
                computed: computed.as_str().to_owned(),
            });
        }
    }
    Ok(())
}

/// The exact bytes this writer will place at each `(path, name)` of the
/// representation container: the manifest itself plus every representation
/// file.
fn written_bytes_by_path(
    representation: &ModelRepresentationFiles,
) -> BTreeMap<(String, String), &[u8]> {
    let mut written: BTreeMap<(String, String), &[u8]> = BTreeMap::new();
    written.insert(
        (
            FilePath::root().as_str().to_owned(),
            representation.manifest_name.as_str().to_owned(),
        ),
        representation.manifest_bytes.as_slice(),
    );
    for file in &representation.files {
        written.insert(
            (
                file.directory.as_str().to_owned(),
                file.name.as_str().to_owned(),
            ),
            file.bytes.as_slice(),
        );
    }
    written
}

/// What the write-time gate needs out of caller-supplied manifest bytes: the
/// root element's `id` attribute and every `File` entry.
struct ParsedManifest {
    /// `id` attribute of the root element, if present.
    root_id: Option<String>,
    /// All `File` entries in document order.
    files: Vec<ManifestFileEntry>,
}

/// Parse the root `id` and the `File` entries out of the caller-supplied
/// manifest bytes (`item` labels the source in errors). Manifest bytes that
/// are not well-formed XML (or whose `File` entries lack the required
/// attributes) can never be part of a valid eFMU and are rejected before
/// anything is written.
fn parse_manifest_bytes(manifest_bytes: &[u8], item: &str) -> Result<ParsedManifest, EfmiError> {
    let malformed = |reason: String| EfmiError::InvalidContainerLayout {
        item: item.to_owned(),
        reason,
    };
    let mut reader = Reader::from_reader(manifest_bytes);
    let mut parsed = ParsedManifest {
        root_id: None,
        files: Vec::new(),
    };
    let mut buf = Vec::new();
    let mut root_seen = false;
    // quick-xml returns a plain Eof for input truncated inside an element,
    // so open elements are counted explicitly to reject such manifests.
    let mut depth: usize = 0;
    loop {
        match reader.read_event_into(&mut buf) {
            Err(error) => {
                return Err(malformed(format!(
                    "manifest bytes are not well-formed XML: {error}"
                )));
            }
            Ok(Event::Eof) => {
                if depth != 0 {
                    return Err(malformed(
                        "manifest bytes are not well-formed XML: \
                         input ends with unclosed elements"
                            .to_owned(),
                    ));
                }
                break;
            }
            Ok(Event::Start(element)) => {
                if depth == 0 && !root_seen {
                    root_seen = true;
                    parsed.root_id = attribute_map(&element).map_err(malformed)?.remove("id");
                }
                depth += 1;
                if element.name().as_ref() == b"File" {
                    parsed
                        .files
                        .push(parse_file_entry(&element).map_err(malformed)?);
                }
            }
            Ok(Event::End(_)) => {
                depth = depth.checked_sub(1).ok_or_else(|| {
                    malformed(
                        "manifest bytes are not well-formed XML: unmatched end tag".to_owned(),
                    )
                })?;
            }
            Ok(Event::Empty(element)) => {
                if depth == 0 && !root_seen {
                    root_seen = true;
                    parsed.root_id = attribute_map(&element).map_err(malformed)?.remove("id");
                }
                if element.name().as_ref() == b"File" {
                    parsed
                        .files
                        .push(parse_file_entry(&element).map_err(malformed)?);
                }
            }
            Ok(_) => {}
        }
        buf.clear();
    }
    Ok(parsed)
}

/// Decode all attributes of one element into an owned map.
fn attribute_map(element: &BytesStart<'_>) -> Result<BTreeMap<String, String>, String> {
    let mut attributes: BTreeMap<String, String> = BTreeMap::new();
    for attribute in element.attributes() {
        let attribute = attribute.map_err(|e| format!("malformed attribute: {e}"))?;
        let key = std::str::from_utf8(attribute.key.as_ref())
            .map_err(|e| format!("non-UTF-8 attribute name: {e}"))?
            .to_owned();
        let value = attribute
            .unescape_value()
            .map_err(|e| format!("unescapable attribute value: {e}"))?
            .into_owned();
        attributes.insert(key, value);
    }
    Ok(attributes)
}

/// Extract `(path, name, checksum-if-needed)` from one manifest `File`
/// element, enforcing the `needsChecksum`/`checksum` coupling of
/// `efmiFiles.xsd`.
fn parse_file_entry(element: &BytesStart<'_>) -> Result<ManifestFileEntry, String> {
    let attributes = attribute_map(element)?;
    let required = |name: &str| {
        attributes
            .get(name)
            .cloned()
            .ok_or_else(|| format!("manifest File entry is missing required attribute `{name}`"))
    };
    let path = required("path")?;
    let name = required("name")?;
    // xs:boolean lexical space: true/false/1/0.
    let checksum = match required("needsChecksum")?.as_str() {
        "true" | "1" => Some(required("checksum")?),
        "false" | "0" => None,
        other => {
            return Err(format!(
                "manifest File `{path}{name}` has invalid needsChecksum value `{other}`"
            ));
        }
    };
    Ok(ManifestFileEntry {
        path,
        name,
        checksum,
    })
}

/// Assemble and validate the `__content.xml` model; checksums are the real
/// digests of the manifest bytes about to be written (GAL-021).
fn build_content(
    representations: &[ModelRepresentationFiles],
    checksums: &[Sha1Hex],
    meta: &EfmuMeta,
) -> Result<Content, EfmiError> {
    let model_representations = representations
        .iter()
        .zip(checksums)
        .map(|(representation, checksum)| ModelRepresentation {
            name: representation.name.clone(),
            kind: representation.kind,
            manifest: representation.manifest_name.clone(),
            checksum: checksum.clone(),
            manifest_ref_id: representation.manifest_ref_id,
        })
        .collect();
    Content::new(ContentParts {
        attributes: meta.attributes.clone(),
        // Never set: this writer does not unpack an FMU at the eFMU root
        // (see [`EfmuMeta`]).
        active_fmu: None,
        model_representations,
    })
}

/// Create the eFMU root; an existing non-empty directory (or a non-directory)
/// is rejected instead of being overwritten. Returns whether this call
/// created the root (it then owns the directory for error cleanup).
fn prepare_root(out_dir: &Path) -> Result<bool, EfmiError> {
    if !out_dir.exists() {
        create_dir(out_dir)?;
        return Ok(true);
    }
    if !out_dir.is_dir() {
        return Err(EfmiError::InvalidContainerLayout {
            item: out_dir.display().to_string(),
            reason: "output path exists and is not a directory".to_owned(),
        });
    }
    let mut entries = fs::read_dir(out_dir).map_err(|e| io_error(out_dir, &e))?;
    if entries.next().is_some() {
        return Err(EfmiError::OutputDirNotEmpty {
            path: out_dir.display().to_string(),
        });
    }
    Ok(false)
}

/// Populate `schemas/` from the embedded vendored asset tree, byte-identical
/// (GAL-023; the BSD-3-Clause `LICENSE` travels with every copy).
fn write_schemas(out_dir: &Path) -> Result<PathBuf, EfmiError> {
    let schemas_dir = out_dir.join(SCHEMAS_DIR_NAME);
    for asset in SCHEMA_ASSETS {
        let mut target = schemas_dir.clone();
        for segment in asset.relative_path.split('/') {
            target.push(segment);
        }
        write_file(&target, asset.bytes)?;
    }
    Ok(schemas_dir)
}

fn write_representation(
    out_dir: &Path,
    representation: &ModelRepresentationFiles,
    manifest_checksum: Sha1Hex,
) -> Result<WrittenRepresentation, EfmiError> {
    let directory = out_dir.join(representation.name.as_str());
    let manifest_path = directory.join(representation.manifest_name.as_str());
    write_file(&manifest_path, &representation.manifest_bytes)?;
    for file in &representation.files {
        let mut target = directory.clone();
        for segment in file.directory.as_str().split_terminator('/').skip(1) {
            target.push(segment);
        }
        target.push(file.name.as_str());
        write_file(&target, &file.bytes)?;
    }
    Ok(WrittenRepresentation {
        name: representation.name.clone(),
        directory,
        manifest_path,
        manifest_checksum,
    })
}

fn create_dir(dir: &Path) -> Result<(), EfmiError> {
    fs::create_dir_all(dir).map_err(|e| io_error(dir, &e))
}

fn write_file(path: &Path, bytes: &[u8]) -> Result<(), EfmiError> {
    let parent = path
        .parent()
        .expect("container file paths always have a parent");
    create_dir(parent)?;
    fs::write(path, bytes).map_err(|e| io_error(path, &e))
}

fn io_error(path: &Path, error: &std::io::Error) -> EfmiError {
    EfmiError::Io {
        path: path.display().to_string(),
        message: error.to_string(),
    }
}

/// Recursively collect files under `dir` as `/`-separated zip entry names
/// relative to `root`.
///
/// The walk is defensive because `dir` is caller-supplied, not necessarily a
/// [`write_efmu_container`] product: symlinks are rejected (a directory
/// symlink could cycle the walk; a file symlink would zip foreign content)
/// and non-UTF-8 file names are rejected (zip entry names are strings, and a
/// lossy conversion would point at a path that does not exist).
fn collect_files(root: &Path, dir: &Path, out: &mut Vec<String>) -> Result<(), EfmiError> {
    let entries = fs::read_dir(dir).map_err(|e| io_error(dir, &e))?;
    for entry in entries {
        let entry = entry.map_err(|e| io_error(dir, &e))?;
        let path = entry.path();
        // `DirEntry::file_type` does not follow symlinks, unlike `Path::is_dir`.
        let file_type = entry.file_type().map_err(|e| io_error(&path, &e))?;
        if file_type.is_symlink() {
            return Err(EfmiError::InvalidContainerLayout {
                item: path.display().to_string(),
                reason: "symlinks are not supported inside an eFMU tree".to_owned(),
            });
        }
        if file_type.is_dir() {
            collect_files(root, &path, out)?;
            continue;
        }
        out.push(relative_entry_name(root, &path)?);
    }
    Ok(())
}

/// Render `path` relative to `root` as a `/`-separated UTF-8 zip entry name.
fn relative_entry_name(root: &Path, path: &Path) -> Result<String, EfmiError> {
    let mut segments = Vec::new();
    for component in path
        .strip_prefix(root)
        .expect("walked path is under the walk root")
        .components()
    {
        let Some(segment) = component.as_os_str().to_str() else {
            return Err(EfmiError::InvalidContainerLayout {
                item: path.display().to_string(),
                reason: "file names inside an eFMU tree must be valid UTF-8".to_owned(),
            });
        };
        segments.push(segment);
    }
    Ok(segments.join("/"))
}

/// Write the archive to a staging path beside `zip_path` and rename it into
/// place on success. `fs::File::create` truncates immediately, so writing
/// straight to the final path would leave a corrupt `.efmu` behind — and
/// destroy a previous run's valid archive — if reading a source file or
/// writing an entry fails partway; the staging file is removed on error
/// instead (mirroring the directory form's `cleanup_failed_write`).
fn write_zip_entries(
    efmu_root: &Path,
    zip_path: &Path,
    relative_paths: &[String],
) -> Result<(), EfmiError> {
    let mut staging_name = zip_path
        .file_name()
        .expect("zip path ends in `.efmu`, so it has a file name")
        .to_os_string();
    staging_name.push(".part");
    let staging_path = zip_path.with_file_name(staging_name);
    write_zip_archive(efmu_root, zip_path, &staging_path, relative_paths).inspect_err(|_| {
        let _ = fs::remove_file(&staging_path);
    })?;
    // Renaming over an existing file replaces it on Unix but fails on
    // Windows, so a previous archive is removed first — only now that the
    // staged replacement is complete.
    if zip_path.exists() {
        fs::remove_file(zip_path).map_err(|e| io_error(zip_path, &e))?;
    }
    fs::rename(&staging_path, zip_path).map_err(|e| io_error(zip_path, &e))
}

/// Write every entry into the staged archive at `staging_path`; zip-level
/// errors name the final `zip_path` (the artifact being produced).
fn write_zip_archive(
    efmu_root: &Path,
    zip_path: &Path,
    staging_path: &Path,
    relative_paths: &[String],
) -> Result<(), EfmiError> {
    let zip_error = |message: String| EfmiError::Zip {
        path: zip_path.display().to_string(),
        message,
    };
    let file = fs::File::create(staging_path).map_err(|e| io_error(staging_path, &e))?;
    let mut zip = zip::ZipWriter::new(file);
    // Fixed timestamp + permissions: the archive is a pure function of the
    // directory contents, so repeated packaging is byte-reproducible.
    let options = zip::write::SimpleFileOptions::default()
        .compression_method(zip::CompressionMethod::Deflated)
        .last_modified_time(zip::DateTime::default())
        .unix_permissions(0o644);
    for relative in relative_paths {
        let source: PathBuf = efmu_root.join(relative.replace('/', std::path::MAIN_SEPARATOR_STR));
        let bytes = fs::read(&source).map_err(|e| io_error(&source, &e))?;
        zip.start_file(relative, options)
            .map_err(|e| zip_error(e.to_string()))?;
        zip.write_all(&bytes)
            .map_err(|e| zip_error(e.to_string()))?;
    }
    zip.finish().map_err(|e| zip_error(e.to_string()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use crate::ids::{NormalizedText, UtcTimestamp};

    /// The embedded asset list must mirror `assets/efmi-schemas/` exactly
    /// (minus the repository-only `README.md`), byte for byte — catching both
    /// build-script drift and accidental asset edits.
    #[test]
    fn embedded_assets_match_vendored_tree() {
        let assets_dir = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("assets")
            .join("efmi-schemas");
        let mut on_disk = Vec::new();
        collect_files(&assets_dir, &assets_dir, &mut on_disk).unwrap();
        on_disk.retain(|p| p != "README.md");
        on_disk.sort();

        let embedded: Vec<String> = SCHEMA_ASSETS
            .iter()
            .map(|a| a.relative_path.to_owned())
            .collect();
        assert_eq!(embedded, on_disk, "embedded asset list drifted from disk");
        assert!(
            embedded.contains(&"LICENSE".to_owned()),
            "LICENSE must travel with every schemas/ copy (GAL-023)"
        );
        let by_path: BTreeMap<&str, &[u8]> = SCHEMA_ASSETS
            .iter()
            .map(|a| (a.relative_path, a.bytes))
            .collect();
        for relative in &on_disk {
            let disk_path = assets_dir.join(relative.replace('/', std::path::MAIN_SEPARATOR_STR));
            let disk_bytes = fs::read(&disk_path).unwrap();
            assert_eq!(
                by_path[relative.as_str()],
                disk_bytes.as_slice(),
                "embedded bytes differ from disk for {relative}"
            );
        }
    }

    fn meta() -> EfmuMeta {
        EfmuMeta {
            attributes: ManifestAttributes {
                id: ManifestId::parse("{2f1a03de-9f14-4a3d-8b1e-73c60d0a1c11}").unwrap(),
                name: NormalizedText::new("TestBlock").unwrap(),
                description: None,
                version: None,
                generation_date_and_time: UtcTimestamp::parse("2026-07-02T12:00:00Z").unwrap(),
                generation_tool: None,
                copyright: None,
                license: None,
            },
        }
    }

    /// The manifest UUID used by [`representation`], matching both the
    /// `manifest_ref_id` registration and the `id` inside the manifest bytes.
    const REP_UUID: &str = "{7d6b1a52-4f0e-4d59-9d3b-215f8e5b6a20}";

    fn representation(name: &str) -> ModelRepresentationFiles {
        ModelRepresentationFiles {
            name: NameWithoutSlashes::new(name).unwrap(),
            kind: ModelRepresentationKind::AlgorithmCode,
            manifest_name: NameWithoutSlashes::new("manifest.xml").unwrap(),
            manifest_ref_id: ManifestId::parse(REP_UUID).unwrap(),
            manifest_bytes: format!("<Manifest id=\"{REP_UUID}\"/>").into_bytes(),
            files: vec![],
        }
    }

    /// [`manifest_root_id`] recovers the exact registered UUID from manifest
    /// bytes and rejects bytes that could never be schema-valid.
    #[test]
    fn manifest_root_id_extracts_registered_uuid() {
        let rep = representation("AlgorithmCode");
        let id = manifest_root_id(&rep.manifest_bytes).expect("root id must parse");
        assert_eq!(id, ManifestId::parse(REP_UUID).unwrap());

        // Missing root id: never schema-valid.
        let err = manifest_root_id(b"<Manifest/>").unwrap_err();
        assert_eq!(err.code(), "EFM026");
        // Malformed UUID: rejected by the ManifestId parser.
        let err = manifest_root_id(b"<Manifest id=\"not-a-uuid\"/>").unwrap_err();
        assert_eq!(err.code(), "EFM001");
        // Not XML at all.
        let err = manifest_root_id(b"plain text").unwrap_err();
        assert_eq!(err.code(), "EFM026");
    }

    /// [`EfmuMeta::generated`] mints a fresh id/timestamp and carries the
    /// tool string; invalid tool text fails loudly instead of defaulting.
    #[test]
    fn efmu_meta_generated_mints_valid_identity() {
        let meta = EfmuMeta::generated("TestBlock", "rumoca 0.0.0-test").unwrap();
        // Round-trip through the strict parsers: both values are valid.
        ManifestId::parse(&meta.attributes.id.to_string()).unwrap();
        UtcTimestamp::parse(&meta.attributes.generation_date_and_time.to_string()).unwrap();
        assert_eq!(meta.attributes.name.as_str(), "TestBlock");
        assert_eq!(
            meta.attributes.generation_tool.as_ref().unwrap().as_str(),
            "rumoca 0.0.0-test"
        );
        // Two mints differ (fresh UUID per container).
        let other = EfmuMeta::generated("TestBlock", "rumoca 0.0.0-test").unwrap();
        assert_ne!(meta.attributes.id, other.attributes.id);

        let err = EfmuMeta::generated("TestBlock", "bad\ntool").unwrap_err();
        assert_eq!(err.code(), "EFM004");
    }

    #[test]
    fn reserved_root_names_rejected() {
        for name in [SCHEMAS_DIR_NAME, CONTENT_XML_NAME] {
            let err = write_efmu_container(
                &[representation(name)],
                &meta(),
                Path::new("/nonexistent/never-created"),
            )
            .unwrap_err();
            assert_eq!(err.code(), "EFM026", "reserved name {name}");
        }
    }

    /// `.`/`..` pass `NameWithoutSlashes` but must never become directory
    /// names; backslashes are already unrepresentable in the name newtypes.
    #[test]
    fn unsafe_path_components_rejected() {
        for name in ["..", "."] {
            let err = write_efmu_container(
                &[representation(name)],
                &meta(),
                Path::new("/nonexistent/never-created"),
            )
            .unwrap_err();
            assert_eq!(err.code(), "EFM026", "unsafe component {name}");
        }
        // Defense in depth: the layer below the newtypes still rejects `\`.
        assert_eq!(
            validate_component("a\\b").unwrap_err().code(),
            "EFM026",
            "backslash component"
        );
    }

    #[test]
    fn duplicate_file_targets_rejected() {
        let mut rep = representation("AlgorithmCode");
        let file = RepresentationFile {
            directory: FilePath::root(),
            name: NameWithoutSlashes::new("Model.alg").unwrap(),
            bytes: b"x\n".to_vec(),
        };
        rep.files = vec![file.clone(), file];
        let err = write_efmu_container(
            std::slice::from_ref(&rep),
            &meta(),
            Path::new("/nonexistent/never-created"),
        )
        .unwrap_err();
        assert_eq!(
            err,
            EfmiError::DuplicateContainerFile {
                representation: "AlgorithmCode".into(),
                path: "./Model.alg".into(),
            }
        );

        // A file colliding with the manifest itself is also a duplicate.
        rep.files = vec![RepresentationFile {
            directory: FilePath::root(),
            name: NameWithoutSlashes::new("manifest.xml").unwrap(),
            bytes: b"x\n".to_vec(),
        }];
        let err = write_efmu_container(&[rep], &meta(), Path::new("/nonexistent/never-created"))
            .unwrap_err();
        assert_eq!(err.code(), "EFM027");
    }

    #[test]
    fn zip_requires_efmu_extension_and_content_xml() {
        let dir = tempfile::tempdir().unwrap();
        let err = write_efmu_zip(dir.path(), &dir.path().join("out.zip")).unwrap_err();
        assert_eq!(err.code(), "EFM026");
        let err = write_efmu_zip(dir.path(), &dir.path().join("out.efmu")).unwrap_err();
        assert_eq!(err.code(), "EFM026"); // no __content.xml in the source dir
    }

    /// Hand-authored minimal manifest whose single checksummed `File` entry
    /// matches `body` — nothing copied from the eFMI Standard.
    fn manifest_listing(body: &[u8]) -> Vec<u8> {
        format!(
            "<Manifest id=\"{REP_UUID}\"><Files><File id=\"F\" name=\"Model.alg\" path=\"./\" \
             needsChecksum=\"true\" checksum=\"{}\" role=\"Code\"/></Files></Manifest>",
            Sha1Hex::of_bytes(body).as_str()
        )
        .into_bytes()
    }

    /// GAL-021: a manifest whose `File/@checksum` does not match the bytes
    /// being written is rejected before anything lands on disk.
    #[test]
    fn stale_manifest_file_checksum_rejected() {
        let mut rep = representation("AlgorithmCode");
        rep.manifest_bytes = manifest_listing(b"original\n");
        rep.files = vec![RepresentationFile {
            directory: FilePath::root(),
            name: NameWithoutSlashes::new("Model.alg").unwrap(),
            bytes: b"edited after manifest serialization\n".to_vec(),
        }];
        let err = write_efmu_container(
            std::slice::from_ref(&rep),
            &meta(),
            Path::new("/nonexistent/never-created"),
        )
        .unwrap_err();
        assert_eq!(err.code(), "EFM036", "stale checksum must be rejected");

        // Matching bytes validate (write still fails later only if the
        // target path is unusable, so use a real tempdir).
        rep.files[0].bytes = b"original\n".to_vec();
        let dir = tempfile::tempdir().unwrap();
        write_efmu_container(&[rep], &meta(), &dir.path().join("efmu"))
            .expect("matching checksums must pass");
    }

    /// A checksummed file listed in the manifest but not written at all is
    /// also an invalid eFMU in the making.
    #[test]
    fn manifest_listed_checksummed_file_must_be_written() {
        let mut rep = representation("AlgorithmCode");
        rep.manifest_bytes = manifest_listing(b"original\n");
        rep.files = vec![];
        let err = write_efmu_container(&[rep], &meta(), Path::new("/nonexistent/never-created"))
            .unwrap_err();
        assert_eq!(err.code(), "EFM035");
    }

    /// A `needsChecksum="false"` entry that names an unwritten file is just
    /// as dangling as a checksummed one and must be rejected too.
    #[test]
    fn manifest_listed_unchecksummed_file_must_be_written() {
        let mut rep = representation("AlgorithmCode");
        rep.manifest_bytes = format!(
            "<Manifest id=\"{REP_UUID}\"><Files><File id=\"F\" name=\"Model.alg\" \
             path=\"./\" needsChecksum=\"false\" role=\"Code\"/></Files></Manifest>"
        )
        .into_bytes();
        rep.files = vec![];
        let err = write_efmu_container(&[rep], &meta(), Path::new("/nonexistent/never-created"))
            .unwrap_err();
        assert_eq!(
            err,
            EfmiError::ManifestFileMissing {
                representation: "AlgorithmCode".into(),
                path: "./Model.alg".into(),
            }
        );
    }

    /// The registered `manifest_ref_id` must equal the `id` inside the
    /// manifest bytes; a manifest regenerated with a fresh id but a stale
    /// registration would otherwise yield a dangling `manifestRefId`.
    #[test]
    fn manifest_ref_id_mismatch_rejected() {
        let mut rep = representation("AlgorithmCode");
        rep.manifest_bytes = b"<Manifest id=\"{aa6b1a52-4f0e-4d59-9d3b-215f8e5b6a21}\"/>".to_vec();
        let err = write_efmu_container(
            std::slice::from_ref(&rep),
            &meta(),
            Path::new("/nonexistent/never-created"),
        )
        .unwrap_err();
        assert_eq!(err.code(), "EFM038", "mismatched id must be rejected");

        // A manifest without any root id can never be schema-valid.
        rep.manifest_bytes = b"<Manifest/>".to_vec();
        let err = write_efmu_container(&[rep], &meta(), Path::new("/nonexistent/never-created"))
            .unwrap_err();
        assert_eq!(err.code(), "EFM026", "missing id must be rejected");
    }

    /// Manifest bytes that are not well-formed XML cannot be cross-checked
    /// (or be part of a valid eFMU) and are rejected up front.
    #[test]
    fn malformed_manifest_bytes_rejected() {
        let mut rep = representation("AlgorithmCode");
        rep.manifest_bytes = b"<Manifest><Files>".to_vec();
        let err = write_efmu_container(&[rep], &meta(), Path::new("/nonexistent/never-created"))
            .unwrap_err();
        assert_eq!(err.code(), "EFM026");
    }

    /// Symlinks under a caller-supplied zip source are rejected instead of
    /// being followed (cycle risk) or zipped as foreign content.
    #[cfg(unix)]
    #[test]
    fn zip_source_symlinks_rejected() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("__content.xml"), b"<Content/>").unwrap();
        std::os::unix::fs::symlink(dir.path().join("__content.xml"), dir.path().join("link"))
            .unwrap();
        let err = write_efmu_zip(dir.path(), &dir.path().join("out.efmu")).unwrap_err();
        assert_eq!(err.code(), "EFM026");
        let err_text = err.to_string();
        assert!(err_text.contains("symlink"), "got: {err_text}");
    }

    /// Non-UTF-8 file names under a caller-supplied zip source fail with a
    /// typed error, not a mangled replacement-character path.
    #[cfg(unix)]
    #[test]
    fn zip_source_non_utf8_names_rejected() {
        use std::ffi::OsStr;
        use std::os::unix::ffi::OsStrExt;
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("__content.xml"), b"<Content/>").unwrap();
        fs::write(dir.path().join(OsStr::from_bytes(b"bad\xFFname")), b"x").unwrap();
        let err = write_efmu_zip(dir.path(), &dir.path().join("out.efmu")).unwrap_err();
        assert_eq!(err.code(), "EFM026");
        let err_text = err.to_string();
        assert!(err_text.contains("UTF-8"), "got: {err_text}");
    }

    /// A mid-write I/O failure must not leave a half-populated eFMU root
    /// behind (which would trip `OutputDirNotEmpty` on retry). The failure is
    /// forced by a file whose directory collides with an already-written
    /// file — a target-path problem only the filesystem reports.
    #[test]
    fn failed_write_cleans_up_partial_root() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("efmu");
        let mut rep = representation("AlgorithmCode");
        rep.files = vec![
            RepresentationFile {
                directory: FilePath::root(),
                name: NameWithoutSlashes::new("x").unwrap(),
                bytes: b"file\n".to_vec(),
            },
            RepresentationFile {
                directory: FilePath::new("./x/").unwrap(),
                name: NameWithoutSlashes::new("y").unwrap(),
                bytes: b"needs ./x/ as a directory\n".to_vec(),
            },
        ];
        let err = write_efmu_container(&[rep], &meta(), &root).unwrap_err();
        assert_eq!(err.code(), "EFM029", "expected an I/O error, got {err:?}");
        assert!(
            !root.exists(),
            "partially written root must be cleaned up after a failed write"
        );
        // A retry with a consistent representation now succeeds.
        write_efmu_container(&[representation("AlgorithmCode")], &meta(), &root)
            .expect("retry after cleanup must succeed");
    }

    /// A zip-write failure partway through must not leave a truncated
    /// archive at the final path — nor clobber a previous valid one — and
    /// must remove its staging file (the zip-form analogue of
    /// [`cleanup_failed_write`]).
    #[test]
    fn failed_zip_write_preserves_previous_archive_and_cleans_staging() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("efmu");
        write_efmu_container(&[representation("AlgorithmCode")], &meta(), &root).unwrap();
        let zip_path = dir.path().join("out.efmu");
        write_efmu_zip(&root, &zip_path).expect("first zip must succeed");
        let previous = fs::read(&zip_path).unwrap();

        // Force a mid-write failure: an entry list naming a file that does
        // not exist under the root (each source is read lazily per entry).
        let err = write_zip_entries(
            &root,
            &zip_path,
            &["__content.xml".to_owned(), "missing-file".to_owned()],
        )
        .unwrap_err();
        assert_eq!(err.code(), "EFM029", "expected an I/O error, got {err:?}");
        assert_eq!(
            fs::read(&zip_path).unwrap(),
            previous,
            "previous archive must survive a failed re-zip"
        );
        let leftovers: Vec<String> = fs::read_dir(dir.path())
            .unwrap()
            .map(|entry| entry.unwrap().file_name().into_string().unwrap())
            .filter(|name| name.ends_with(".part"))
            .collect();
        assert!(
            leftovers.is_empty(),
            "staging file must be removed on failure: {leftovers:?}"
        );
    }

    /// Re-zipping over an existing `.efmu` replaces it (the staged archive
    /// is renamed into place), so repeated packaging of the same directory
    /// form is byte-stable.
    #[test]
    fn zip_rewrite_replaces_existing_archive() {
        let dir = tempfile::tempdir().unwrap();
        let root = dir.path().join("efmu");
        write_efmu_container(&[representation("AlgorithmCode")], &meta(), &root).unwrap();
        let zip_path = dir.path().join("out.efmu");
        write_efmu_zip(&root, &zip_path).expect("first zip must succeed");
        let first = fs::read(&zip_path).unwrap();
        write_efmu_zip(&root, &zip_path).expect("re-zip must replace the archive");
        assert_eq!(
            fs::read(&zip_path).unwrap(),
            first,
            "repeated packaging must be byte-reproducible"
        );
    }

    #[test]
    fn non_empty_output_dir_rejected() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("stale"), b"x").unwrap();
        let err = write_efmu_container(&[representation("AlgorithmCode")], &meta(), dir.path())
            .unwrap_err();
        assert_eq!(err.code(), "EFM028");
    }
}
