# Generated by Rumoca - JAX/Diffrax Code
#
# This file was automatically generated from a Modelica model.
# Do not edit manually.
#
# Dependencies:
#   pip install jax jaxlib diffrax numpy

import os
import math

# Default to CPU backend if no platform is specified
os.environ.setdefault('JAX_PLATFORMS', 'cpu')

import jax
import jax.numpy as jnp
from diffrax import diffeqsolve, ODETerm, Tsit5, SaveAt
from typing import NamedTuple

# Patch namespaces so render_expr's prefix works for builtins
jnp.if_else = jnp.where
jnp.fabs = jnp.abs
jnp.fmin = jnp.minimum
jnp.fmax = jnp.maximum
jnp.sum1 = lambda x: jnp.sum(jnp.array(x))
math.if_else = lambda c, t, e: t if c else e






# Modelica enum values that may appear in start/parameter expressions
StateSelect_never = 1
StateSelect_avoid = 2
StateSelect_default = 3
StateSelect_prefer = 4
StateSelect_always = 5


def if_else(cond, true_val, false_val):
    """Conditional for use in start-value expressions and ode_fn."""
    return jnp.where(cond, true_val, false_val)


# =========================================================================
# User-Defined Functions (0)
# =========================================================================


# =========================================================================
# Default values (evaluated without JAX for initialization)
# =========================================================================

def get_default_values():
    """Compute default start values for all variables."""
    _if_else = lambda c, t, e: t if c else e

    # Forward-declare all variables so cross-references resolve
    time = 0.0


    m = 0.0

    J = 0.0

    g = 0.0




    x = 0.0

    z = 0.0

    theta = 0.0

    x_dot = 0.0

    z_dot = 0.0

    theta_dot = 0.0




    # Assign start values (may reference other variables; errors fall back to 0.0)



    try:
        m = float(2.496)
    except (ZeroDivisionError, ValueError, TypeError, NameError, OverflowError):
        pass



    try:
        J = float(0.0344)
    except (ZeroDivisionError, ValueError, TypeError, NameError, OverflowError):
        pass



    try:
        g = float(9.80665)
    except (ZeroDivisionError, ValueError, TypeError, NameError, OverflowError):
        pass






    try:
        x = float(0.0)
    except (ZeroDivisionError, ValueError, TypeError, NameError, OverflowError):
        pass



    try:
        z = float(0.0)
    except (ZeroDivisionError, ValueError, TypeError, NameError, OverflowError):
        pass



    try:
        theta = float(0.0)
    except (ZeroDivisionError, ValueError, TypeError, NameError, OverflowError):
        pass



    try:
        x_dot = float(0.0)
    except (ZeroDivisionError, ValueError, TypeError, NameError, OverflowError):
        pass



    try:
        z_dot = float(0.0)
    except (ZeroDivisionError, ValueError, TypeError, NameError, OverflowError):
        pass



    try:
        theta_dot = float(0.0)
    except (ZeroDivisionError, ValueError, TypeError, NameError, OverflowError):
        pass



    return {
        'x0': [x, z, theta, x_dot, z_dot, theta_dot],
        'p0': [m, J, g],
        'constants': {

        },
        'z0': {

        },
        'm0': {

        },
    }


# =========================================================================
# ODE right-hand side
# =========================================================================

def ode_fn(t, y, args):
    """ODE right-hand side: dy/dt = f(t, y, args).

    Args:
        t: Current time
        y: State vector as JAX array
        args: Tuple of (params, inputs, constants_and_discrete)

    Returns:
        State derivatives as JAX array
    """
    params, inputs, cd = args
    time = t

    # Unpack state variables

    x = y[0]

    z = y[1]

    theta = y[2]

    x_dot = y[3]

    z_dot = y[4]

    theta_dot = y[5]


    # Unpack parameters

    m = params[0]

    J = params[1]

    g = params[2]


    # Unpack inputs

    T = inputs[0]

    M = inputs[1]


    # Constants


    # Discrete variables (held constant)



    # Algebraic variables



    # Output variables



    # Compute derivatives


    f_x_0 = x_dot  # der(x)

    f_x_1 = z_dot  # der(z)

    f_x_2 = theta_dot  # der(theta)

    f_x_3 = ((-(T * jnp.sin(theta)))) / (m)  # der(x_dot)

    f_x_4 = (((T * jnp.cos(theta)) - (m * g))) / (m)  # der(z_dot)

    f_x_5 = (M) / (J)  # der(theta_dot)


    return jnp.array([

        f_x_0,

        f_x_1,

        f_x_2,

        f_x_3,

        f_x_4,

        f_x_5

    ])



# =========================================================================
# Simulation
# =========================================================================

def simulate(x0=None, u=None, t_span=(0.0, 1.0), dt=0.01):
    """Simulate the model.

    Args:
        x0: Initial state as JAX array (uses defaults if None)
        u: Constant input vector applied over the rollout (zeros if None)
        t_span: Tuple of (t0, tf)
        dt: Integration step size

    Returns:
        Tuple of (times, states)
    """
    defaults = get_default_values()

    if x0 is None:
        y0 = jnp.array(defaults['x0'])
    else:
        y0 = jnp.asarray(x0)

    params = jnp.array(defaults['p0'])

    n_u = len(get_input_names())
    if u is None:
        inputs = jnp.zeros(n_u)
    else:
        inputs = jnp.asarray(u)

    # Merge constants and discrete vars into a single dict
    cd = {}
    cd.update(defaults['constants'])
    cd.update(defaults['z0'])
    cd.update(defaults['m0'])

    t0, tf = t_span
    n_steps = int((tf - t0) / dt)
    save_at = SaveAt(ts=jnp.linspace(t0, tf, n_steps + 1))

    term = ODETerm(ode_fn)
    solver = Tsit5()

    sol = diffeqsolve(
        term,
        solver,
        t0=t0,
        t1=tf,
        dt0=dt,
        y0=y0,
        args=(params, inputs, cd),
        saveat=save_at,
    )

    return sol.ts, sol.ys


# =========================================================================
# CSV output for testing
# =========================================================================

def get_state_names():
    """Get list of state variable names."""
    return ['x', 'z', 'theta', 'x_dot', 'z_dot', 'theta_dot']


def simulate_csv(t_end=1.0, dt=0.01):
    """Run simulation and return CSV string."""
    ts, ys = simulate(t_span=(0.0, t_end), dt=dt)
    header = "time," + ",".join(get_state_names())
    rows = [header]
    for i in range(len(ts)):
        row = [f"{float(ts[i]):.10g}"] + [f"{float(ys[i, j]):.10g}" for j in range(ys.shape[1])]
        rows.append(",".join(row))
    return "\n".join(rows)


def get_param_names():
    """Get list of parameter names."""
    return ['m', 'J', 'g']


def get_input_names():
    """Get list of input names."""
    return ['T', 'M']


if __name__ == '__main__':
    print(f"States (6): {get_state_names()}")
    print(f"Parameters (3): {get_param_names()}")
    print(f"Inputs (2): {get_input_names()}")


    print(simulate_csv())
