version = 1

[libraries.msl]
display_name = "MSL"
version = "4.1.0"
url = "https://github.com/modelica/ModelicaStandardLibrary/releases/download/v4.1.0/ModelicaStandardLibrary_v4.1.0.zip"
sha256 = "5409cfa17797c52d866dc9d2675badc1378b4bbf88066e60899a489cb1cb8a2d"
cache_dir = "target/msl/ModelicaStandardLibrary-4.1.0"
zip_layout = "direct"
required_files = [
  "Complex.mo",
  "Modelica 4.1.0/package.mo",
]

[libraries.cmm]
display_name = "CMM"
version = "v0.0.2"
url = "https://github.com/CogniPilot/modelica_models/releases/download/v0.0.2/CMM_v0.0.2.zip"
sha256 = "ec233a25a0875d2ba1d07f4199a25c8eeb86694d3f9867394d2ae50e41574508"
cache_dir = "target/cmm/CMM-v0.0.2"
zip_layout = "auto-strip-common-root"
required_files = [
  "LieGroup/package.mo",
  "LieGroups/package.mo",
  "RigidBody/package.mo",
]
write_revision_marker = true
