// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <Eigen/Core>

#include <lcmtypes/sym/algebraics_t.hpp>
#include <lcmtypes/sym/derivatives_t.hpp>
#include <lcmtypes/sym/external_inputs_t.hpp>
#include <lcmtypes/sym/model_outputs_t.hpp>
#include <lcmtypes/sym/parameters_t.hpp>
#include <lcmtypes/sym/states_t.hpp>

namespace sym {

/**
 * This function was autogenerated. Do not modify by hand.
 *
 * Args:
 *     time: Scalar
 *     states: Values
 *     derivatives: Values
 *     algebraics: Values
 *     model_outputs: Values
 *     external_inputs: Values
 *     parameters: Values
 *
 * Outputs:
 *     f_x: Matrix22_1
 *     f_x_D_time: (22x1) jacobian of f_x (22) wrt arg time (1)
 *     f_x_D_states: (22x10) jacobian of f_x (22) wrt arg states (10)
 *     f_x_D_derivatives: (22x10) jacobian of f_x (22) wrt arg derivatives (10)
 *     f_x_D_algebraics: (22x9) jacobian of f_x (22) wrt arg algebraics (9)
 *     f_x_D_model_outputs: (22x3) jacobian of f_x (22) wrt arg model_outputs (3)
 *     f_x_D_external_inputs: (22x6) jacobian of f_x (22) wrt arg external_inputs (6)
 *     f_x_D_parameters: (22x1) jacobian of f_x (22) wrt arg parameters (1)
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 22, 1> FixedwinginsDaeResidualJacobians(
    const Scalar time, const sym::states_t& states, const sym::derivatives_t& derivatives,
    const sym::algebraics_t& algebraics, const sym::model_outputs_t& model_outputs,
    const sym::external_inputs_t& external_inputs, const sym::parameters_t& parameters,
    Eigen::Matrix<Scalar, 22, 1>* const f_x_D_time = nullptr,
    Eigen::Matrix<Scalar, 22, 10>* const f_x_D_states = nullptr,
    Eigen::Matrix<Scalar, 22, 10>* const f_x_D_derivatives = nullptr,
    Eigen::Matrix<Scalar, 22, 9>* const f_x_D_algebraics = nullptr,
    Eigen::Matrix<Scalar, 22, 3>* const f_x_D_model_outputs = nullptr,
    Eigen::Matrix<Scalar, 22, 6>* const f_x_D_external_inputs = nullptr,
    Eigen::Matrix<Scalar, 22, 1>* const f_x_D_parameters = nullptr) {
  // Total ops: 146

  // Unused inputs
  (void)time;

  // Input arrays

  // Intermediate terms (33)
  const Scalar _tmp0 = std::pow(states.qz, Scalar(2));
  const Scalar _tmp1 = std::pow(states.qy, Scalar(2));
  const Scalar _tmp2 = states.qx * states.qy;
  const Scalar _tmp3 = states.qw * states.qz;
  const Scalar _tmp4 = states.qw * states.qy;
  const Scalar _tmp5 = states.qx * states.qz;
  const Scalar _tmp6 = std::pow(states.qx, Scalar(2));
  const Scalar _tmp7 = states.qw * states.qx;
  const Scalar _tmp8 = states.qy * states.qz;
  const Scalar _tmp9 = 2 * states.qz;
  const Scalar _tmp10 = 2 * states.qy;
  const Scalar _tmp11 = -_tmp10;
  const Scalar _tmp12 = -_tmp9;
  const Scalar _tmp13 = 2 * states.qx;
  const Scalar _tmp14 = -_tmp13;
  const Scalar _tmp15 = Scalar(0.5) * external_inputs.wx;
  const Scalar _tmp16 = -_tmp15;
  const Scalar _tmp17 = Scalar(0.5) * external_inputs.wy;
  const Scalar _tmp18 = -_tmp17;
  const Scalar _tmp19 = Scalar(0.5) * external_inputs.wz;
  const Scalar _tmp20 = -_tmp19;
  const Scalar _tmp21 = 4 * states.qx;
  const Scalar _tmp22 = 2 * states.qw;
  const Scalar _tmp23 = -_tmp22;
  const Scalar _tmp24 = 4 * states.qy;
  const Scalar _tmp25 = 4 * states.qz;
  const Scalar _tmp26 = -external_inputs.fx;
  const Scalar _tmp27 = -external_inputs.fy;
  const Scalar _tmp28 = -external_inputs.fz;
  const Scalar _tmp29 = Scalar(0.5) * states.qx;
  const Scalar _tmp30 = -Scalar(0.5) * states.qw;
  const Scalar _tmp31 = Scalar(0.5) * states.qz;
  const Scalar _tmp32 = Scalar(0.5) * states.qy;

  // Output terms (8)
  Eigen::Matrix<Scalar, 22, 1> _f_x;

  _f_x(0, 0) = 2 * _tmp0 + 2 * _tmp1 + algebraics.R11 - 1;
  _f_x(1, 0) = -2 * _tmp2 + 2 * _tmp3 + algebraics.R12;
  _f_x(2, 0) = -2 * _tmp4 - 2 * _tmp5 + algebraics.R13;
  _f_x(3, 0) = -2 * _tmp2 - 2 * _tmp3 + algebraics.R21;
  _f_x(4, 0) = 2 * _tmp0 + 2 * _tmp6 + algebraics.R22 - 1;
  _f_x(5, 0) = 2 * _tmp7 - 2 * _tmp8 + algebraics.R23;
  _f_x(6, 0) = 2 * _tmp4 - 2 * _tmp5 + algebraics.R31;
  _f_x(7, 0) = -2 * _tmp7 - 2 * _tmp8 + algebraics.R32;
  _f_x(8, 0) = 2 * _tmp1 + 2 * _tmp6 + algebraics.R33 - 1;
  _f_x(9, 0) = -algebraics.R11 * external_inputs.fx - algebraics.R12 * external_inputs.fy -
               algebraics.R13 * external_inputs.fz + model_outputs.ax;
  _f_x(10, 0) = -algebraics.R21 * external_inputs.fx - algebraics.R22 * external_inputs.fy -
                algebraics.R23 * external_inputs.fz + model_outputs.ay;
  _f_x(11, 0) = -algebraics.R31 * external_inputs.fx - algebraics.R32 * external_inputs.fy -
                algebraics.R33 * external_inputs.fz + model_outputs.az + parameters.g;
  _f_x(12, 0) = derivatives.px - states.vx;
  _f_x(13, 0) = derivatives.py - states.vy;
  _f_x(14, 0) = derivatives.pz - states.vz;
  _f_x(15, 0) = derivatives.vx - model_outputs.ax;
  _f_x(16, 0) = derivatives.vy - model_outputs.ay;
  _f_x(17, 0) = derivatives.vz - model_outputs.az;
  _f_x(18, 0) = derivatives.qw + Scalar(0.5) * external_inputs.wx * states.qx +
                Scalar(0.5) * external_inputs.wy * states.qy +
                Scalar(0.5) * external_inputs.wz * states.qz;
  _f_x(19, 0) = derivatives.qx - Scalar(0.5) * external_inputs.wx * states.qw +
                Scalar(0.5) * external_inputs.wy * states.qz -
                Scalar(0.5) * external_inputs.wz * states.qy;
  _f_x(20, 0) = derivatives.qy - Scalar(0.5) * external_inputs.wx * states.qz -
                Scalar(0.5) * external_inputs.wy * states.qw +
                Scalar(0.5) * external_inputs.wz * states.qx;
  _f_x(21, 0) = derivatives.qz + Scalar(0.5) * external_inputs.wx * states.qy -
                Scalar(0.5) * external_inputs.wy * states.qx -
                Scalar(0.5) * external_inputs.wz * states.qw;

  if (f_x_D_time != nullptr) {
    Eigen::Matrix<Scalar, 22, 1>& _f_x_D_time = (*f_x_D_time);

    _f_x_D_time.setZero();
  }

  if (f_x_D_states != nullptr) {
    Eigen::Matrix<Scalar, 22, 10>& _f_x_D_states = (*f_x_D_states);

    _f_x_D_states.setZero();

    _f_x_D_states(12, 3) = -1;
    _f_x_D_states(13, 4) = -1;
    _f_x_D_states(14, 5) = -1;
    _f_x_D_states(1, 6) = _tmp9;
    _f_x_D_states(2, 6) = _tmp11;
    _f_x_D_states(3, 6) = _tmp12;
    _f_x_D_states(5, 6) = _tmp13;
    _f_x_D_states(6, 6) = _tmp10;
    _f_x_D_states(7, 6) = _tmp14;
    _f_x_D_states(19, 6) = _tmp16;
    _f_x_D_states(20, 6) = _tmp18;
    _f_x_D_states(21, 6) = _tmp20;
    _f_x_D_states(1, 7) = _tmp11;
    _f_x_D_states(2, 7) = _tmp12;
    _f_x_D_states(3, 7) = _tmp11;
    _f_x_D_states(4, 7) = _tmp21;
    _f_x_D_states(5, 7) = _tmp22;
    _f_x_D_states(6, 7) = _tmp12;
    _f_x_D_states(7, 7) = _tmp23;
    _f_x_D_states(8, 7) = _tmp21;
    _f_x_D_states(18, 7) = _tmp15;
    _f_x_D_states(20, 7) = _tmp19;
    _f_x_D_states(21, 7) = _tmp18;
    _f_x_D_states(0, 8) = _tmp24;
    _f_x_D_states(1, 8) = _tmp14;
    _f_x_D_states(2, 8) = _tmp23;
    _f_x_D_states(3, 8) = _tmp14;
    _f_x_D_states(5, 8) = _tmp12;
    _f_x_D_states(6, 8) = _tmp22;
    _f_x_D_states(7, 8) = _tmp12;
    _f_x_D_states(8, 8) = _tmp24;
    _f_x_D_states(18, 8) = _tmp17;
    _f_x_D_states(19, 8) = _tmp20;
    _f_x_D_states(21, 8) = _tmp15;
    _f_x_D_states(0, 9) = _tmp25;
    _f_x_D_states(1, 9) = _tmp22;
    _f_x_D_states(2, 9) = _tmp14;
    _f_x_D_states(3, 9) = _tmp23;
    _f_x_D_states(4, 9) = _tmp25;
    _f_x_D_states(5, 9) = _tmp11;
    _f_x_D_states(6, 9) = _tmp14;
    _f_x_D_states(7, 9) = _tmp11;
    _f_x_D_states(18, 9) = _tmp19;
    _f_x_D_states(19, 9) = _tmp17;
    _f_x_D_states(20, 9) = _tmp16;
  }

  if (f_x_D_derivatives != nullptr) {
    Eigen::Matrix<Scalar, 22, 10>& _f_x_D_derivatives = (*f_x_D_derivatives);

    _f_x_D_derivatives.setZero();

    _f_x_D_derivatives(12, 0) = 1;
    _f_x_D_derivatives(13, 1) = 1;
    _f_x_D_derivatives(14, 2) = 1;
    _f_x_D_derivatives(15, 3) = 1;
    _f_x_D_derivatives(16, 4) = 1;
    _f_x_D_derivatives(17, 5) = 1;
    _f_x_D_derivatives(18, 6) = 1;
    _f_x_D_derivatives(19, 7) = 1;
    _f_x_D_derivatives(20, 8) = 1;
    _f_x_D_derivatives(21, 9) = 1;
  }

  if (f_x_D_algebraics != nullptr) {
    Eigen::Matrix<Scalar, 22, 9>& _f_x_D_algebraics = (*f_x_D_algebraics);

    _f_x_D_algebraics.setZero();

    _f_x_D_algebraics(0, 0) = 1;
    _f_x_D_algebraics(9, 0) = _tmp26;
    _f_x_D_algebraics(1, 1) = 1;
    _f_x_D_algebraics(9, 1) = _tmp27;
    _f_x_D_algebraics(2, 2) = 1;
    _f_x_D_algebraics(9, 2) = _tmp28;
    _f_x_D_algebraics(3, 3) = 1;
    _f_x_D_algebraics(10, 3) = _tmp26;
    _f_x_D_algebraics(4, 4) = 1;
    _f_x_D_algebraics(10, 4) = _tmp27;
    _f_x_D_algebraics(5, 5) = 1;
    _f_x_D_algebraics(10, 5) = _tmp28;
    _f_x_D_algebraics(6, 6) = 1;
    _f_x_D_algebraics(11, 6) = _tmp26;
    _f_x_D_algebraics(7, 7) = 1;
    _f_x_D_algebraics(11, 7) = _tmp27;
    _f_x_D_algebraics(8, 8) = 1;
    _f_x_D_algebraics(11, 8) = _tmp28;
  }

  if (f_x_D_model_outputs != nullptr) {
    Eigen::Matrix<Scalar, 22, 3>& _f_x_D_model_outputs = (*f_x_D_model_outputs);

    _f_x_D_model_outputs.setZero();

    _f_x_D_model_outputs(9, 0) = 1;
    _f_x_D_model_outputs(15, 0) = -1;
    _f_x_D_model_outputs(10, 1) = 1;
    _f_x_D_model_outputs(16, 1) = -1;
    _f_x_D_model_outputs(11, 2) = 1;
    _f_x_D_model_outputs(17, 2) = -1;
  }

  if (f_x_D_external_inputs != nullptr) {
    Eigen::Matrix<Scalar, 22, 6>& _f_x_D_external_inputs = (*f_x_D_external_inputs);

    _f_x_D_external_inputs.setZero();

    _f_x_D_external_inputs(18, 0) = _tmp29;
    _f_x_D_external_inputs(19, 0) = _tmp30;
    _f_x_D_external_inputs(20, 0) = -_tmp31;
    _f_x_D_external_inputs(21, 0) = _tmp32;
    _f_x_D_external_inputs(18, 1) = _tmp32;
    _f_x_D_external_inputs(19, 1) = _tmp31;
    _f_x_D_external_inputs(20, 1) = _tmp30;
    _f_x_D_external_inputs(21, 1) = -_tmp29;
    _f_x_D_external_inputs(18, 2) = _tmp31;
    _f_x_D_external_inputs(19, 2) = -_tmp32;
    _f_x_D_external_inputs(20, 2) = _tmp29;
    _f_x_D_external_inputs(21, 2) = _tmp30;
    _f_x_D_external_inputs(9, 3) = -algebraics.R11;
    _f_x_D_external_inputs(10, 3) = -algebraics.R21;
    _f_x_D_external_inputs(11, 3) = -algebraics.R31;
    _f_x_D_external_inputs(9, 4) = -algebraics.R12;
    _f_x_D_external_inputs(10, 4) = -algebraics.R22;
    _f_x_D_external_inputs(11, 4) = -algebraics.R32;
    _f_x_D_external_inputs(9, 5) = -algebraics.R13;
    _f_x_D_external_inputs(10, 5) = -algebraics.R23;
    _f_x_D_external_inputs(11, 5) = -algebraics.R33;
  }

  if (f_x_D_parameters != nullptr) {
    Eigen::Matrix<Scalar, 22, 1>& _f_x_D_parameters = (*f_x_D_parameters);

    _f_x_D_parameters.setZero();

    _f_x_D_parameters(11, 0) = 1;
  }

  return _f_x;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
