[book]
title = "Rumoca Handbook"
authors = ["Rumoca Contributors"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/CogniPilot/rumoca"
edit-url-template = "https://github.com/CogniPilot/rumoca/edit/main/docs/user-guide/{path}"
additional-js = ["live/rumoca-live.js"]
additional-css = ["live/rumoca-live.css"]
