//! Explicit contract-case manifest entries for ALG through CLK contracts.

use super::{ContractCase, ContractCaseKind, ContractCaseOutcome};

pub(super) static IMPLEMENTED_CONTRACT_CASES_A_C: &[ContractCase] = &[
    ContractCase {
        contract_id: "ALG-001",
        case_id: "alg_001_assignment_in_algorithm",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ALG-001",
        case_id: "alg_basic_algorithm_section",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ALG-001",
        case_id: "alg_001_no_equality_in_algorithm",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ALG-005",
        case_id: "alg_005_while_boolean",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ALG-007",
        case_id: "alg_007_no_when_in_function",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ALG-008",
        case_id: "alg_008_when_in_initial_algorithm_rejected",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ALG-009",
        case_id: "alg_009_no_nested_when_statements",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ALG-010",
        case_id: "alg_010_when_in_for_rejected",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ALG-012",
        case_id: "alg_012_break_in_for",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ALG-013",
        case_id: "alg_013_return_in_function",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ALG-016",
        case_id: "alg_016_for_range",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ALG-016",
        case_id: "alg_for_loop_algorithm",
        test_file: "tests/alg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ANN-001",
        case_id: "ann_001_component_annotation_each_rejected",
        test_file: "tests/ann_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ANN-001",
        case_id: "ann_001_class_annotation_redeclare_rejected",
        test_file: "tests/ann_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ANN-001",
        case_id: "ann_001_extends_annotation_replaceable_rejected",
        test_file: "tests/ann_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ANN-008",
        case_id: "ann_008_parameter_evaluate_ok",
        test_file: "tests/ann_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ANN-008",
        case_id: "ann_008_variable_evaluate_rejected",
        test_file: "tests/ann_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ANN-008",
        case_id: "ann_008_class_annotation_evaluate_rejected",
        test_file: "tests/ann_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ANN-008",
        case_id: "ann_008_extends_annotation_evaluate_rejected",
        test_file: "tests/ann_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ARR-001",
        case_id: "arr_001_fixed_dimensionality",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-001",
        case_id: "arr_array_of_parameters",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-002",
        case_id: "arr_002_rectangular_2d",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-003",
        case_id: "arr_003_matching_sizes",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-005",
        case_id: "arr_005_valid_index",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-006",
        case_id: "arr_006_empty_array_constructor_rejected",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ARR-017",
        case_id: "arr_017_zeros_or_ones_empty_rejected",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ARR-018",
        case_id: "arr_018_fill_too_few_args_rejected",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ARR-023",
        case_id: "arr_023_cat_requires_arguments_rejected",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "ARR-009",
        case_id: "arr_009_int_to_real_coercion",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-019",
        case_id: "arr_019_linspace_valid",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-027",
        case_id: "arr_027_same_dim_assignment",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-029",
        case_id: "arr_029_add_same_size",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-029",
        case_id: "arr_scalar_broadcast",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "ARR-030",
        case_id: "arr_030_divide_by_scalar",
        test_file: "tests/arr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "CONN-001",
        case_id: "conn_001_flow_connects_ok",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "CONN-001",
        case_id: "conn_series_resistors",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "CONN-002",
        case_id: "conn_002_same_type_connectors",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "CONN-002",
        case_id: "conn_002_type_mismatch_rejected",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CONN-003",
        case_id: "conn_003_flow_to_flow_mismatch_rejected",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CONN-007",
        case_id: "conn_007_no_parameter_connector",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CONN-008",
        case_id: "conn_008_same_dimensions",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "CONN-008",
        case_id: "conn_008_dimension_mismatch_rejected",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CONN-009",
        case_id: "conn_009_expandable_connector_rejects_flow_member",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CONN-010",
        case_id: "conn_010_expandable_connector_requires_expandable_peer",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CONN-017",
        case_id: "conn_017_balanced_connector",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "CONN-017",
        case_id: "conn_017_unbalanced_connector_fails",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CONN-026",
        case_id: "conn_026_flow_sign_basic",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "CONN-029",
        case_id: "conn_029_connect_requires_connectors",
        test_file: "tests/conn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CLK-001",
        case_id: "clk_001_clock_constructor_forbidden_in_function",
        test_file: "tests/clk_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CLK-002",
        case_id: "clk_002_parameter_clock_prefix_rejected",
        test_file: "tests/clk_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CLK-002",
        case_id: "clk_002_discrete_clock_prefix_rejected",
        test_file: "tests/clk_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CLK-013",
        case_id: "clk_013_derivative_on_clock_operator_rejected",
        test_file: "tests/clk_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CLK-013",
        case_id: "clk_013_derivative_on_clock_operator_in_binding_rejected",
        test_file: "tests/clk_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CLK-020",
        case_id: "clk_020_flow_clock_prefix_rejected",
        test_file: "tests/clk_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "CLK-020",
        case_id: "clk_020_stream_clock_prefix_rejected",
        test_file: "tests/clk_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
];
