//! Explicit contract-case manifest entries for DECL through FUNC contracts.

use super::{ContractCase, ContractCaseKind, ContractCaseOutcome};

pub(super) static IMPLEMENTED_CONTRACT_CASES_D_F: &[ContractCase] = &[
    ContractCase {
        contract_id: "DECL-001",
        case_id: "decl_001_distinct_names_ok",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "DECL-001",
        case_id: "decl_001_rejects_duplicate_names",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-002",
        case_id: "decl_002_block_connector_needs_io_prefix",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-003",
        case_id: "decl_003_record_no_protected",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-003",
        case_id: "decl_003_record_public_ok",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "DECL-004",
        case_id: "decl_004_record_no_flow",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-005",
        case_id: "decl_005_record_no_model_component",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-006",
        case_id: "decl_006_connector_no_protected",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-007",
        case_id: "decl_007_connector_no_inner_outer",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-009",
        case_id: "decl_009_no_protected_dot_access",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-012",
        case_id: "decl_012_input_not_parameter",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-014",
        case_id: "decl_014_partial_class_error",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-015",
        case_id: "decl_015_component_not_same_name_as_class",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-018",
        case_id: "decl_018_array_dim_constant",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "DECL-019",
        case_id: "decl_019_constant_with_value",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "DECL-020",
        case_id: "decl_020_no_der_on_discrete",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-022",
        case_id: "decl_022_integer_discrete",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "DECL-024",
        case_id: "decl_024_package_no_variables",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-024",
        case_id: "decl_024_package_with_constant",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "DECL-032",
        case_id: "decl_032_balanced_model",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "DECL-032",
        case_id: "decl_032_balanced_ode",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "DECL-032",
        case_id: "decl_032_unbalanced_model",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "DECL-036",
        case_id: "decl_036_type_alias",
        test_file: "tests/decl_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-001",
        case_id: "eqn_001_ode_balanced",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-001",
        case_id: "eqn_001_simple_balanced",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-001",
        case_id: "eqn_001_underspecified",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-001",
        case_id: "eqn_multiple_equations",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-002",
        case_id: "eqn_002_input_with_binding",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-003",
        case_id: "eqn_003_algorithm_section",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-004",
        case_id: "eqn_004_if_equation_balanced",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-005",
        case_id: "eqn_005_no_nested_when",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-006",
        case_id: "eqn_006_no_when_in_initial",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-008",
        case_id: "eqn_008_for_equation_vector",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-008",
        case_id: "eqn_for_loop_equations",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-010",
        case_id: "eqn_010_for_variable_readonly",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-011",
        case_id: "eqn_011_if_boolean_ok",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-013",
        case_id: "eqn_013_when_elsewhen_same_lhs_set_ok",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-013",
        case_id: "eqn_013_when_elsewhen_different_lhs_set_fails",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-015",
        case_id: "eqn_015_reinit_in_when",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-015",
        case_id: "eqn_015_reinit_outside_when_fails",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-016",
        case_id: "eqn_016_reinit_state_variable_ok",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-016",
        case_id: "eqn_016_reinit_non_state_fails",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-021",
        case_id: "eqn_021_constants_by_declaration",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-024",
        case_id: "eqn_024_no_assignment_in_equations",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-025",
        case_id: "eqn_025_type_compatible",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-025",
        case_id: "eqn_025_record_wrapper_constructor_compatible",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-025",
        case_id: "eqn_025_user_defined_record_type_mismatch_fails",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-025",
        case_id: "eqn_025_record_constructor_type_mismatch_fails",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EQN-029",
        case_id: "eqn_029_when_boolean_condition",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-029",
        case_id: "eqn_when_clause_basic",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-033",
        case_id: "eqn_033_perfect_matching",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EQN-037",
        case_id: "eqn_037_no_when_in_initial",
        test_file: "tests/eqn_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-001",
        case_id: "expr_001_relational_scalar_ok",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-002",
        case_id: "expr_002_no_real_equality",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-003",
        case_id: "expr_003_der_of_continuous",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-004",
        case_id: "expr_004_no_der_in_functions",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-005",
        case_id: "expr_005_normal_arithmetic",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-006",
        case_id: "expr_006_delaymax_parameter_expression_ok",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-006",
        case_id: "expr_006_delaymax_parameter_expression_rejected",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-008",
        case_id: "expr_008_delay_not_in_function",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-009",
        case_id: "expr_009_cardinality_rejects_connector_arrays",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-009",
        case_id: "expr_009_cardinality_rejects_expandable_connectors",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-012",
        case_id: "expr_012_constant_to_parameter_ok",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-012",
        case_id: "expr_012_variable_to_parameter_fails",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-013",
        case_id: "expr_013_end_in_subscript",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-013",
        case_id: "expr_013_end_outside_subscript_fails",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-014",
        case_id: "expr_014_no_chained_relationals",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-015",
        case_id: "expr_015_unary_minus_ok",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-016",
        case_id: "expr_016_if_expr_boolean",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-016",
        case_id: "expr_016_if_expr_non_boolean_fails",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-017",
        case_id: "expr_017_if_expr_same_type",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-018",
        case_id: "expr_018_abs_real",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-019",
        case_id: "expr_019_sign_real",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-024",
        case_id: "expr_024_div_integer",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-024",
        case_id: "expr_024_mod_integer",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-025",
        case_id: "expr_025_ceil_real",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-025",
        case_id: "expr_025_floor_real",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-026",
        case_id: "expr_026_integer_accepts_real_argument",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-026",
        case_id: "expr_026_integer_rejects_boolean_argument",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-027",
        case_id: "expr_027_delay_rejects_string_value_argument",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-028",
        case_id: "expr_028_delay_rejects_non_real_time_argument",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-029",
        case_id: "expr_029_delaytime_parameter_expression_ok",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-029",
        case_id: "expr_029_delaytime_non_parameter_rejected",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-033",
        case_id: "expr_033_cardinality_not_in_function",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-035",
        case_id: "expr_035_instream_not_in_function",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-036",
        case_id: "expr_036_actualstream_not_in_function",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-037",
        case_id: "expr_037_pre_not_in_function",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "EXPR-039",
        case_id: "expr_039_noevent_usage",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "EXPR-040",
        case_id: "expr_040_integer_event_trigger",
        test_file: "tests/expr_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-001",
        case_id: "func_001_input_output_ok",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-001",
        case_id: "func_001_public_no_prefix_fails",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-002",
        case_id: "func_002_input_readonly",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-006",
        case_id: "func_006_no_equations_in_function",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-007",
        case_id: "func_007_no_when_in_function",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-010",
        case_id: "func_010_builtin_math_call_ok",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-010",
        case_id: "func_010_initial_forbidden_in_function",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-010",
        case_id: "func_010_sample_forbidden_in_function",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-011",
        case_id: "func_011_non_clock_component_ok",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-011",
        case_id: "func_011_clock_component_fails",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-012",
        case_id: "func_012_local_component_without_inner_outer_ok",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-012",
        case_id: "func_012_inner_prefix_in_function_fails",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-012",
        case_id: "func_012_outer_prefix_in_function_fails",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-014",
        case_id: "func_014_single_algorithm",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-017",
        case_id: "func_017_return_in_function",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-017",
        case_id: "func_017_return_outside_function_algorithm_fails",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-015",
        case_id: "func_015_record_component_ok",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-015",
        case_id: "func_015_connector_component_fails",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "FUNC-001",
        case_id: "func_basic_call",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-001",
        case_id: "func_with_protected",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-001",
        case_id: "func_multiple_outputs",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "FUNC-001",
        case_id: "func_default_input",
        test_file: "tests/func_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
];
