//! Explicit contract-case manifest entries for INST through LEX contracts.

use super::{ContractCase, ContractCaseKind, ContractCaseOutcome};

pub(super) static IMPLEMENTED_CONTRACT_CASES_I_L: &[ContractCase] = &[
    ContractCase {
        contract_id: "INST-001",
        case_id: "inst_001_modification_context",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-002",
        case_id: "inst_002_outer_overrides_inner",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-003",
        case_id: "inst_003_no_duplicate_modifications",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-006",
        case_id: "inst_006_identical_inherited_components_are_kept_once",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-006",
        case_id: "inst_006_conflicting_inherited_components_fail",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-007",
        case_id: "inst_007_parameter_evaluable",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-008",
        case_id: "inst_008_no_cyclic_binding",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-010",
        case_id: "inst_010_final_cannot_modify",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-011",
        case_id: "inst_011_inner_can_be_subtype_of_outer",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-011",
        case_id: "inst_011_inner_must_match_outer_constraint",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-012",
        case_id: "inst_012_outer_binding_is_rejected",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-012",
        case_id: "inst_012_outer_modification_is_rejected",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-014",
        case_id: "inst_014_replaceable_component_can_be_redeclared",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-014",
        case_id: "inst_014_non_replaceable_component_cannot_be_redeclared",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-014",
        case_id: "inst_014_replaceable_nested_class_can_be_redeclared",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-014",
        case_id: "inst_014_non_replaceable_nested_class_cannot_be_redeclared",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-016",
        case_id: "inst_016_conditional_parameter",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-022",
        case_id: "inst_022_constant_component_cannot_be_redeclared",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-027",
        case_id: "inst_027_constraining_clause_modifications_apply_after_redeclare",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-029",
        case_id: "inst_029_break_existing_element_is_allowed",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-029",
        case_id: "inst_029_break_missing_element_fails",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-034",
        case_id: "inst_034_encapsulated_basic",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-034",
        case_id: "inst_034_encapsulated_self_lookup_ok",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-037",
        case_id: "inst_037_identical_inherited_child_class_is_kept_once",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-037",
        case_id: "inst_037_conflicting_inherited_child_class_fails",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-039",
        case_id: "inst_039_protected_extends_marks_inherited_components_protected",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-043",
        case_id: "inst_043_original_type_is_used_as_implicit_constraint",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-043",
        case_id: "inst_043_redeclare_must_still_be_subtype_without_explicit_constrainedby",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "INST-053",
        case_id: "inst_053_conditional_false_removed",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "INST-053",
        case_id: "inst_053_conditional_true_kept",
        test_file: "tests/inst_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "LEX-001",
        case_id: "lex_001_ascii_identifiers_non_ascii",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "LEX-001",
        case_id: "lex_001_ascii_identifiers_valid",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "LEX-002",
        case_id: "lex_002_no_token_whitespace",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "LEX-003",
        case_id: "lex_003_no_nested_comments",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "LEX-004",
        case_id: "lex_004_case_sensitivity",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "LEX-005",
        case_id: "lex_005_reserved_keywords",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "LEX-006",
        case_id: "lex_006_reserved_type_names",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "LEX-007",
        case_id: "lex_007_quoted_distinct",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "LEX-007",
        case_id: "lex_007_quoted_with_spaces",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "LEX-008",
        case_id: "lex_008_string_concat_explicit",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "LEX-009",
        case_id: "lex_009_semantic_parser_check",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "LEX-010",
        case_id: "lex_010_float_range",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "LEX-011",
        case_id: "lex_011_integer_range",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "LEX-012",
        case_id: "lex_012_boolean_literals",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "LEX-013",
        case_id: "lex_013_string_escapes",
        test_file: "tests/lex_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Accept,
    },
];
