//! Explicit contract-case manifest entries for OPREC through STRM contracts.

use super::{ContractCase, ContractCaseKind, ContractCaseOutcome};

pub(super) static IMPLEMENTED_CONTRACT_CASES_M_S: &[ContractCase] = &[
    ContractCase {
        contract_id: "OPREC-001",
        case_id: "oprec_001_encapsulated_operator_ok",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "OPREC-001",
        case_id: "oprec_001_unencapsulated_operator_rejected",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "OPREC-002",
        case_id: "oprec_002_single_output_ok",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "OPREC-002",
        case_id: "oprec_002_multiple_outputs_rejected",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "OPREC-003",
        case_id: "oprec_003_record_input_ok",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "OPREC-003",
        case_id: "oprec_003_missing_record_input_rejected",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "OPREC-004",
        case_id: "oprec_004_constructor_output_ok",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "OPREC-004",
        case_id: "oprec_004_constructor_output_rejected",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "OPREC-008",
        case_id: "oprec_008_zero_operator_single_zero_input_ok",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "OPREC-008",
        case_id: "oprec_008_zero_operator_multiple_functions_rejected",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "OPREC-008",
        case_id: "oprec_008_zero_operator_with_input_rejected",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "OPREC-010",
        case_id: "oprec_010_string_output_ok",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "OPREC-010",
        case_id: "oprec_010_non_string_output_rejected",
        test_file: "tests/oprec_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-001",
        case_id: "pkg_001_no_duplicate_imports",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-002",
        case_id: "pkg_002_import_basic",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "PKG-002",
        case_id: "pkg_002_import_not_inherited_fails",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-003",
        case_id: "pkg_003_import_from_package",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "PKG-003",
        case_id: "pkg_nested_package",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "PKG-003",
        case_id: "pkg_package_with_class",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "PKG-003",
        case_id: "pkg_003_import_from_non_package_rejected",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-005",
        case_id: "pkg_005_import_element_of_package",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "PKG-005",
        case_id: "pkg_005_import_cannot_traverse_model_members",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-006",
        case_id: "pkg_006_directory_requires_package_mo",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-007",
        case_id: "pkg_007_duplicate_child_class_names_rejected",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-008",
        case_id: "pkg_008_dir_and_file_conflict_rejected",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-009",
        case_id: "pkg_009_non_top_level_file_requires_within",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-010",
        case_id: "pkg_010_within_must_match_enclosing_package",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-011",
        case_id: "pkg_011_qualified_import",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "PKG-012",
        case_id: "pkg_012_import_clause_not_modifiable",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Parse,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "PKG-002",
        case_id: "pkg_wildcard_import",
        test_file: "tests/pkg_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-002",
        case_id: "sim_002_initialization_fixed",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-003",
        case_id: "sim_003_parameter_fixed_default",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-003",
        case_id: "sim_003_parameter_missing_binding_not_standalone_simulatable",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-003",
        case_id: "sim_003_parameter_with_binding_is_standalone_simulatable",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-003",
        case_id: "sim_with_parameters",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-004",
        case_id: "sim_004_non_parameter_variable_defaults_fixed_false",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-005",
        case_id: "sim_005_discrete_solved_form_acyclic_dependency",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-005",
        case_id: "sim_005_conditional_when_missing_branch_uses_pre_fallback",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-005",
        case_id: "sim_005_discrete_solved_form_rejects_cycle",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_dae_has_algebraic_equations",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_dae_has_ode_equations",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_dae_structure_ode_and_algebraic",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_basic_integrator",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_spring_mass",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Balance,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_with_when_clause",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_fc_relation_covers_if_and_when_conditions",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_fc_relation_ignores_noevent_conditions",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_sample_allowed_in_discrete_when_condition",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_runtime_metadata_consistent_for_hybrid_model",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_strict_solver_dae_rejects_unlowered_sample_in_fx",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_dynamic_clock_constructor_without_static_schedule_fails",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_unresolved_function_rejected_in_resolve",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "SIM-009",
        case_id: "sim_009_unresolved_reference_rejected_in_resolve",
        test_file: "tests/sim_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "STRM-001",
        case_id: "strm_001_stream_prefix_inside_connector_ok",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "STRM-001",
        case_id: "strm_001_stream_prefix_outside_connector_rejected",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "STRM-002",
        case_id: "strm_002_stream_connector_with_single_flow_ok",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "STRM-002",
        case_id: "strm_002_stream_connector_without_flow_rejected",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "STRM-002",
        case_id: "strm_002_stream_connector_with_multiple_flows_rejected",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "STRM-003",
        case_id: "strm_003_stream_connector_flow_is_scalar_real_ok",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "STRM-003",
        case_id: "strm_003_stream_connector_flow_must_be_real_rejected",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "STRM-003",
        case_id: "strm_003_stream_connector_flow_must_be_scalar_rejected",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "STRM-006",
        case_id: "strm_006_instream_requires_stream_variable",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "STRM-006",
        case_id: "strm_006_instream_accepts_stream_variable",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "STRM-010",
        case_id: "strm_010_actualstream_requires_stream_variable",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
    ContractCase {
        contract_id: "STRM-010",
        case_id: "strm_010_actualstream_accepts_stream_variable",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "STRM-011",
        case_id: "strm_011_nested_connector_same_level_flow_ok",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Accept,
    },
    ContractCase {
        contract_id: "STRM-011",
        case_id: "strm_011_nested_connector_missing_same_level_flow_rejected",
        test_file: "tests/strm_contracts.rs",
        kind: ContractCaseKind::Compile,
        outcome: ContractCaseOutcome::Reject,
    },
];
