source_roots = []

[model]
file = "../models/Ball.mo"
name = "Ball"

[[plot.views]]
id = "states_time"
title = "States vs Time"
type = "timeseries"
x = "time"
y = [
    "x",
    "v",
]

[rumoca]
task = "simulate"
version = "1"

[signals]

[sim]
solver = "rk-like"
t_end = 10

[viewer]
mode = "results_panel"
