# Generated by Rumoca - CasADi MX Code
#
# This file was automatically generated from a Modelica model.
# Do not edit manually.
#
# MX mode: variables are vector symbols with named slices.
# Functions and the DAE itself are casadi.Function objects,
# enabling differentiation, serialization, and composition.

import casadi as ca
import numpy as np

def create_model():
    """Create CasADi MX model with vector symbols and Function objects.

    Returns:
        dict: Model dictionary with casadi.Function DAE and metadata.
    """

    # Time symbol
    t = ca.MX.sym('t')

    # =========================================================================
    # State Variables (1 variables)
    # =========================================================================
    n_x = 1
    _x = ca.MX.sym('x', n_x)
    _xdot = ca.MX.sym('xdot', n_x)

    # Named slices into _x (0-indexed)
    x = _x[0]  # x

    # der() maps state variables to _xdot slices via CasADi symbolic comparison
    _der_pairs = [
        (x, _xdot[0]),
    ]
    def der(v):
        for _state, _deriv in _der_pairs:
            if ca.is_equal(v, _state):
                return _deriv
        raise ValueError(f"der() called on non-state variable: {v}")

    # =========================================================================
    # Algebraic Variables (1 variables)
    # =========================================================================
    n_z = 1
    _z = ca.MX.sym('z', n_z)

    # Named slices into _z
    y = _z[0]  # y

    # =========================================================================
    # Input Variables (0 variables)
    # =========================================================================
    n_u = 0
    _u = ca.MX.sym('u', 0)

    # =========================================================================
    # Parameters (1 variables)
    # =========================================================================
    n_p = 1
    _p = ca.MX.sym('p', n_p)

    # Named slices into _p
    k = _p[0]  # k

    # =========================================================================
    # Constants
    # =========================================================================

    # =========================================================================
    # User-Defined Functions (0)
    # =========================================================================
    # =========================================================================
    # Continuous Implicit Equations f_x (2)
    # =========================================================================
    f_x = ca.vertcat(
        (der(x) - (-y)),  # equation from 
        (y - (k * x))  # algorithm assignment (algorithm from )
    )

    # =========================================================================
    # DAE as CasADi Function
    # =========================================================================
    dae_fn = ca.Function('dae',
        [_x, _xdot, _z, _u, _p, t],
        [f_x],
        ['x', 'xdot', 'z', 'u', 'p', 't'],
        ['f_x'])

    # =========================================================================
    # Integrator Builder
    # =========================================================================
    def build_integrator(dt, opts=None):
        """Build a CasADi integrator from the implicit DAE.

        Extracts explicit ODE from the implicit residual f_x by computing the
        mass matrix M = df_x/d(xdot), splitting ODE rows (M nonzero) from
        algebraic rows (M zero), then solving for xdot = M_ode^{-1} * (-f_x|_{xdot=0}).

        Args:
            dt: Integration step size.
            opts: Optional dict of integrator options passed to ca.integrator().

        Returns:
            A CasADi integrator Function.
        """
        _M = ca.jacobian(f_x, _xdot)
        _p_full = ca.vertcat(_p, _u)

        if n_z == 0:
            _f0 = ca.substitute(f_x, _xdot, ca.MX.zeros(n_x))
            _ode = ca.solve(_M, -_f0)
            _dae = {'x': _x, 'ode': _ode, 'p': _p_full}
            _solver = 'cvodes'
        else:
            _n_eq = f_x.shape[0]
            _M_fn = ca.Function('mass_matrix_eval', [_x, _xdot, _z, _u, _p, t], [_M])
            _M_num = np.array(_M_fn(
                np.zeros(n_x), np.zeros(n_x), np.zeros(n_z),
                np.zeros(n_u), np.zeros(n_p), 0.0,
            ))
            _ode_rows = [i for i in range(_n_eq) if np.sum(np.abs(_M_num[i, :])) > 1e-15]
            _alg_rows = [i for i in range(_n_eq) if np.sum(np.abs(_M_num[i, :])) <= 1e-15]
            _f_ode = f_x[_ode_rows, :]
            _f_alg = f_x[_alg_rows, :]
            _M_ode = ca.jacobian(_f_ode, _xdot)
            _f_ode0 = ca.substitute(_f_ode, _xdot, ca.MX.zeros(n_x))
            _ode = ca.solve(_M_ode, -_f_ode0)
            _alg = ca.substitute(_f_alg, _xdot, ca.MX.zeros(n_x))
            _dae = {'x': _x, 'z': _z, 'ode': _ode, 'alg': _alg, 'p': _p_full}
            _solver = 'idas'

        return ca.integrator('integrator', _solver, _dae, 0, dt, opts or {})

    # =========================================================================
    # Default Values
    # =========================================================================
    def _flat_start(value, expected_size, var_name):
        arr = np.array(value).reshape(-1)
        if arr.size == expected_size:
            return arr
        if arr.size == 1 and expected_size > 1:
            return np.repeat(arr, expected_size)
        raise ValueError(
            f"Start value size mismatch for {var_name}: expected {expected_size}, got {arr.size}"
        )

    _x0_parts = []
    _x0_parts.append(_flat_start(
        1.0,
        1,
        'x'
    ))
    x0 = np.concatenate(_x0_parts) if _x0_parts else np.array([])

    _p0_parts = []
    _p0_parts.append(_flat_start(
        2.0,
        1,
        'k'
    ))
    p0 = np.concatenate(_p0_parts) if _p0_parts else np.array([])

    return {
        'name': 'Model',
        't': t,
        'x': _x,
        'xdot': _xdot,
        'z': _z,
        'u': _u,
        'p': _p,
        'f_x': f_x,
        'dae_fn': dae_fn,
        'build_integrator': build_integrator,
        'x0': x0,
        'p0': p0,
        'n_x': n_x,
        'n_z': n_z,
        'n_u': n_u,
        'n_p': n_p,
        'state_names': ['x'],
        'algebraic_names': ['y'],
        'input_names': [],
        'param_names': ['k'],
    }


if __name__ == '__main__':
    model = create_model()
    print(f"States ({model['n_x']}): {model['state_names']}")
    print(f"Algebraics ({model['n_z']}): {model['algebraic_names']}")
    print(f"Parameters ({model['n_p']}): {model['param_names']}")

    # Test the DAE function
    dae_fn = model['dae_fn']
    print(f"\nDAE Function: {dae_fn}")
    print(f"  Inputs: {dae_fn.name_in()}")
    print(f"  Outputs: {dae_fn.name_out()}")

    # Verify differentiability
    if model['n_x'] > 0:
        J = dae_fn.jacobian()
        print(f"\nJacobian computable: {J}")