# Generated by Rumoca - CasADi MX Code
#
# This file was automatically generated from a Modelica model.
# Do not edit manually.
#
# MX mode: variables are vector symbols with named slices.
# Functions and the DAE itself are casadi.Function objects,
# enabling differentiation, serialization, and composition.

import casadi as ca
import numpy as np

def _size(x, dim=None):
    """Modelica size() for CasADi MX objects, Python lists, and numpy arrays."""
    if dim is None:
        return len(x) if hasattr(x, '__len__') else x.size1()
    if dim == 1:
        return len(x) if hasattr(x, '__len__') else x.size1()
    return x.shape[dim - 1] if hasattr(x, 'shape') else x.size2()

def _sum(x):
    """Modelica sum() for CasADi: handles lists, comprehensions, and MX vectors."""
    if isinstance(x, list):
        return ca.sum1(ca.vertcat(*x))
    return ca.sum1(x)

def _mul(a, b):
    """Modelica `*` (matrix product) for CasADi.

    Modelica scalar `*` broadcasts; matrix/vector `*` is a linear-algebra
    product. CasADi `*` is element-wise (`ca.times`) and does not broadcast a
    scalar against a matrix or contract inner dimensions, so dispatch here:
      - scalar operand -> element-wise/broadcast `*`
      - column·column  -> dot product (a^T b)
      - otherwise       -> matrix multiply (ca.mtimes)
    """
    a_scalar = not hasattr(a, 'is_scalar') or a.is_scalar()
    b_scalar = not hasattr(b, 'is_scalar') or b.is_scalar()
    if a_scalar or b_scalar:
        return a * b
    if a.is_vector() and b.is_vector() and a.size2() == 1 and b.size2() == 1:
        return ca.mtimes(a.T, b)
    return ca.mtimes(a, b)

def pre(x):
    """Modelica pre() operator for CasADi.

    During continuous integration, pre(x) = x since events are not handled
    mid-step. A full event-driven simulation driver would snapshot discrete
    variables at event boundaries and substitute them here.
    """
    return x

def Clock(*args):
    """Modelica Clock() constructor stub (MLS §16.3).

    In continuous CasADi simulation, clocked constructs are not meaningful.
    Returns 0 so that expressions referencing Clock() do not crash.
    """
    return 0

def previous(x):
    """Modelica previous() operator stub (MLS §16.4).

    In continuous simulation, previous(x) = x (no discrete tick tracking).
    """
    return x

def firstTick(*args):
    """Modelica firstTick() operator stub (MLS §16.10).

    Returns False — not at a first tick in continuous simulation.
    """
    return False

def interval(*args):
    """Modelica interval() operator stub (MLS §16.10).

    Returns 0.0 — clock interval is not meaningful in continuous simulation.
    """
    return 0.0

def hold(x):
    """Modelica hold() operator stub (MLS §16.5.1).

    In continuous simulation, pass through the value unchanged.
    """
    return x

def subSample(x, *args):
    """Modelica subSample() operator stub (MLS §16.5.2). Pass through."""
    return x

def superSample(x, *args):
    """Modelica superSample() operator stub (MLS §16.5.2). Pass through."""
    return x

def shiftSample(x, *args):
    """Modelica shiftSample() operator stub (MLS §16.5.3). Pass through."""
    return x

def backSample(x, *args):
    """Modelica backSample() operator stub (MLS §16.5.3). Pass through."""
    return x

def noClock(x):
    """Modelica noClock() operator stub (MLS §16.5.4). Pass through."""
    return x

def Complex(re, im=0):
    """Complex record constructor — projects to real part for real-valued DAE."""
    return re

def Modelica_ComplexMath_abs(c_re, c_im=0):
    """ComplexMath.abs: magnitude of complex number (uses real sqrt)."""
    return ca.sqrt(ca.power(c_re, 2) + ca.power(c_im, 2))

def Modelica_ComplexMath_sqrt(c1_re, c1_im=0):
    """ComplexMath.sqrt: square root of complex number."""
    r = Modelica_ComplexMath_abs(c1_re, c1_im)
    phi = ca.atan2(c1_im, c1_re)
    return ca.sqrt(r) * ca.cos(phi / 2.0)

def Modelica_ComplexMath_arg(c_re, c_im=0):
    """ComplexMath.arg: argument (phase angle) of complex number."""
    return ca.atan2(c_im, c_re)





def create_model():
    """Create CasADi MX model with vector symbols and Function objects.

    Returns:
        dict: Model dictionary with casadi.Function DAE and metadata.
    """

    # Time symbol
    t = ca.MX.sym('t')
    time = t  # Modelica built-in `time` maps to CasADi time symbol

    # =========================================================================
    # State Variables (6 variables)
    # =========================================================================
    n_x = 6
    _x = ca.MX.sym('x', n_x)
    _xdot = ca.MX.sym('xdot', n_x)

    # Named slices into _x (0-indexed)
    x = _x[0]  # x
    z = _x[1]  # z
    theta = _x[2]  # theta
    vx = _x[3]  # vx
    vz = _x[4]  # vz
    q = _x[5]  # q

    # der() maps state variables to _xdot slices via CasADi symbolic comparison
    _der_pairs = [
        (x, _xdot[0]),
        (z, _xdot[1]),
        (theta, _xdot[2]),
        (vx, _xdot[3]),
        (vz, _xdot[4]),
        (q, _xdot[5]),
    ]
    def der(v):
        for _state, _deriv in _der_pairs:
            if _state.shape == v.shape and ca.is_equal(v, _state):
                return _deriv
        raise ValueError(f"der() called on non-state variable: {v}")

    # =========================================================================
    # Continuous Algebraic Variables (9 algebraics + 0 outputs)
    # =========================================================================
    n_z = 9
    n_z_continuous = 9
    n_z_discrete = 0

    # Declare continuous and discrete algebraic symbols separately so that
    # each is a pure MX symbolic (required by ca.substitute / ca.Function).
    _z_c = ca.MX.sym('z_c', n_z_continuous)
    _z_d = ca.MX.sym('z_d', n_z_discrete)
    _z = ca.vertcat(_z_c, _z_d)

    # Named slices into _z_c (continuous algebraics: y, w)
    V = _z_c[0]  # V
    alpha = _z_c[1]  # alpha
    qbar = _z_c[2]  # qbar
    sigma = _z_c[3]  # sigma
    Cm = _z_c[4]  # Cm
    CL = _z_c[5]  # CL
    CD = _z_c[6]  # CD
    L = _z_c[7]  # L
    D = _z_c[8]  # D

    # Named slices into _z_d (discrete algebraics: z, m)

    # =========================================================================
    # Input Variables (2 variables)
    # =========================================================================
    n_u = 2
    _u = ca.MX.sym('u', n_u)

    # Named slices into _u
    delta_e = _u[0]  # delta_e
    thrust = _u[1]  # thrust

    # =========================================================================
    # Parameters (18 variables)
    # =========================================================================
    n_p = 18
    _p = ca.MX.sym('p', n_p)

    # Named slices into _p
    m = _p[0]  # m
    Iyy = _p[1]  # Iyy
    g = _p[2]  # g
    rho = _p[3]  # rho
    S = _p[4]  # S
    cbar = _p[5]  # cbar
    CL0 = _p[6]  # CL0
    CLa = _p[7]  # CLa
    CD0 = _p[8]  # CD0
    k_ind = _p[9]  # k_ind
    Cm0 = _p[10]  # Cm0
    Cma = _p[11]  # Cma
    Cmq = _p[12]  # Cmq
    Cmde = _p[13]  # Cmde
    CD_fp = _p[14]  # CD_fp
    alpha_stall = _p[15]  # alpha_stall
    blend_width = _p[16]  # blend_width
    eps = _p[17]  # eps

    # =========================================================================
    # Constants
    # =========================================================================


    # Enumeration literal ordinals (MLS §4.9.5)
    StateSelect_never = 1
    StateSelect_avoid = 2
    StateSelect_default = 3
    StateSelect_prefer = 4
    StateSelect_always = 5
    AssertionLevel_warning = 1
    AssertionLevel_error = 2

    # =========================================================================
    # User-Defined Functions (0)
    # =========================================================================
    # =========================================================================
    # Continuous Implicit Equations f_x (15)
    # =========================================================================
    f_x = ca.vertcat(
        ca.vec((V - ca.sqrt(((_mul(vx, vx) + _mul(vz, vz)) + _mul(eps, eps))))),  # top-level model equation
        ca.vec((alpha - (theta - ca.atan2(vz, vx)))),  # top-level model equation
        ca.vec((qbar - _mul(_mul(_mul(0.5, rho), V), V))),  # top-level model equation
        ca.vec((sigma - _mul(0.5, (1 + ca.tanh(((alpha - alpha_stall) / blend_width)))))),  # top-level model equation
        ca.vec((CL - (_mul((1 - sigma), (CL0 + _mul(CLa, alpha))) + _mul(sigma, ca.sin(_mul(2, alpha)))))),  # top-level model equation
        ca.vec((CD - (_mul((1 - sigma), (CD0 + _mul(k_ind, ca.power((CL0 + _mul(CLa, alpha)), 2)))) + _mul(_mul(sigma, CD_fp), ca.power(ca.sin(alpha), 2))))),  # top-level model equation
        ca.vec((Cm - (((Cm0 + _mul(Cma, alpha)) + _mul(_mul(Cmq, (cbar / _mul(2, V))), q)) + _mul(Cmde, delta_e)))),  # top-level model equation
        ca.vec((L - _mul(_mul(qbar, S), CL))),  # top-level model equation
        ca.vec((D - _mul(_mul(qbar, S), CD))),  # top-level model equation
        ca.vec((der(x) - vx)),  # top-level model equation
        ca.vec((der(z) - vz)),  # top-level model equation
        ca.vec((der(theta) - q)),  # top-level model equation
        ca.vec((_mul(m, der(vx)) - ((((-_mul(D, vx)) - _mul(L, vz)) / V) + _mul(thrust, ca.cos(theta))))),  # top-level model equation
        ca.vec((_mul(m, der(vz)) - (((((-_mul(D, vz)) + _mul(L, vx)) / V) + _mul(thrust, ca.sin(theta))) - _mul(m, g)))),  # top-level model equation
        ca.vec((_mul(Iyy, der(q)) - _mul(_mul(_mul(qbar, S), cbar), Cm)))  # top-level model equation
    )

    # =========================================================================
    # DAE as CasADi Function
    # =========================================================================
    # _z is vertcat(_z_c, _z_d) which is not a pure symbol, so we create a
    # fresh monolithic symbol for the Function interface and substitute.
    _z_sym = ca.MX.sym('z', n_z)
    _f_x_for_fn = ca.substitute(
        [f_x],
        [_z_c, _z_d],
        [_z_sym[:n_z_continuous], _z_sym[n_z_continuous:]]
    )[0]
    dae_fn = ca.Function('dae',
        [_x, _xdot, _z_sym, _u, _p, t],
        [_f_x_for_fn],
        ['x', 'xdot', 'z', 'u', 'p', 't'],
        ['f_x'])

    # =========================================================================
    # Integrator Builder
    # =========================================================================
    def build_integrator(dt, opts=None, method='idas'):
        """Build a CasADi integrator from the implicit DAE residual.

        For pure ODEs (no algebraics, exactly n_x equations), converts to
        explicit form via mass-matrix inversion and uses CVODES.

        For DAE systems or over-determined ODEs, uses an augmented-z
        approach: xdot symbols are included in the algebraic vector so the
        chosen DAE solver receives the original residual directly.

        Args:
            dt: Time grid (scalar step or array of output times).
            opts: Optional dict of integrator options passed to ca.integrator().
            method: DAE solver — 'idas' (default) or 'collocation'.
                IDAS is faster but requires consistent initial conditions.
                Collocation handles structurally singular DAEs where
                IDACalcIC fails.

        Returns:
            A CasADi integrator Function.
        """
        # Discrete variables are treated as fixed parameters during continuous
        # integration (MLS §8.5). Only continuous algebraics (y, w) are part of
        # the DAE solved by IDAS. Discrete variables (z, m) are updated at
        # event boundaries by the simulation driver.
        # _z_c and _z_d are already pure MX symbols (declared at module level).
        if n_z_discrete > 0:
            _p_full = ca.vertcat(_p, _u, _z_d)
        else:
            _p_full = ca.vertcat(_p, _u)
        _n_eq = f_x.shape[0]

        # Pure ODE: exactly n_x equations, no continuous algebraics → explicit CVODES
        if _n_eq == n_x and n_z_continuous == 0:
            _M = ca.jacobian(f_x, _xdot)
            _f0 = ca.substitute(f_x, _xdot, ca.MX.zeros(n_x))
            _ode = ca.solve(_M, -_f0)
            _dae = {'x': _x, 't': t, 'ode': _ode, 'p': _p_full}
            return ca.integrator('integrator', 'cvodes', _dae, 0, dt, opts or {})

        # General DAE / over-determined ODE: augmented-z approach.
        # Include xdot in the algebraic vector so IDAS solves the original
        # implicit residual f_x(x, xdot, z_c, p, t) = 0 directly.
        # Only continuous algebraics are in the augmented z vector.
        # CasADi requires purely symbolic integrator inputs, so we create a
        # fresh symbol and substitute the original xdot/_z_c references.
        _n_z_aug = n_x + n_z_continuous
        _z_aug = ca.MX.sym('z_aug', _n_z_aug)
        _xdot_aug = _z_aug[:n_x]
        _z_c_aug = _z_aug[n_x:]
        _f_x_sub = ca.substitute([f_x], [_xdot, _z_c], [_xdot_aug, _z_c_aug])[0]
        _dae = {
            'x': _x, 'z': _z_aug, 't': t,
            'ode': _xdot_aug,
            'alg': _f_x_sub,
            'p': _p_full,
        }
        return ca.integrator('integrator', method, _dae, 0, dt, opts or {})

    # =========================================================================
    # Default Values
    # =========================================================================
    def _flat_start(value, expected_size, var_name, params=None):
        # Convert value to a float64 numpy array.  A start value may be a CasADi
        # symbolic expression — e.g. a state whose start references a parameter
        # (`p(start = p_start)`).  np.array() fails on those, so substitute the
        # numeric parameter vector and evaluate to a constant before retrying.
        if isinstance(value, (bool, np.bool_)):
            value = float(value)
        try:
            arr = np.array(value, dtype=np.float64).reshape(-1)
        except Exception:
            # CasADi raises a bare Exception on implicit numeric conversion of a
            # symbolic value; substitute the numeric parameter vector and evaluate.
            try:
                v = value
                if params is not None and n_p > 0:
                    v = ca.substitute(v, _p, ca.DM(np.asarray(params, dtype=np.float64)))
                arr = np.array(ca.evalf(v)).astype(np.float64).reshape(-1)
            except Exception:
                try:
                    arr = np.array([float(value)], dtype=np.float64)
                except Exception:
                    arr = np.zeros(expected_size, dtype=np.float64)
        if arr.size == expected_size:
            return arr
        if arr.size == 1 and expected_size > 1:
            return np.repeat(arr, expected_size)
        raise ValueError(
            f"Start value size mismatch for {var_name}: expected {expected_size}, got {arr.size}"
        )

    # Parameters first: their numeric values resolve symbolic state/algebraic
    # starts that reference a parameter (e.g. `p(start = p_start)`). Accumulate
    # into a running vector so a parameter default that references an
    # earlier-defined parameter (e.g. `J = [ixx, …]`) resolves by substitution.
    p0 = np.zeros(n_p)
    _p0_off = 0
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        1.5,
        _p0_sz,
        'm', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.08,
        _p0_sz,
        'Iyy', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        9.81,
        _p0_sz,
        'g', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        1.225,
        _p0_sz,
        'rho', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.25,
        _p0_sz,
        'S', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.18,
        _p0_sz,
        'cbar', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.3,
        _p0_sz,
        'CL0', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        5.0,
        _p0_sz,
        'CLa', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.05,
        _p0_sz,
        'CD0', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.08,
        _p0_sz,
        'k_ind', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.05,
        _p0_sz,
        'Cm0', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        -0.7,
        _p0_sz,
        'Cma', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        -8.0,
        _p0_sz,
        'Cmq', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        2.6,
        _p0_sz,
        'Cmde', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        2.0,
        _p0_sz,
        'CD_fp', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.262,
        _p0_sz,
        'alpha_stall', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.05,
        _p0_sz,
        'blend_width', p0
    )
    _p0_off += _p0_sz
    _p0_sz = 1
    p0[_p0_off:_p0_off + _p0_sz] = _flat_start(
        0.001,
        _p0_sz,
        'eps', p0
    )
    _p0_off += _p0_sz

    _x0_parts = []
    _x0_parts.append(_flat_start(
        0.0,
        1,
        'x', p0
    ))
    _x0_parts.append(_flat_start(
        0.0,
        1,
        'z', p0
    ))
    _x0_parts.append(_flat_start(
        0.0,
        1,
        'theta', p0
    ))
    _x0_parts.append(_flat_start(
        13.0,
        1,
        'vx', p0
    ))
    _x0_parts.append(_flat_start(
        0.0,
        1,
        'vz', p0
    ))
    _x0_parts.append(_flat_start(
        0.0,
        1,
        'q', p0
    ))
    x0 = np.concatenate(_x0_parts) if _x0_parts else np.array([])

    # Algebraic initial guesses (continuous y, w then discrete z, m)
    _z0_parts = []
    _z0_parts.append(_flat_start(
        0.0,
        1,
        'V', p0
    ))
    _z0_parts.append(_flat_start(
        0.0,
        1,
        'alpha', p0
    ))
    _z0_parts.append(_flat_start(
        0.0,
        1,
        'qbar', p0
    ))
    _z0_parts.append(_flat_start(
        0.0,
        1,
        'sigma', p0
    ))
    _z0_parts.append(_flat_start(
        0.0,
        1,
        'Cm', p0
    ))
    _z0_parts.append(_flat_start(
        0.0,
        1,
        'CL', p0
    ))
    _z0_parts.append(_flat_start(
        0.0,
        1,
        'CD', p0
    ))
    _z0_parts.append(_flat_start(
        0.0,
        1,
        'L', p0
    ))
    _z0_parts.append(_flat_start(
        0.0,
        1,
        'D', p0
    ))
    z0 = np.concatenate(_z0_parts) if _z0_parts else np.array([])

    _zd0_parts = []
    zd0 = np.concatenate(_zd0_parts) if _zd0_parts else np.array([])
    u0 = np.zeros(n_u)
    p_full0 = np.concatenate([p0, u0, zd0])

    return {
        'name': 'Model',
        't': t,
        'x': _x,
        'xdot': _xdot,
        'z': _z,
        'u': _u,
        'p': _p,
        'f_x': f_x,
        'dae_fn': dae_fn,
        'build_integrator': build_integrator,
        'x0': x0,
        'p0': p0,
        'u0': u0,
        'z0': z0,
        'zd0': zd0,
        'p_full0': p_full0,
        'n_x': n_x,
        'n_z': n_z,
        'n_z_continuous': n_z_continuous,
        'n_u': n_u,
        'n_p': n_p,
        'state_names': ['x', 'z', 'theta', 'vx', 'vz', 'q'],
        'algebraic_names': ['V', 'alpha', 'qbar', 'sigma', 'Cm', 'CL', 'CD', 'L', 'D', ],
        'input_names': ['delta_e', 'thrust'],
        'param_names': ['m', 'Iyy', 'g', 'rho', 'S', 'cbar', 'CL0', 'CLa', 'CD0', 'k_ind', 'Cm0', 'Cma', 'Cmq', 'Cmde', 'CD_fp', 'alpha_stall', 'blend_width', 'eps'],
    }


# =========================================================================
# Convenience Functions
# =========================================================================

def get_state_names():
    """Get list of state variable names."""
    return ['x', 'z', 'theta', 'vx', 'vz', 'q']


def get_param_names():
    """Get list of parameter names."""
    return ['m', 'Iyy', 'g', 'rho', 'S', 'cbar', 'CL0', 'CLa', 'CD0', 'k_ind', 'Cm0', 'Cma', 'Cmq', 'Cmde', 'CD_fp', 'alpha_stall', 'blend_width', 'eps']


def get_input_names():
    """Get list of input variable names."""
    return ['delta_e', 'thrust']


def simulate(x0=None, p0=None, u0=None, zd0=None, t_span=(0.0, 1.0), dt=0.01):
    """Simulate the model using CasADi integrator.

    Args:
        x0: Initial state (numpy array). Uses model defaults if None.
        p0: Parameters (numpy array). Uses model defaults if None.
        u0: Inputs (numpy array). Uses zeros if None.
        zd0: Discrete variables held fixed during continuous integration.
        t_span: Tuple of (t0, tf) time span.
        dt: Integration time step.

    Returns:
        Tuple of (times, states) where times is a 1-D array of length
        n_steps+1 and states is an (n_x, n_steps+1) numpy array.
    """
    model = create_model()
    if x0 is None:
        x0 = model['x0']
    if p0 is None:
        p0 = model['p0']
    if u0 is None:
        u0 = model['u0']
    if zd0 is None:
        zd0 = model['zd0']

    t0, tf = t_span
    tgrid = np.arange(t0, tf + dt * 0.5, dt)
    integrator = model['build_integrator'](tgrid)
    p_full = np.concatenate([p0, u0, zd0])
    result = integrator(x0=x0, p=p_full)
    states = np.array(result['xf'])
    return tgrid, states


def simulate_csv(t_end=1.0, dt=0.01):
    """Run simulation and return CSV string.

    Args:
        t_end: End time (start is always 0).
        dt: Integration time step.

    Returns:
        CSV string with header row and one row per time step.
    """
    ts, xs = simulate(t_span=(0.0, t_end), dt=dt)
    names = get_state_names()
    header = "time," + ",".join(names)
    rows = [header]
    for j in range(len(ts)):
        row = [f"{float(ts[j]):.10g}"]
        for i in range(xs.shape[0]):
            row.append(f"{float(xs[i, j]):.10g}")
        rows.append(",".join(row))
    return "\n".join(rows)


if __name__ == '__main__':
    model = create_model()
    print(f"States ({model['n_x']}): {model['state_names']}")
    print(f"Algebraics ({model['n_z']}): {model['algebraic_names']}")
    print(f"Parameters ({model['n_p']}): {model['param_names']}")

    # Test the DAE function
    dae_fn = model['dae_fn']
    print(f"\nDAE Function: {dae_fn}")
    print(f"  Inputs: {dae_fn.name_in()}")
    print(f"  Outputs: {dae_fn.name_out()}")

    # Verify differentiability
    if model['n_x'] > 0:
        J = dae_fn.jacobian()
        print(f"\nJacobian computable: {J}")

    # Quick simulation demo
    if model['n_x'] > 0:
        ts, xs = simulate()
        print(f"\nSimulated {len(ts)} steps, final state: {xs[:, -1]}")