use anyhow::{Context, Result};
use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_RESULTS_DIR: &str = "target/msl/results";
const DEFAULT_OUTPUT_FILE: &str = "msl_pr_comment.md";
const COMMENT_MARKER: &str = "<!-- rumoca-msl-quality-summary -->";

#[derive(Debug, clap::Args, Clone)]
pub struct Args {
    /// MSL results directory containing markdown report artifacts
    #[arg(long, default_value = DEFAULT_RESULTS_DIR)]
    pub results_dir: PathBuf,
    /// Markdown file to write for CI PR publication
    #[arg(long)]
    pub out: Option<PathBuf>,
}

pub fn run(args: Args) -> Result<()> {
    let out = args
        .out
        .clone()
        .unwrap_or_else(|| args.results_dir.join(DEFAULT_OUTPUT_FILE));
    if let Some(parent) = out.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }
    let body = render_pr_comment(&args.results_dir)?;
    fs::write(&out, body).with_context(|| format!("failed to write {}", out.display()))?;
    println!("MSL PR comment summary written to {}", out.display());
    Ok(())
}

fn render_pr_comment(results_dir: &Path) -> Result<String> {
    let mut body = String::new();
    body.push_str(COMMENT_MARKER);
    body.push_str("\n### MSL Quality Gate Summary\n\n");
    body.push_str("_Generated by `cargo xtask repo msl pr-comment` from CI result artifacts._\n\n");

    if let Some(summary) = render_quality_snapshot_summary(results_dir)? {
        body.push_str(&summary);
        body.push('\n');
    }

    append_report_section(
        &mut body,
        "Package Pass Rates",
        &results_dir.join("msl_package_pass_rates.md"),
    )?;
    append_report_section(
        &mut body,
        "MLS Contract Coverage",
        &results_dir.join("mls_contract_coverage.md"),
    )?;
    append_report_section(
        &mut body,
        "Trace Accuracy vs OMC",
        &results_dir.join("msl_package_trace_accuracy.md"),
    )?;
    body.push_str("#### Compile Speed vs OMC\n\n");
    body.push_str(&render_speed_section(results_dir)?);
    body.push_str("\n\n");
    append_optional_link_note(&mut body, results_dir);

    Ok(body)
}

fn render_quality_snapshot_summary(results_dir: &Path) -> Result<Option<String>> {
    let quality_path = results_dir.join("msl_quality_current.json");
    if !quality_path.is_file() {
        return Ok(None);
    }
    let text = fs::read_to_string(&quality_path)
        .with_context(|| format!("failed to read {}", quality_path.display()))?;
    let json: Value = serde_json::from_str(&text)
        .with_context(|| format!("failed to parse {}", quality_path.display()))?;

    let run_scope = json_str(&json, "run_scope").unwrap_or("unknown");
    let msl_version = json_str(&json, "msl_version").unwrap_or("unknown");
    let omc_version = json_str(&json, "omc_version").unwrap_or("unknown");
    let compiled = json_u64(&json, "compiled_models").unwrap_or(0);
    let balance_denominator = json_u64(&json, "balance_denominator").unwrap_or(0);
    let balanced = json_u64(&json, "balanced_models").unwrap_or(0);
    let initial_balanced = json_u64(&json, "initial_balanced_models").unwrap_or(0);
    let sim_ok = json_u64(&json, "sim_ok").unwrap_or(0);
    let sim_attempted = json_u64(&json, "sim_attempted").unwrap_or(0);

    Ok(Some(format!(
        "| Scope | MSL | OMC | Compile | Balance | Initial Balance | Simulation |\n\
         |---|---|---|---:|---:|---:|---:|\n\
         | `{run_scope}` | `{msl_version}` | `{omc_version}` | {compiled}/{balance_denominator} | {balanced}/{balance_denominator} | {initial_balanced}/{balance_denominator} | {sim_ok}/{sim_attempted} |\n"
    )))
}

/// Render the compile-speed table and mermaid scalability plot from
/// `msl_speed_comparison.json`. The mermaid plot lives here, in the PR-comment
/// step, rather than being emitted on every OMC run; local developers use the
/// `msl_speed_scaling.html` uPlot view instead.
fn render_speed_section(results_dir: &Path) -> Result<String> {
    let path = results_dir.join("msl_speed_comparison.json");
    if !path.is_file() {
        return Ok("_Report was not produced in this run._\n".to_string());
    }
    let json: Value = serde_json::from_str(
        &fs::read_to_string(&path).with_context(|| format!("failed to read {}", path.display()))?,
    )
    .with_context(|| format!("failed to parse {}", path.display()))?;
    let models = json
        .get("models_compared")
        .and_then(Value::as_u64)
        .unwrap_or(0);
    if models == 0 {
        return Ok(
            "_No models had both an agreeing OMC/rumoca trace and compile timing to compare._\n"
                .to_string(),
        );
    }
    let mut out = String::new();
    if let Some(speedup) = json.get("speedup") {
        let get = |key| speedup.get(key).and_then(Value::as_f64);
        if let (Some(min), Some(median), Some(max)) = (get("min"), get("median"), get("max")) {
            out.push_str(&format!(
                "Over **{models}** models where OMC and rumoca traces agree, rumoca compiled a \
                 **median {median:.1}× faster** than OMC (min {min:.1}×, max {max:.1}×). \
                 `speedup = OMC_compile_s / rumoca_compile_s`; OMC compile = `timeTotal − timeSimulation`.\n\n"
            ));
        }
    }
    out.push_str(
        "| scalar equations | models | rumoca median (s) | OMC median (s) | speedup (×) |\n\
         |---|--:|--:|--:|--:|\n",
    );
    let bins = json
        .get("scaling_by_scalar_equations")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let (mut labels, mut rumoca_line, mut omc_line) = (Vec::new(), Vec::new(), Vec::new());
    for bin in &bins {
        let low = bin.get("bin_low").and_then(Value::as_u64).unwrap_or(0);
        let label = match bin.get("bin_high_inclusive").and_then(Value::as_u64) {
            Some(high) => format!("{low}-{high}"),
            None => format!("{low}+"),
        };
        let count = bin.get("models").and_then(Value::as_u64).unwrap_or(0);
        let median = |group| {
            bin.get(group)
                .and_then(|value| value.get("median"))
                .and_then(Value::as_f64)
                .unwrap_or(0.0)
        };
        let rumoca = median("rumoca_compile_seconds");
        let omc = median("omc_compile_seconds");
        let speedup = bin
            .get("speedup_median")
            .and_then(Value::as_f64)
            .unwrap_or(0.0);
        out.push_str(&format!(
            "| {label} | {count} | {rumoca:.4} | {omc:.4} | {speedup:.2} |\n"
        ));
        labels.push(format!("\"{label}\""));
        rumoca_line.push(format!("{rumoca:.4}"));
        omc_line.push(format!("{omc:.4}"));
    }
    out.push_str(&format!(
        "\nScalability — median compile seconds vs flattened system size (line 1 = rumoca, line 2 = OMC):\n\n\
         ```mermaid\nxychart-beta\n    title \"Compile time vs system size (median s) — line 1 = rumoca, line 2 = OMC\"\n    x-axis [{}]\n    y-axis \"median compile seconds\"\n    line [{}]\n    line [{}]\n```\n",
        labels.join(", "),
        rumoca_line.join(", "),
        omc_line.join(", ")
    ));
    Ok(out)
}

fn append_report_section(body: &mut String, title: &str, path: &Path) -> Result<()> {
    body.push_str(&format!("#### {title}\n\n"));
    if !path.is_file() {
        body.push_str("_Report was not produced in this run._\n\n");
        return Ok(());
    }
    let text =
        fs::read_to_string(path).with_context(|| format!("failed to read {}", path.display()))?;
    body.push_str(text.trim());
    body.push_str("\n\n");
    Ok(())
}

fn append_optional_link_note(body: &mut String, results_dir: &Path) {
    let compatibility = results_dir.join("msl_compatibility_report.md");
    let modelica_test = results_dir.join("modelica_test_catalog.md");
    if !compatibility.is_file() && !modelica_test.is_file() {
        return;
    }

    body.push_str("#### Additional Artifacts\n\n");
    if compatibility.is_file() {
        body.push_str("- `msl_compatibility_report.md`\n");
    }
    if modelica_test.is_file() {
        body.push_str("- `modelica_test_catalog.md`\n");
    }
    body.push('\n');
}

fn json_str<'a>(json: &'a Value, key: &str) -> Option<&'a str> {
    json.get(key).and_then(Value::as_str)
}

fn json_u64(json: &Value, key: &str) -> Option<u64> {
    json.get(key).and_then(Value::as_u64)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pr_comment_renders_existing_msl_reports() {
        let temp = tempfile::tempdir().expect("tempdir");
        let results = temp.path();
        fs::write(
            results.join("msl_quality_current.json"),
            r#"{
                "run_scope": "full",
                "msl_version": "v4.1.0",
                "omc_version": "OpenModelica 1.26.1",
                "compiled_models": 10,
                "balance_denominator": 10,
                "balanced_models": 9,
                "initial_balanced_models": 8,
                "sim_ok": 7,
                "sim_attempted": 10
            }"#,
        )
        .expect("write quality snapshot");
        fs::write(
            results.join("mls_contract_coverage.md"),
            "| MLS Category | n |\n|---|---:|\n| OTHER | 10 |\n",
        )
        .expect("write coverage");
        fs::write(
            results.join("msl_package_pass_rates.md"),
            "| MSL Package | n |\n|---|---:|\n| Blocks | 10 |\n",
        )
        .expect("write pass rates");
        fs::write(
            results.join("msl_package_trace_accuracy.md"),
            "| MSL Package | Trace |\n|---|---:|\n| Blocks | 90% |\n",
        )
        .expect("write trace accuracy");

        let rendered = render_pr_comment(results).expect("render comment");
        assert!(rendered.contains(COMMENT_MARKER));
        assert!(rendered.contains(
            "| `full` | `v4.1.0` | `OpenModelica 1.26.1` | 10/10 | 9/10 | 8/10 | 7/10 |"
        ));
        assert!(rendered.contains("#### MLS Contract Coverage"));
        assert!(rendered.contains("| OTHER | 10 |"));
    }

    #[test]
    fn pr_comment_marks_missing_reports_without_failing() {
        let temp = tempfile::tempdir().expect("tempdir");
        let rendered = render_pr_comment(temp.path()).expect("render missing-report comment");
        assert!(rendered.contains(COMMENT_MARKER));
        assert!(rendered.contains("_Report was not produced in this run._"));
    }
}
